-- ch03t3 "MO Theory & Resonance" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch03t3s1 Molecular Orbital Theory & Bond Order   (axai_ch03_091..105)
--   ch03t3s2 Resonance, Polarity & Dipole Moment      (axai_ch03_106..120)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch03t3s1', 'Molecular Orbital Theory & Bond Order', 'ch03t3', 'ch03', 'chem', 1),
  ('ch03t3s2', 'Resonance, Polarity & Dipole Moment', 'ch03t3', 'ch03', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch03t3s1 Molecular Orbital Theory & Bond Order =====
('axai_ch03_091', 'In molecular orbital theory, molecular orbitals are formed by the:', 'mcq', '["linear combination of atomic orbitals","fusion of atomic nuclei","transfer of electrons","ionisation of atoms"]', 'linear combination of atomic orbitals', 'easy', 1, 'both', 'Molecular orbitals are obtained by the linear combination of atomic orbitals (LCAO).', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_092', 'Compared with the atomic orbitals from which it forms, a bonding molecular orbital has:', 'mcq', '["higher energy","lower energy","the same energy","no energy"]', 'lower energy', 'easy', 2, 'both', 'A bonding molecular orbital is more stable and therefore lower in energy than the combining atomic orbitals.', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_093', 'Bond order in molecular orbital theory is given by:', 'mcq', '["(Nb + Na)","½(Nb − Na)","(Nb − Na)","½(Nb + Na)"]', '½(Nb − Na)', 'easy', 2, 'both', 'Bond order = ½(number of bonding electrons − number of antibonding electrons).', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_094', 'The bond order of a hydrogen molecule (H₂) is:', 'mcq', '["0","0.5","1","2"]', '1', 'easy', 2, 'both', 'H₂ has 2 bonding and 0 antibonding electrons: ½(2 − 0) = 1.', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_095', 'The He₂ molecule does not exist because its bond order is:', 'mcq', '["0","0.5","1","2"]', '0', 'easy', 3, 'both', 'He₂ has 2 bonding and 2 antibonding electrons: ½(2 − 2) = 0, so no net bond forms.', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_096', 'The bond order of an oxygen molecule (O₂) is:', 'mcq', '["1","1.5","2","3"]', '2', 'medium', 4, 'both', 'O₂ has 10 bonding and 6 antibonding electrons: ½(10 − 6) = 2.', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_097', 'Molecular orbital theory successfully explains that the O₂ molecule is:', 'mcq', '["diamagnetic","paramagnetic","ionic","non-existent"]', 'paramagnetic', 'medium', 5, 'both', 'The two unpaired electrons in the π* orbitals make O₂ paramagnetic — a key success of MO theory.', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_098', 'The bond order of a nitrogen molecule (N₂) is:', 'mcq', '["1","2","3","2.5"]', '3', 'medium', 4, 'both', 'N₂ has 10 bonding and 4 antibonding electrons: ½(10 − 4) = 3.', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_099', 'The number of unpaired electrons in an O₂ molecule is:', 'mcq', '["0","1","2","3"]', '2', 'medium', 5, 'both', 'The two π* orbitals each hold one electron, giving O₂ two unpaired electrons.', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_100', 'Among N₂, O₂ and F₂, the species with the highest bond order is:', 'mcq', '["N₂","O₂","F₂","all equal"]', 'N₂', 'medium', 5, 'both', 'Bond orders are N₂ = 3, O₂ = 2, F₂ = 1, so N₂ has the highest.', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_101', 'The bond order of the dioxygenyl cation (O₂⁺) is:', 'mcq', '["1.5","2.0","2.5","3.0"]', '2.5', 'hard', 6, 'jee', 'Removing one antibonding electron from O₂ gives 10 bonding and 5 antibonding electrons: ½(10 − 5) = 2.5.', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_102', 'The correct order of stability (bond order) is:', 'mcq', '["O₂²⁻ > O₂⁻ > O₂ > O₂⁺","O₂⁺ > O₂ > O₂⁻ > O₂²⁻","O₂ > O₂⁺ > O₂⁻ > O₂²⁻","O₂⁻ > O₂ > O₂⁺ > O₂²⁻"]', 'O₂⁺ > O₂ > O₂⁻ > O₂²⁻', 'hard', 7, 'jee', 'Adding electrons to antibonding orbitals lowers bond order: O₂⁺ (2.5) > O₂ (2) > O₂⁻ (1.5) > O₂²⁻ (1).', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_103', 'Which of the following species is diamagnetic?', 'mcq', '["O₂","B₂","N₂","O₂⁺"]', 'N₂', 'hard', 7, 'jee', 'N₂ has all electrons paired (bond order 3), so it is diamagnetic; O₂, B₂ and O₂⁺ have unpaired electrons.', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_104', 'The B₂ molecule is paramagnetic because, for molecules up to N₂, the:', 'mcq', '["σ2p orbital lies below the π2p orbitals","π2p orbitals lie below the σ2p orbital","2s and 2p orbitals do not mix","antibonding orbitals are filled first"]', 'π2p orbitals lie below the σ2p orbital', 'hard', 8, 'jee', 'Because of s–p mixing the π2p orbitals fill before σ2p in B₂; its last two electrons occupy degenerate π orbitals singly, making it paramagnetic.', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
('axai_ch03_105', 'The bond order of the nitric oxide (NO) molecule is:', 'mcq', '["1.5","2.0","2.5","3.0"]', '2.5', 'hard', 6, 'jee', 'NO has 15 electrons: 10 bonding and 5 antibonding, giving ½(10 − 5) = 2.5.', 'chem', 'ch03', 'ch03t3', 'ch03t3s1'),
-- ===== ch03t3s2 Resonance, Polarity & Dipole Moment =====
('axai_ch03_106', 'Resonance structures of a molecule differ only in the:', 'mcq', '["positions of the atomic nuclei","positions of the electrons","number of atoms","molecular mass"]', 'positions of the electrons', 'easy', 1, 'both', 'Canonical (resonance) forms differ only in electron distribution; the positions of the nuclei stay fixed.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_107', 'The SI-related unit commonly used for dipole moment is the:', 'mcq', '["Debye","Pascal","Joule","Newton"]', 'Debye', 'easy', 2, 'both', 'Dipole moment is usually expressed in Debye (D), where 1 D ≈ 3.34 × 10⁻³⁰ C·m.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_108', 'A polar covalent bond forms between two atoms that have:', 'mcq', '["identical electronegativities","different electronegativities","no valence electrons","the same atomic number"]', 'different electronegativities', 'easy', 2, 'both', 'Unequal sharing of the bonding electrons, caused by an electronegativity difference, makes a bond polar.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_109', 'The net dipole moment of a carbon dioxide (CO₂) molecule is:', 'mcq', '["zero","1.5 D","1.85 D","very large"]', 'zero', 'easy', 2, 'both', 'CO₂ is linear, so the two equal and opposite C=O bond dipoles cancel, giving zero net dipole moment.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_110', 'The dipole moment (μ) of a bond is given by the product of:', 'mcq', '["charge and distance of separation","mass and velocity","force and area","pressure and volume"]', 'charge and distance of separation', 'easy', 3, 'both', 'Dipole moment μ = q × d, the magnitude of charge times the distance between the charge centres.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_111', 'A water (H₂O) molecule has a net dipole moment because it is:', 'mcq', '["linear","bent","tetrahedral and symmetric","non-polar"]', 'bent', 'medium', 4, 'both', 'The bent shape means the two O–H bond dipoles do not cancel, giving water a net dipole moment.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_112', 'Which of the following molecules is non-polar?', 'mcq', '["NH₃","H₂O","BF₃","HCl"]', 'BF₃', 'medium', 5, 'both', 'BF₃ is symmetric trigonal planar, so its three bond dipoles cancel to give zero net dipole moment.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_113', 'The dipole moment of NH₃ is greater than that of NF₃ because in NH₃ the:', 'mcq', '["lone pair dipole adds to the bond dipoles","lone pair dipole opposes the bond dipoles","molecule is non-polar","nitrogen is less electronegative than fluorine"]', 'lone pair dipole adds to the bond dipoles', 'medium', 6, 'jee', 'In NH₃ the lone pair moment and the N–H bond moments point the same way and add; in NF₃ they oppose, lowering the net dipole.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_114', 'All three carbon–oxygen bonds in the carbonate ion (CO₃²⁻) are equal in length because of:', 'mcq', '["resonance","hydrogen bonding","ionic bonding","sp hybridisation"]', 'resonance', 'medium', 5, 'both', 'Resonance delocalises the electrons over all three C–O bonds, making them identical in length.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_115', 'A resonance hybrid is:', 'mcq', '["less stable than any canonical form","more stable than any single canonical form","identical in energy to each canonical form","not a real structure"]', 'more stable than any single canonical form', 'medium', 5, 'both', 'Delocalisation lowers the energy, so the resonance hybrid is more stable than any contributing canonical structure.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_116', 'The correct decreasing order of dipole moment among the hydrogen halides is:', 'mcq', '["HI > HBr > HCl > HF","HF > HCl > HBr > HI","HCl > HF > HBr > HI","HBr > HF > HCl > HI"]', 'HF > HCl > HBr > HI', 'hard', 6, 'jee', 'The electronegativity difference (and hence bond polarity) is greatest for HF and falls down the group, so HF has the largest dipole moment.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_117', 'Which of the following molecules has zero dipole moment?', 'mcq', '["CHCl₃","CH₃Cl","CCl₄","CH₂Cl₂"]', 'CCl₄', 'hard', 6, 'jee', 'CCl₄ is symmetric tetrahedral, so the four C–Cl bond dipoles cancel; the others are unsymmetrical and polar.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_118', 'In benzene all six carbon–carbon bonds have the same length, intermediate between a single and a double bond, because of:', 'mcq', '["resonance (delocalisation)","sp³ hybridisation","ionic character","hydrogen bonding"]', 'resonance (delocalisation)', 'hard', 6, 'jee', 'The π electrons are delocalised over the ring, so every C–C bond has identical, intermediate length.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_119', 'The dipole moment of trans-1,2-dichloroethene is:', 'mcq', '["zero","equal to that of the cis isomer","greater than that of the cis isomer","very large"]', 'zero', 'hard', 7, 'jee', 'In the trans isomer the two equal C–Cl bond dipoles point in opposite directions and cancel, giving zero net dipole.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2'),
('axai_ch03_120', 'All three sulfur–oxygen bonds in sulfur trioxide (SO₃) are equal in length, which is best explained by:', 'mcq', '["resonance among equivalent canonical forms","an expanded octet only","hydrogen bonding","its ionic character"]', 'resonance among equivalent canonical forms', 'hard', 7, 'jee', 'Equivalent resonance structures delocalise the π bonding equally over all three S–O bonds, making them identical.', 'chem', 'ch03', 'ch03t3', 'ch03t3s2')
on conflict (id) do nothing;
