-- ch10t2 "Halogen Family & Noble Gases (Gr 17–18)" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch10t2s1 Group 17: Halogens      (axai_ch10_031..045)
--   ch10t2s2 Group 18: Noble Gases   (axai_ch10_046..060)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch10t2s1', 'Group 17: Halogens', 'ch10t2', 'ch10', 'chem', 1),
  ('ch10t2s2', 'Group 18: Noble Gases', 'ch10t2', 'ch10', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch10t2s1 Group 17: Halogens =====
('axai_ch10_031', 'The general valence-shell electronic configuration of Group 17 (halogens) is:', 'mcq', '["ns²np³","ns²np⁴","ns²np⁵","ns²np⁶"]', 'ns²np⁵', 'easy', 1, 'both', 'Halogens have seven valence electrons, one short of an octet, with the configuration ns²np⁵.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_032', 'Which halogen is a liquid at room temperature?', 'mcq', '["fluorine","chlorine","bromine","iodine"]', 'bromine', 'easy', 1, 'both', 'Bromine is the only halogen that is a dark red-brown liquid at room temperature.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_033', 'The most common oxidation state shown by halogens in their salts (halides) is:', 'mcq', '["+1","-1","+5","+7"]', '-1', 'easy', 2, 'both', 'By gaining one electron to complete their octet, halogens commonly show the -1 oxidation state in halides.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_034', 'Which halogen is the most electronegative element in the periodic table?', 'mcq', '["fluorine","chlorine","oxygen","iodine"]', 'fluorine', 'easy', 2, 'both', 'Fluorine is the most electronegative element, with the strongest attraction for bonding electrons.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_035', 'Halogens are strong oxidising agents because they:', 'mcq', '["readily lose electrons","readily gain an electron to complete their octet","have low electron affinity","are metals"]', 'readily gain an electron to complete their octet', 'easy', 3, 'both', 'Needing just one electron for a noble-gas configuration, halogens accept electrons easily, making them strong oxidising agents.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_036', 'The oxidising power of the halogens decreases in the order:', 'mcq', '["I₂ > Br₂ > Cl₂ > F₂","F₂ > Cl₂ > Br₂ > I₂","Cl₂ > F₂ > Br₂ > I₂","Br₂ > Cl₂ > F₂ > I₂"]', 'F₂ > Cl₂ > Br₂ > I₂', 'medium', 4, 'both', 'Oxidising power decreases down the group as the tendency to gain an electron falls, so fluorine is the strongest oxidiser.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_037', 'The bond dissociation enthalpy of fluorine (F₂) is lower than that of chlorine (Cl₂) because of:', 'mcq', '["weak F–F bonding from lone-pair repulsion in the small F atom","strong metallic bonding","the larger size of fluorine","its high electronegativity only"]', 'weak F–F bonding from lone-pair repulsion in the small F atom', 'medium', 5, 'jee', 'The small size of fluorine causes strong repulsion between non-bonding lone pairs, weakening the F–F bond below the Cl–Cl bond.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_038', 'The acidic strength of the hydrogen halides increases in the order:', 'mcq', '["HF < HCl < HBr < HI","HI < HBr < HCl < HF","HCl < HF < HBr < HI","HF < HBr < HCl < HI"]', 'HF < HCl < HBr < HI', 'medium', 5, 'jee', 'As the H–X bond weakens down the group, the halide ion is released more easily, so acid strength increases from HF to HI.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_039', 'Bleaching action of chlorine in the presence of moisture is due to:', 'mcq', '["reduction","the formation of nascent oxygen (oxidation)","hydrogenation","precipitation"]', 'the formation of nascent oxygen (oxidation)', 'medium', 5, 'both', 'Chlorine reacts with water to give HOCl, which releases nascent oxygen that oxidises and bleaches the coloured matter.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_040', 'Among the halogens, fluorine shows only a -1 oxidation state (no positive states) because it:', 'mcq', '["is a gas","is the most electronegative and has no d-orbitals","has a large size","is a metal"]', 'is the most electronegative and has no d-orbitals', 'medium', 5, 'jee', 'Being the most electronegative element with no available d-orbitals, fluorine cannot exhibit positive oxidation states.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_041', 'Despite fluorine being the most electronegative element, it has a lower electron affinity than chlorine because of:', 'mcq', '["its larger size","strong electron-electron repulsion in the compact 2p subshell","weak nuclear charge","its metallic nature"]', 'strong electron-electron repulsion in the compact 2p subshell', 'hard', 7, 'jee', 'The small fluorine atom has a compact 2p subshell, so added electrons experience strong repulsion, lowering its electron affinity below chlorine''s.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_042', 'The shape of the interhalogen compound ICl₃ (which exists as the dimer I₂Cl₆) in its monomeric form is:', 'mcq', '["trigonal planar","T-shaped","trigonal pyramidal","tetrahedral"]', 'T-shaped', 'hard', 7, 'jee', 'In ICl₃ the central iodine has three bond pairs and two lone pairs (trigonal bipyramidal geometry), giving a T-shaped molecule.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_043', 'Hydrofluoric acid (HF) is a weak acid in water (unlike the other hydrohalic acids) mainly because of its:', 'mcq', '["low electronegativity","very high H–F bond strength","large molecular size","ionic character"]', 'very high H–F bond strength', 'hard', 6, 'jee', 'The strong, short H–F bond resists ionisation, so HF is only weakly acidic compared with HCl, HBr and HI.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_044', 'When chlorine is passed into cold dilute NaOH, the products are sodium chloride and:', 'mcq', '["sodium chlorate(V) (NaClO₃)","sodium hypochlorite (NaOCl)","sodium perchlorate","sodium chlorite"]', 'sodium hypochlorite (NaOCl)', 'hard', 6, 'jee', 'In cold dilute alkali chlorine disproportionates to chloride and hypochlorite (NaOCl), the basis of bleaching solution.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
('axai_ch10_045', 'The correct order of acidic strength of the oxoacids of chlorine is:', 'mcq', '["HClO > HClO₂ > HClO₃ > HClO₄","HClO₄ > HClO₃ > HClO₂ > HClO","HClO₂ > HClO > HClO₄ > HClO₃","HClO₃ > HClO₄ > HClO > HClO₂"]', 'HClO₄ > HClO₃ > HClO₂ > HClO', 'hard', 8, 'jee', 'As the oxidation state of chlorine and the number of oxygen atoms increase, the conjugate base is more stabilised, so HClO₄ is the strongest acid.', 'chem', 'ch10', 'ch10t2', 'ch10t2s1'),
-- ===== ch10t2s2 Group 18: Noble Gases =====
('axai_ch10_046', 'The general valence-shell electronic configuration of the noble gases (except He) is:', 'mcq', '["ns²np⁵","ns²np⁶","ns²np⁴","ns¹"]', 'ns²np⁶', 'easy', 1, 'both', 'Noble gases (other than helium) have a completely filled octet with the configuration ns²np⁶.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_047', 'Which noble gas is used to fill electric light bulbs?', 'mcq', '["helium","neon","argon","xenon"]', 'argon', 'easy', 1, 'both', 'Argon is an inert, inexpensive gas used to fill light bulbs and prevent oxidation of the filament.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_048', 'The noble gases are chemically inert mainly because they have:', 'mcq', '["completely filled valence shells","unpaired electrons","large atomic radii","high electron affinity"]', 'completely filled valence shells', 'easy', 2, 'both', 'Their stable, completely filled valence shells give noble gases very high ionisation energies and almost no tendency to react.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_049', 'Which noble gas is used in weather balloons and airships because it is light and non-flammable?', 'mcq', '["helium","argon","krypton","radon"]', 'helium', 'easy', 2, 'both', 'Helium is the second lightest gas and is non-flammable, making it ideal for balloons and airships.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_050', 'Which noble gas is radioactive?', 'mcq', '["neon","argon","krypton","radon"]', 'radon', 'easy', 3, 'both', 'Radon is a radioactive noble gas produced by the decay of radium.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_051', 'The first noble gas compound to be prepared was:', 'mcq', '["XePtF₆","XeF₂","XeO₃","KrF₂"]', 'XePtF₆', 'medium', 4, 'jee', 'Neil Bartlett prepared the first noble gas compound, xenon hexafluoroplatinate (XePtF₆), in 1962.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_052', 'Only xenon (and to a lesser extent krypton) forms compounds among the noble gases because it has the:', 'mcq', '["smallest size and highest ionisation energy","largest size and lowest ionisation energy in its reactive range","highest electronegativity","most unpaired electrons"]', 'largest size and lowest ionisation energy in its reactive range', 'medium', 5, 'jee', 'Xenon''s relatively low ionisation energy (large size) lets it lose/share electrons with very electronegative atoms like F and O.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_053', 'The shape of the xenon difluoride (XeF₂) molecule is:', 'mcq', '["bent","linear","trigonal planar","T-shaped"]', 'linear', 'medium', 5, 'jee', 'XeF₂ has two bond pairs and three lone pairs (trigonal bipyramidal geometry); the lone pairs occupy equatorial sites, giving a linear molecule.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_054', 'Which noble gas is used in producing the bright red-orange glow of advertising (discharge) lamps?', 'mcq', '["helium","neon","argon","xenon"]', 'neon', 'medium', 4, 'both', 'Neon emits a characteristic bright red-orange light in discharge tubes, used widely in advertising signs.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_055', 'A mixture of which noble gas with oxygen is used by deep-sea divers in place of nitrogen?', 'mcq', '["helium","argon","krypton","radon"]', 'helium', 'medium', 5, 'both', 'Helium is far less soluble in blood than nitrogen, so a helium-oxygen mixture prevents decompression sickness in divers.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_056', 'The hybridisation of xenon in xenon tetrafluoride (XeF₄) is:', 'mcq', '["sp³","sp³d","sp³d²","sp³d³"]', 'sp³d²', 'hard', 6, 'jee', 'XeF₄ has four bond pairs and two lone pairs occupying six sp³d² hybrid orbitals (octahedral electron geometry, square planar shape).', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_057', 'On complete hydrolysis, xenon hexafluoride (XeF₆) gives:', 'mcq', '["XeO₃","XeOF₄","XeF₄","XeO₄"]', 'XeO₃', 'hard', 7, 'jee', 'Complete hydrolysis of XeF₆ produces explosive xenon trioxide (XeO₃) and hydrogen fluoride.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_058', 'The shape of the xenon trioxide (XeO₃) molecule is:', 'mcq', '["trigonal planar","trigonal pyramidal","T-shaped","square planar"]', 'trigonal pyramidal', 'hard', 7, 'jee', 'XeO₃ has three bond pairs and one lone pair on xenon, giving a trigonal pyramidal shape.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_059', 'The hybridisation of xenon in XeF₆ is:', 'mcq', '["sp³d","sp³d²","sp³d³","sp³"]', 'sp³d³', 'hard', 8, 'jee', 'XeF₆ has six bond pairs and one lone pair (seven electron domains), requiring sp³d³ hybridisation and a distorted octahedral shape.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2'),
('axai_ch10_060', 'Helium has a higher first ionisation energy than any other element because it has a:', 'mcq', '["large atomic size","completely filled, very compact 1s² shell","high atomic mass","single valence electron"]', 'completely filled, very compact 1s² shell', 'hard', 6, 'jee', 'Helium''s two electrons fill a small, tightly held 1s shell close to the nucleus, giving it the highest ionisation energy of all elements.', 'chem', 'ch10', 'ch10t2', 'ch10t2s2')
on conflict (id) do nothing;
