-- ch05t1 "Enthalpy, Hess's Law & Born-Haber Cycle" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch05t1s1 Enthalpy & Thermochemical Equations   (axai_ch05_001..015)
--   ch05t1s2 Hess's Law & Born–Haber Cycle           (axai_ch05_016..030)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch05t1s1', 'Enthalpy & Thermochemical Equations', 'ch05t1', 'ch05', 'chem', 1),
  ('ch05t1s2', 'Hess''s Law & Born–Haber Cycle', 'ch05t1', 'ch05', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch05t1s1 Enthalpy & Thermochemical Equations =====
('axai_ch05_001', 'At constant pressure, the heat exchanged by a system is equal to its:', 'mcq', '["change in enthalpy (ΔH)","change in volume","change in temperature","change in pressure"]', 'change in enthalpy (ΔH)', 'easy', 1, 'both', 'At constant pressure qₚ = ΔH, so the heat exchanged equals the enthalpy change.', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_002', 'For an exothermic reaction, the sign of ΔH is:', 'mcq', '["positive","negative","zero","undefined"]', 'negative', 'easy', 1, 'both', 'An exothermic reaction releases heat, so its enthalpy change is negative.', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_003', 'For an endothermic reaction, the sign of ΔH is:', 'mcq', '["positive","negative","zero","always one"]', 'positive', 'easy', 2, 'both', 'An endothermic reaction absorbs heat, so its enthalpy change is positive.', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_004', 'Enthalpy (H) is a:', 'mcq', '["path function","state function","kinetic quantity","non-thermodynamic quantity"]', 'state function', 'easy', 2, 'both', 'Enthalpy depends only on the state of the system, not on the path taken — it is a state function.', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_005', 'The standard enthalpy of formation of an element in its most stable form is:', 'mcq', '["zero","always positive","always negative","equal to its atomic mass"]', 'zero', 'easy', 2, 'both', 'By convention the standard enthalpy of formation of an element in its reference (standard) state is zero.', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_006', 'The enthalpy of combustion of a substance is always:', 'mcq', '["positive (endothermic)","negative (exothermic)","zero","undefined"]', 'negative (exothermic)', 'medium', 4, 'both', 'Combustion releases heat, so the enthalpy of combustion is always negative.', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_007', 'The relation between the enthalpy change and the internal energy change of a reaction is:', 'mcq', '["ΔH = ΔU + Δng RT","ΔH = ΔU − Δng RT","ΔH = ΔU × RT","ΔH = ΔU / RT"]', 'ΔH = ΔU + Δng RT', 'medium', 5, 'both', 'ΔH = ΔU + Δng RT, where Δng is the change in the number of moles of gas.', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_008', 'The standard enthalpy of formation of a compound is the enthalpy change when one mole of it forms from its elements in their:', 'mcq', '["gaseous states","standard (reference) states","ionic states","liquid states"]', 'standard (reference) states', 'medium', 4, 'both', 'Standard enthalpy of formation refers to forming one mole of compound from elements in their standard reference states.', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_009', 'According to the first law of thermodynamics, the change in internal energy is:', 'mcq', '["ΔU = q + w","ΔU = q − w","ΔU = q × w","ΔU = w − q"]', 'ΔU = q + w', 'medium', 5, 'both', 'The first law states ΔU = q + w (heat added to the system plus work done on it).', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_010', 'The enthalpy of neutralisation of a strong acid by a strong base is approximately:', 'mcq', '["−57.1 kJ mol⁻¹","+57.1 kJ mol⁻¹","−285 kJ mol⁻¹","0 kJ mol⁻¹"]', '−57.1 kJ mol⁻¹', 'medium', 5, 'both', 'It is the constant value −57.1 kJ mol⁻¹, corresponding to H⁺(aq) + OH⁻(aq) → H₂O(l).', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_011', 'For a reaction in which the number of moles of gas does not change (Δng = 0):', 'mcq', '["ΔH > ΔU","ΔH < ΔU","ΔH = ΔU","ΔH = 0"]', 'ΔH = ΔU', 'hard', 6, 'jee', 'Since ΔH = ΔU + Δng RT, when Δng = 0 the two are equal.', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_012', 'For the reaction N₂(g) + 3H₂(g) → 2NH₃(g) at constant temperature, ΔH is:', 'mcq', '["greater than ΔU","less than ΔU","equal to ΔU","equal to zero"]', 'less than ΔU', 'hard', 7, 'jee', 'Δng = 2 − 4 = −2, so ΔH = ΔU + (−2)RT, making ΔH less than ΔU.', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_013', 'In terms of bond enthalpies, the enthalpy change of a gas-phase reaction is:', 'mcq', '["bonds formed − bonds broken","bonds broken − bonds formed","bonds broken + bonds formed","bonds broken × bonds formed"]', 'bonds broken − bonds formed', 'hard', 6, 'jee', 'ΔH = Σ(bond enthalpies of bonds broken) − Σ(bond enthalpies of bonds formed).', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_014', 'When a gas expands against an external pressure, the work done on the system (w = −PΔV) is:', 'mcq', '["positive","negative","zero","equal to ΔH"]', 'negative', 'hard', 6, 'jee', 'On expansion ΔV > 0, so w = −PΔV is negative (work is done by the system).', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
('axai_ch05_015', 'For H₂(g) + Cl₂(g) → 2HCl(g), using bond enthalpies H–H = 436, Cl–Cl = 242 and H–Cl = 431 kJ mol⁻¹, ΔH is:', 'mcq', '["−184 kJ","+184 kJ","−247 kJ","−431 kJ"]', '−184 kJ', 'hard', 8, 'jee', 'ΔH = (436 + 242) − 2(431) = 678 − 862 = −184 kJ.', 'chem', 'ch05', 'ch05t1', 'ch05t1s1'),
-- ===== ch05t1s2 Hess's Law & Born–Haber Cycle =====
('axai_ch05_016', 'Hess''s law states that the total enthalpy change of a reaction is:', 'mcq', '["dependent on the path taken","independent of the path taken","always zero","equal to the activation energy"]', 'independent of the path taken', 'easy', 2, 'both', 'Hess''s law: the overall enthalpy change is the same whether the reaction occurs in one step or several.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_017', 'Hess''s law is a direct consequence of the fact that enthalpy is a:', 'mcq', '["path function","state function","kinetic quantity","rate constant"]', 'state function', 'easy', 2, 'both', 'Because enthalpy is a state function, the total change depends only on the initial and final states.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_018', 'The Born–Haber cycle is mainly used to determine the:', 'mcq', '["lattice enthalpy of an ionic solid","rate of a reaction","activation energy","boiling point"]', 'lattice enthalpy of an ionic solid', 'easy', 2, 'both', 'Lattice enthalpy cannot be measured directly, so the Born–Haber cycle is used to calculate it indirectly.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_019', 'The Born–Haber cycle is an application of:', 'mcq', '["Hess''s law","Raoult''s law","Le Chatelier''s principle","Hund''s rule"]', 'Hess''s law', 'easy', 3, 'both', 'The Born–Haber cycle applies Hess''s law to a series of enthalpy steps to obtain the lattice enthalpy.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_020', 'The enthalpy of sublimation is the enthalpy change when a substance converts from:', 'mcq', '["solid to gas","liquid to gas","solid to liquid","gas to liquid"]', 'solid to gas', 'easy', 2, 'both', 'Sublimation is the direct conversion of a solid to a gas.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_021', 'The ionisation enthalpy of a gaseous atom is always:', 'mcq', '["negative (exothermic)","positive (endothermic)","zero","equal to the electron gain enthalpy"]', 'positive (endothermic)', 'medium', 4, 'both', 'Removing an electron from a gaseous atom requires energy, so ionisation enthalpy is positive.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_022', 'The electron gain enthalpy of chlorine is:', 'mcq', '["negative (exothermic)","positive (endothermic)","zero","equal to its ionisation enthalpy"]', 'negative (exothermic)', 'medium', 5, 'both', 'Chlorine releases energy when it gains an electron, so its electron gain enthalpy is negative.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_023', 'If A → B has ΔH₁ and B → C has ΔH₂, then by Hess''s law the enthalpy change for A → C is:', 'mcq', '["ΔH₁ − ΔH₂","ΔH₁ + ΔH₂","ΔH₁ × ΔH₂","ΔH₂ − ΔH₁"]', 'ΔH₁ + ΔH₂', 'medium', 5, 'both', 'Enthalpy changes of consecutive steps add: ΔH(A→C) = ΔH₁ + ΔH₂.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_024', 'In the Born–Haber cycle of NaCl, the lattice enthalpy (formation of the solid from gaseous ions) is:', 'mcq', '["exothermic","endothermic","zero","equal to the ionisation enthalpy"]', 'exothermic', 'medium', 5, 'both', 'Gaseous ions combining into a crystal lattice release energy, so the lattice (formation) enthalpy is exothermic.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_025', 'Which set of steps is combined in the Born–Haber cycle to obtain the enthalpy of formation of NaCl?', 'mcq', '["sublimation, ionisation, dissociation, electron gain and lattice enthalpy","only ionisation and electron gain","only the lattice enthalpy","only sublimation and dissociation"]', 'sublimation, ionisation, dissociation, electron gain and lattice enthalpy', 'medium', 6, 'jee', 'The cycle sums Na sublimation, Na ionisation, ½ Cl₂ dissociation, Cl electron gain and the lattice enthalpy.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_026', 'For CH₄(g) + 2O₂(g) → CO₂(g) + 2H₂O(l), using ΔHf = −393 (CO₂), −286 (H₂O) and −75 (CH₄) kJ mol⁻¹, ΔH is:', 'mcq', '["−890 kJ","−604 kJ","−1040 kJ","+890 kJ"]', '−890 kJ', 'hard', 7, 'jee', 'ΔH = [(−393) + 2(−286)] − (−75) = −965 + 75 = −890 kJ.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_027', 'In the Born–Haber cycle of NaCl, given ΔHf = −411, sublimation = +108, ionisation = +496, ½ dissociation = +121 and electron gain = −349 kJ mol⁻¹, the lattice enthalpy is:', 'mcq', '["−787 kJ mol⁻¹","−411 kJ mol⁻¹","+787 kJ mol⁻¹","−1163 kJ mol⁻¹"]', '−787 kJ mol⁻¹', 'hard', 8, 'jee', 'U = ΔHf − (108 + 496 + 121 − 349) = −411 − 376 = −787 kJ mol⁻¹.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_028', 'Given S(s) + O₂(g) → SO₂(g), ΔH = −297 kJ and SO₂(g) + ½O₂(g) → SO₃(g), ΔH = −98 kJ, the enthalpy change for S(s) + 3/2 O₂(g) → SO₃(g) is:', 'mcq', '["−395 kJ","−199 kJ","+395 kJ","−297 kJ"]', '−395 kJ', 'hard', 7, 'jee', 'By Hess''s law the two steps add: −297 + (−98) = −395 kJ.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_029', 'Given C(s) + O₂(g) → CO₂(g), ΔH = −393 kJ and CO(g) + ½O₂(g) → CO₂(g), ΔH = −283 kJ, the enthalpy of formation of CO is:', 'mcq', '["−110 kJ","−676 kJ","+110 kJ","−283 kJ"]', '−110 kJ', 'hard', 7, 'jee', 'For C + ½O₂ → CO, ΔH = (−393) − (−283) = −110 kJ.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2'),
('axai_ch05_030', 'Which step in the Born–Haber cycle of NaCl is exothermic?', 'mcq', '["sublimation of sodium","ionisation of sodium","dissociation of chlorine","electron gain by chlorine"]', 'electron gain by chlorine', 'hard', 6, 'jee', 'Chlorine releases energy on gaining an electron, so this step is exothermic; the other listed steps are endothermic.', 'chem', 'ch05', 'ch05t1', 'ch05t1s2')
on conflict (id) do nothing;
