-- ch06t3 "Solubility Product & Salt Hydrolysis" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch06t3s1 Solubility Product (Ksp)         (axai_ch06_061..075)
--   ch06t3s2 Salt Hydrolysis & pH of Salts    (axai_ch06_076..090)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch06t3s1', 'Solubility Product (Ksp)', 'ch06t3', 'ch06', 'chem', 1),
  ('ch06t3s2', 'Salt Hydrolysis & pH of Salts', 'ch06t3', 'ch06', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch06t3s1 Solubility Product (Ksp) =====
('axai_ch06_061', 'The solubility product (Ksp) concept is applied to:', 'mcq', '["highly soluble salts","sparingly soluble salts","all gases","pure water only"]', 'sparingly soluble salts', 'easy', 2, 'both', 'Ksp describes the equilibrium between a sparingly soluble salt and its ions in a saturated solution.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_062', 'For AgCl ⇌ Ag⁺ + Cl⁻, the solubility-product expression is:', 'mcq', '["[Ag⁺][Cl⁻]","[Ag⁺]/[Cl⁻]","[AgCl]","[Ag⁺]+[Cl⁻]"]', '[Ag⁺][Cl⁻]', 'easy', 2, 'both', 'Ksp = [Ag⁺][Cl⁻] for the dissolution of AgCl.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_063', 'A precipitate forms when the ionic product exceeds the:', 'mcq', '["Kw","Ka","Ksp","Kb"]', 'Ksp', 'easy', 3, 'both', 'When the ionic product is greater than Ksp, the solution is supersaturated and a precipitate forms.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_064', 'For a 1:1 salt AB with molar solubility s, Ksp equals:', 'mcq', '["s","s²","2s","s³"]', 's²', 'easy', 3, 'both', 'AB → A⁺ + B⁻ gives [A⁺] = [B⁻] = s, so Ksp = s².', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_065', 'A very small value of Ksp indicates that the salt is:', 'mcq', '["very soluble","sparingly soluble","a strong acid","a gas"]', 'sparingly soluble', 'easy', 2, 'both', 'The smaller the Ksp, the lower the solubility of the salt.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_066', 'For a salt of type AB₂ with molar solubility s, Ksp is:', 'mcq', '["s²","2s²","4s³","s³"]', '4s³', 'medium', 5, 'both', 'AB₂ → A²⁺ + 2B⁻ gives [A²⁺] = s and [B⁻] = 2s, so Ksp = s(2s)² = 4s³.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_067', 'The molar solubility of AgCl (Ksp = 1×10⁻¹⁰) in water is:', 'mcq', '["1×10⁻⁵ M","1×10⁻¹⁰ M","1×10⁻⁸ M","1 M"]', '1×10⁻⁵ M', 'medium', 5, 'both', 'For AB salt, s = √Ksp = √(10⁻¹⁰) = 10⁻⁵ M.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_068', 'For BaSO₄ (Ksp = 1×10⁻¹⁰), the concentration of Ba²⁺ in a saturated solution is:', 'mcq', '["1×10⁻⁵ M","1×10⁻¹⁰ M","2×10⁻⁵ M","1×10⁻⁷ M"]', '1×10⁻⁵ M', 'medium', 5, 'both', 'For the 1:1 salt, [Ba²⁺] = s = √Ksp = 10⁻⁵ M.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_069', 'The solubility of a sparingly soluble salt decreases in the presence of a common ion due to:', 'mcq', '["the common-ion effect","increased temperature","hydrolysis","complex formation"]', 'the common-ion effect', 'medium', 4, 'both', 'A common ion shifts the dissolution equilibrium backward (Le Chatelier), lowering solubility.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_070', 'For Ag₂CrO₄ ⇌ 2Ag⁺ + CrO₄²⁻ with molar solubility s, Ksp equals:', 'mcq', '["s²","2s³","4s³","s³"]', '4s³', 'medium', 6, 'both', '[Ag⁺] = 2s and [CrO₄²⁻] = s, so Ksp = (2s)²·s = 4s³.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_071', 'The molar solubility of CaF₂ (Ksp = 3.2×10⁻¹¹) is (Ksp = 4s³):', 'mcq', '["2×10⁻⁴ M","4×10⁻⁴ M","1×10⁻⁴ M","8×10⁻¹² M"]', '2×10⁻⁴ M', 'hard', 7, 'jee', '4s³ = 3.2×10⁻¹¹ → s³ = 8×10⁻¹² → s = 2×10⁻⁴ M.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_072', 'The solubility of AgCl (Ksp = 1×10⁻¹⁰) in 0.1 M NaCl is:', 'mcq', '["1×10⁻⁵ M","1×10⁻⁹ M","1×10⁻¹⁰ M","0.1 M"]', '1×10⁻⁹ M', 'hard', 7, 'jee', 's = Ksp/[Cl⁻] = 10⁻¹⁰ / 0.1 = 10⁻⁹ M (common-ion effect).', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_073', 'A 1:1 salt MX has Ksp = 4×10⁻¹². Its molar solubility is:', 'mcq', '["2×10⁻⁶ M","4×10⁻⁶ M","2×10⁻¹² M","1×10⁻⁶ M"]', '2×10⁻⁶ M', 'hard', 6, 'jee', 's = √Ksp = √(4×10⁻¹²) = 2×10⁻⁶ M.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_074', 'Equal volumes of 2×10⁻³ M Ba²⁺ and 2×10⁻³ M SO₄²⁻ are mixed (Ksp of BaSO₄ = 1×10⁻¹⁰). The result is:', 'mcq', '["a precipitate forms","no precipitate","BaSO₄ dissolves","the pH rises"]', 'a precipitate forms', 'hard', 7, 'jee', 'After mixing each ion is 1×10⁻³ M; ionic product = 10⁻⁶ > Ksp, so BaSO₄ precipitates.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
('axai_ch06_075', 'For Ca₃(PO₄)₂ with molar solubility s, the solubility product Ksp equals:', 'mcq', '["108s⁵","4s³","27s⁴","s⁵"]', '108s⁵', 'hard', 8, 'jee', '[Ca²⁺] = 3s and [PO₄³⁻] = 2s, so Ksp = (3s)³(2s)² = 27s³·4s² = 108s⁵.', 'chem', 'ch06', 'ch06t3', 'ch06t3s1'),
-- ===== ch06t3s2 Salt Hydrolysis & pH of Salts =====
('axai_ch06_076', 'A salt of a strong acid and a strong base (e.g. NaCl) gives a solution that is:', 'mcq', '["acidic","basic","neutral","strongly acidic"]', 'neutral', 'easy', 2, 'both', 'Neither ion hydrolyses appreciably, so the solution is neutral.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_077', 'A salt of a weak acid and a strong base (e.g. CH₃COONa) gives a solution that is:', 'mcq', '["acidic","basic","neutral","colourless gas"]', 'basic', 'easy', 3, 'both', 'The anion of a weak acid hydrolyses to give OH⁻, making the solution basic.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_078', 'A salt of a strong acid and a weak base (e.g. NH₄Cl) gives a solution that is:', 'mcq', '["acidic","basic","neutral","amphoteric"]', 'acidic', 'easy', 3, 'both', 'The cation of a weak base hydrolyses to give H⁺, making the solution acidic.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_079', 'Salt hydrolysis is essentially the reaction of a salt''s ions with:', 'mcq', '["oxygen","water","a catalyst","another salt"]', 'water', 'easy', 2, 'both', 'Hydrolysis is the reaction of the salt''s ions with water to regenerate the parent acid or base.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_080', 'Which salt solution turns red litmus blue?', 'mcq', '["NH₄Cl","CH₃COONa","NaCl","Na₂SO₄"]', 'CH₃COONa', 'easy', 3, 'both', 'CH₃COONa is basic (weak acid + strong base), so it turns red litmus blue.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_081', 'An aqueous solution of NH₄Cl is acidic because:', 'mcq', '["the NH₄⁺ ion hydrolyses to give H⁺","the Cl⁻ ion hydrolyses","it does not dissolve","NaOH is formed"]', 'the NH₄⁺ ion hydrolyses to give H⁺', 'medium', 5, 'both', 'NH₄⁺ + H₂O ⇌ NH₄OH + H⁺, so the solution becomes acidic.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_082', 'In the hydrolysis of CH₃COONa, the ion that reacts with water is:', 'mcq', '["Na⁺","CH₃COO⁻","both ions","neither ion"]', 'CH₃COO⁻', 'medium', 5, 'both', 'The acetate ion (conjugate base of a weak acid) hydrolyses; Na⁺ does not.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_083', 'For a salt of a weak acid and strong base, the degree of hydrolysis increases on:', 'mcq', '["increasing concentration","dilution","adding the common ion","lowering temperature"]', 'dilution', 'medium', 6, 'both', 'Hydrolysis, like ionisation, is favoured by dilution, so the degree of hydrolysis increases.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_084', 'The aqueous solution of sodium carbonate (Na₂CO₃) has a pH that is:', 'mcq', '["less than 7","equal to 7","greater than 7","exactly 1"]', 'greater than 7', 'medium', 4, 'both', 'Na₂CO₃ is a salt of a weak acid and strong base, so its solution is basic (pH > 7).', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_085', 'For a salt of a weak acid and a weak base, the solution pH depends on:', 'mcq', '["only Ka","only Kb","the relative values of Ka and Kb","temperature only"]', 'the relative values of Ka and Kb', 'medium', 6, 'both', 'The pH is governed by whether Ka or Kb is larger, i.e. their relative strengths.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_086', 'For a salt of a weak acid (Ka) and a strong base, the hydrolysis constant Kh equals:', 'mcq', '["Kw/Ka","Kw/Kb","Ka/Kw","Ka·Kb"]', 'Kw/Ka', 'hard', 7, 'jee', 'For an anion of a weak acid, Kh = Kw/Ka.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_087', 'For a salt of a weak acid and a weak base, the hydrolysis constant Kh equals:', 'mcq', '["Kw/Ka","Kw/Kb","Kw/(Ka·Kb)","Ka·Kb/Kw"]', 'Kw/(Ka·Kb)', 'hard', 8, 'jee', 'Both ions hydrolyse, giving Kh = Kw/(Ka·Kb).', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_088', 'For 0.1 M CH₃COONa (Ka of CH₃COOH = 1.8×10⁻⁵), the pH is approximately:', 'mcq', '["5.1","7.0","8.9","11.0"]', '8.9', 'hard', 8, 'jee', 'Kh = Kw/Ka = 5.6×10⁻¹⁰; [OH⁻] = √(Kh·C) ≈ 7.5×10⁻⁶, giving pOH ≈ 5.1 and pH ≈ 8.9.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_089', 'For a salt of a weak base (Kb) and a strong acid, the hydrolysis constant Kh equals:', 'mcq', '["Kw/Kb","Kw/Ka","Kb/Kw","Kw·Kb"]', 'Kw/Kb', 'hard', 7, 'jee', 'For the cation of a weak base, Kh = Kw/Kb.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2'),
('axai_ch06_090', 'For a salt of a weak acid and a weak base in which Ka > Kb, the resulting solution is:', 'mcq', '["acidic","basic","neutral","always pH 7"]', 'acidic', 'hard', 7, 'jee', 'When Ka > Kb the cationic hydrolysis dominates, so the solution is acidic.', 'chem', 'ch06', 'ch06t3', 'ch06t3s2')
on conflict (id) do nothing;
