-- ch04t3 "Liquefaction & Van der Waals" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch04t3s1 Real Gases & Van der Waals Equation   (axai_ch04_061..075)
--   ch04t3s2 Critical Constants & Liquefaction      (axai_ch04_076..090)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch04t3s1', 'Real Gases & Van der Waals Equation', 'ch04t3', 'ch04', 'chem', 1),
  ('ch04t3s2', 'Critical Constants & Liquefaction', 'ch04t3', 'ch04', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch04t3s1 Real Gases & Van der Waals Equation =====
('axai_ch04_061', 'Real gases show the largest deviations from ideal behaviour at:', 'mcq', '["high temperature and low pressure","low temperature and high pressure","high temperature and high pressure","standard temperature and pressure"]', 'low temperature and high pressure', 'easy', 2, 'both', 'At low temperature and high pressure intermolecular forces and molecular volume become significant, causing large deviations.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_062', 'The van der Waals equation for one mole of a real gas is:', 'mcq', '["(P + a/V²)(V − b) = RT","PV = RT","(P − a/V²)(V + b) = RT","P(V − b) = RT"]', '(P + a/V²)(V − b) = RT', 'easy', 3, 'both', 'For one mole, (P + a/V²)(V − b) = RT, where a and b are the van der Waals constants.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_063', 'In the van der Waals equation, the constant a accounts for the:', 'mcq', '["volume of the molecules","intermolecular forces of attraction","mass of the molecules","temperature of the gas"]', 'intermolecular forces of attraction', 'easy', 2, 'both', 'The a/V² term corrects the pressure for intermolecular attractive forces.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_064', 'In the van der Waals equation, the constant b corrects for the:', 'mcq', '["intermolecular attraction","finite volume of the molecules","kinetic energy","temperature"]', 'finite volume of the molecules', 'easy', 2, 'both', 'The b term (excluded volume) corrects for the finite size of the gas molecules.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_065', 'The compressibility factor Z is defined as:', 'mcq', '["PV/nRT","nRT/PV","PV/RT²","P/nRT"]', 'PV/nRT', 'easy', 3, 'both', 'The compressibility factor is Z = PV/nRT; for an ideal gas Z = 1.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_066', 'For a real gas at very high pressure, the compressibility factor Z is:', 'mcq', '["greater than 1","less than 1","exactly 1","exactly 0"]', 'greater than 1', 'medium', 5, 'both', 'At very high pressure the repulsion arising from molecular volume dominates, making Z > 1.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_067', 'At low to moderate pressure, most real gases have a compressibility factor Z that is:', 'mcq', '["greater than 1","less than 1","exactly 1","negative"]', 'less than 1', 'medium', 5, 'both', 'At low to moderate pressure intermolecular attractions dominate, making the gas more compressible so Z < 1.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_068', 'A real gas behaves most like an ideal gas at:', 'mcq', '["low temperature and high pressure","high temperature and low pressure","low temperature and low pressure","high temperature and high pressure"]', 'high temperature and low pressure', 'medium', 4, 'both', 'At high temperature and low pressure the molecules are far apart and fast, so attractions and molecular volume are negligible.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_069', 'The SI-style units of the van der Waals constant a are:', 'mcq', '["L mol⁻¹","atm L² mol⁻²","atm mol⁻¹","L² mol⁻¹"]', 'atm L² mol⁻²', 'medium', 5, 'both', 'Since a/V² has units of pressure, a has units of atm L² mol⁻².', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_070', 'The units of the van der Waals constant b are:', 'mcq', '["L mol⁻¹","atm L² mol⁻²","atm mol⁻¹","mol L⁻¹"]', 'L mol⁻¹', 'medium', 4, 'both', 'b is an excluded volume per mole, so its units are L mol⁻¹.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_071', 'A larger value of the van der Waals constant a for a gas indicates:', 'mcq', '["weaker intermolecular forces","stronger intermolecular forces","larger molecular volume","ideal behaviour"]', 'stronger intermolecular forces', 'hard', 6, 'jee', 'A larger a reflects stronger intermolecular attractions, so the gas is also more easily liquefied.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_072', 'For hydrogen and helium, the compressibility factor Z is greater than 1 at all pressures because they have:', 'mcq', '["very large a values","very small a values","no molecular volume","very high critical temperatures"]', 'very small a values', 'hard', 7, 'jee', 'H₂ and He have negligible attractive forces (very small a), so the molecular-volume term dominates and Z > 1 throughout.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_073', 'The Boyle temperature of a gas is the temperature at which the gas:', 'mcq', '["always condenses","obeys ideal gas behaviour over an appreciable pressure range","has zero volume","cannot be compressed"]', 'obeys ideal gas behaviour over an appreciable pressure range', 'hard', 7, 'jee', 'At the Boyle temperature the attractive and repulsive effects cancel, so the gas behaves nearly ideally over a range of pressures.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_074', 'At its Boyle temperature, the compressibility factor of a real gas at low pressure is:', 'mcq', '["greater than 1","approximately 1","less than 1","zero"]', 'approximately 1', 'hard', 6, 'jee', 'At the Boyle temperature Z ≈ 1 over an appreciable low-pressure range, so the gas obeys Boyle''s law.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
('axai_ch04_075', 'In the van der Waals equation the pressure correction term a/V² is added to the measured pressure because intermolecular attractions make the observed pressure:', 'mcq', '["higher than ideal","lower than ideal","equal to ideal","zero"]', 'lower than ideal', 'hard', 7, 'jee', 'Attractions pull molecules inward, reducing the impact on the walls; the measured pressure is lower than ideal, so a/V² is added to correct it.', 'chem', 'ch04', 'ch04t3', 'ch04t3s1'),
-- ===== ch04t3s2 Critical Constants & Liquefaction =====
('axai_ch04_076', 'The critical temperature of a gas is the temperature above which the gas:', 'mcq', '["cannot be liquefied by pressure alone","always liquefies","has zero volume","becomes a solid"]', 'cannot be liquefied by pressure alone', 'easy', 2, 'both', 'Above the critical temperature no amount of pressure can liquefy the gas.', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_077', 'The critical temperature of a substance is usually denoted by the symbol:', 'mcq', '["Tb","Tc","Tf","Tm"]', 'Tc', 'easy', 2, 'both', 'The critical temperature is written Tc.', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_078', 'A gas can be liquefied by applying pressure only when its temperature is:', 'mcq', '["above its critical temperature","at or below its critical temperature","at absolute zero","above its boiling point"]', 'at or below its critical temperature', 'easy', 2, 'both', 'Liquefaction by pressure is possible only at or below the critical temperature.', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_079', 'The critical pressure of a gas is the pressure required to liquefy it at its:', 'mcq', '["boiling point","critical temperature","melting point","Boyle temperature"]', 'critical temperature', 'easy', 3, 'both', 'Critical pressure (Pc) is the minimum pressure needed to liquefy a gas at its critical temperature.', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_080', 'The volume occupied by one mole of a substance at its critical temperature and pressure is called the:', 'mcq', '["molar volume","critical volume","excluded volume","standard volume"]', 'critical volume', 'easy', 3, 'both', 'The critical volume (Vc) is the molar volume at the critical point.', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_081', 'A gas with a higher critical temperature is:', 'mcq', '["more difficult to liquefy","more easily liquefied","unable to be liquefied","an ideal gas"]', 'more easily liquefied', 'medium', 4, 'both', 'A higher critical temperature means stronger attractions, so the gas is more easily liquefied.', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_082', 'In terms of the van der Waals constants, the critical temperature is given by:', 'mcq', '["8a/27Rb","a/27b²","3b","27Rb/8a"]', '8a/27Rb', 'medium', 6, 'jee', 'The critical temperature is Tc = 8a/(27Rb).', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_083', 'In terms of the van der Waals constants, the critical pressure is given by:', 'mcq', '["a/27b²","8a/27Rb","3b","a/b"]', 'a/27b²', 'medium', 6, 'jee', 'The critical pressure is Pc = a/(27b²).', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_084', 'In terms of the van der Waals constant b, the critical volume is given by:', 'mcq', '["b","2b","3b","b/3"]', '3b', 'medium', 5, 'jee', 'The critical volume is Vc = 3b.', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_085', 'Helium and hydrogen are difficult to liquefy because they have:', 'mcq', '["very high critical temperatures","very low critical temperatures","very large molecules","strong intermolecular forces"]', 'very low critical temperatures', 'medium', 5, 'both', 'Their weak attractions give very low critical temperatures, so they must be cooled far below room temperature to liquefy.', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_086', 'At the critical point of a substance, the densities of the liquid and vapour phases become:', 'mcq', '["very different","equal","zero","infinite"]', 'equal', 'hard', 6, 'jee', 'At the critical point the liquid and vapour become indistinguishable and their densities are equal (the meniscus disappears).', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_087', 'When a compressed real gas is allowed to expand through a fine nozzle (below its inversion temperature), it usually:', 'mcq', '["warms up","cools down","stays at the same temperature","decomposes"]', 'cools down', 'hard', 6, 'jee', 'This Joule–Thomson expansion cools most real gases (below their inversion temperature) and is used in liquefaction.', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_088', 'Hydrogen and helium warm up on Joule–Thomson expansion at room temperature because their inversion temperature is:', 'mcq', '["above room temperature","below room temperature","equal to room temperature","infinite"]', 'below room temperature', 'hard', 7, 'jee', 'Above the inversion temperature a gas warms on expansion; for H₂ and He the inversion temperature lies below room temperature.', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_089', 'For two gases with comparable molecular size (similar b), the one with the larger van der Waals constant a has:', 'mcq', '["a lower critical temperature","a higher critical temperature","zero critical pressure","no critical point"]', 'a higher critical temperature', 'hard', 7, 'jee', 'Since Tc = 8a/27Rb, a larger a (for similar b) raises the critical temperature.', 'chem', 'ch04', 'ch04t3', 'ch04t3s2'),
('axai_ch04_090', 'In the Linde process, a gas is liquefied by compression followed by:', 'mcq', '["heating at constant volume","Joule–Thomson expansion","an increase in pressure","addition of a catalyst"]', 'Joule–Thomson expansion', 'hard', 7, 'jee', 'The Linde process compresses and pre-cools the gas, then lets it expand (Joule–Thomson) so it cools further and liquefies.', 'chem', 'ch04', 'ch04t3', 'ch04t3s2')
on conflict (id) do nothing;
