-- ch06t2 "Ionic Equilibrium, pH & Buffers" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch06t2s1 Acids, Bases & pH               (axai_ch06_031..045)
--   ch06t2s2 Buffers & Common-Ion Effect     (axai_ch06_046..060)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch06t2s1', 'Acids, Bases & pH', 'ch06t2', 'ch06', 'chem', 1),
  ('ch06t2s2', 'Buffers & Common-Ion Effect', 'ch06t2', 'ch06', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch06t2s1 Acids, Bases & pH =====
('axai_ch06_031', 'According to the Arrhenius concept, an acid is a substance that in water produces:', 'mcq', '["OH⁻ ions","H⁺ ions","electrons","Na⁺ ions"]', 'H⁺ ions', 'easy', 1, 'both', 'An Arrhenius acid increases the concentration of H⁺ (H₃O⁺) ions in aqueous solution.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_032', 'The pH of a solution is defined as:', 'mcq', '["log[H⁺]","−log[H⁺]","log[OH⁻]","−ln[H⁺]"]', '−log[H⁺]', 'easy', 2, 'both', 'pH = −log₁₀[H⁺], the negative logarithm of the hydrogen-ion concentration.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_033', 'At 25 °C, the ionic product of water Kw is:', 'mcq', '["1×10⁻⁷","1×10⁻¹⁴","1×10⁻¹","1×10⁻²¹"]', '1×10⁻¹⁴', 'easy', 2, 'both', 'At 25 °C, Kw = [H⁺][OH⁻] = 1×10⁻¹⁴.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_034', 'A solution with pH = 7 at 25 °C is:', 'mcq', '["acidic","basic","neutral","amphoteric"]', 'neutral', 'easy', 1, 'both', 'At 25 °C, pH 7 means [H⁺] = [OH⁻], so the solution is neutral.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_035', 'According to the Brønsted–Lowry concept, a base is a:', 'mcq', '["proton donor","proton acceptor","electron-pair donor","electron-pair acceptor"]', 'proton acceptor', 'easy', 3, 'both', 'A Brønsted–Lowry base is a species that accepts a proton (H⁺).', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_036', 'The pH of a 0.01 M HCl solution is:', 'mcq', '["1","2","12","7"]', '2', 'medium', 4, 'both', 'HCl is a strong acid, so [H⁺] = 0.01 M and pH = −log(10⁻²) = 2.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_037', 'The pOH of a 0.001 M NaOH solution at 25 °C is:', 'mcq', '["1","2","3","11"]', '3', 'medium', 4, 'both', 'NaOH is a strong base, so [OH⁻] = 10⁻³ M and pOH = 3.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_038', 'The pH of a 0.001 M NaOH solution at 25 °C is:', 'mcq', '["3","11","7","14"]', '11', 'medium', 5, 'both', 'pOH = 3, so pH = 14 − 3 = 11.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_039', 'A conjugate base is formed when an acid:', 'mcq', '["gains a proton","loses a proton","gains an electron","loses an electron"]', 'loses a proton', 'medium', 4, 'both', 'An acid donates (loses) a proton to give its conjugate base.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_040', 'For a weak acid HA, the acid dissociation constant Ka is given by:', 'mcq', '["[HA] / ([H⁺][A⁻])","[H⁺][A⁻] / [HA]","[H⁺][OH⁻]","[H⁺] + [A⁻]"]', '[H⁺][A⁻] / [HA]', 'medium', 5, 'both', 'For HA ⇌ H⁺ + A⁻, Ka = [H⁺][A⁻] / [HA].', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_041', 'The pH of a 0.1 M weak acid with Ka = 1×10⁻⁵ is approximately:', 'mcq', '["1","3","5","7"]', '3', 'hard', 6, 'jee', '[H⁺] = √(Ka·C) = √(10⁻⁵ × 0.1) = 10⁻³, so pH = 3.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_042', 'The degree of dissociation of a 0.1 M weak acid with Ka = 1×10⁻⁵ is about:', 'mcq', '["0.001","0.01","0.1","1.0"]', '0.01', 'hard', 7, 'jee', 'α = √(Ka/C) = √(10⁻⁵ / 0.1) = √(10⁻⁴) = 0.01.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_043', 'At 25 °C, the sum pH + pOH for any aqueous solution equals:', 'mcq', '["7","10","14","1"]', '14', 'hard', 6, 'both', 'Since Kw = 10⁻¹⁴ at 25 °C, pH + pOH = 14.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_044', 'If [H⁺] of a solution is 2×10⁻⁴ M, its pH is approximately (log 2 = 0.3):', 'mcq', '["3.7","4.3","3.0","4.0"]', '3.7', 'hard', 7, 'jee', 'pH = −log(2×10⁻⁴) = 4 − log 2 = 4 − 0.3 = 3.7.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
('axai_ch06_045', 'When a strong acid solution (pH well below 7) is diluted ten-fold, its pH:', 'mcq', '["decreases by 1 unit","increases by 1 unit","stays the same","becomes 7"]', 'increases by 1 unit', 'hard', 6, 'jee', 'Ten-fold dilution reduces [H⁺] by a factor of 10, raising the pH by one unit.', 'chem', 'ch06', 'ch06t2', 'ch06t2s1'),
-- ===== ch06t2s2 Buffers & Common-Ion Effect =====
('axai_ch06_046', 'A buffer solution resists changes in:', 'mcq', '["temperature","pH","colour","volume"]', 'pH', 'easy', 1, 'both', 'A buffer resists changes in pH when small amounts of acid or base are added.', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_047', 'An acidic buffer is typically made from a weak acid and:', 'mcq', '["a strong acid","its salt with a strong base","a strong base","pure water"]', 'its salt with a strong base', 'easy', 3, 'both', 'An acidic buffer (e.g. acetic acid + sodium acetate) is a weak acid plus its salt with a strong base.', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_048', 'The Henderson–Hasselbalch equation for an acidic buffer is:', 'mcq', '["pH = pKa + log([salt]/[acid])","pH = pKa − log([salt]/[acid])","pH = pKa + log([acid]/[salt])","pH = pKw − pKa"]', 'pH = pKa + log([salt]/[acid])', 'easy', 3, 'both', 'For an acidic buffer, pH = pKa + log([salt]/[acid]).', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_049', 'The common-ion effect is the suppression of the dissociation of a weak electrolyte caused by adding:', 'mcq', '["water","an ion common to it","a catalyst","heat"]', 'an ion common to it', 'easy', 2, 'both', 'Adding an ion already present shifts the dissociation equilibrium back, lowering ionisation.', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_050', 'A common example of a basic buffer is:', 'mcq', '["CH₃COOH / CH₃COONa","NH₄OH / NH₄Cl","HCl / NaCl","H₂SO₄ / Na₂SO₄"]', 'NH₄OH / NH₄Cl', 'easy', 3, 'both', 'A basic buffer is a weak base with its salt, such as NH₄OH and NH₄Cl.', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_051', 'For an acidic buffer with equal concentrations of acid and salt, the pH equals:', 'mcq', '["pKa","pKa + 1","pKa − 1","7"]', 'pKa', 'medium', 4, 'both', 'When [salt] = [acid], log(1) = 0, so pH = pKa.', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_052', 'An acetic acid–sodium acetate buffer has pKa = 4.74 with [salt] = [acid]. Its pH is:', 'mcq', '["4.74","5.74","3.74","7.00"]', '4.74', 'medium', 4, 'both', 'With equal salt and acid, pH = pKa = 4.74.', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_053', 'Adding sodium acetate to acetic acid causes the dissociation of acetic acid to:', 'mcq', '["increase","decrease","remain unchanged","become complete"]', 'decrease', 'medium', 5, 'both', 'The common acetate ion suppresses the ionisation of acetic acid (common-ion effect).', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_054', 'For a basic buffer pOH = pKb + log([salt]/[base]). If [salt] = [base] and pKb = 4.74, the pOH is:', 'mcq', '["4.74","9.26","7.00","2.74"]', '4.74', 'medium', 5, 'both', 'With equal salt and base, log(1) = 0, so pOH = pKb = 4.74.', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_055', 'The buffer capacity is maximum when the ratio [salt]/[acid] is:', 'mcq', '["10","1","0.1","100"]', '1', 'medium', 6, 'both', 'Buffer capacity is greatest when [salt] = [acid], i.e. the ratio equals 1 (pH = pKa).', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_056', 'A buffer of 0.2 M CH₃COOH and 0.2 M CH₃COONa (pKa = 4.74) is diluted with a little water. Its pH:', 'mcq', '["stays at 4.74","rises to 5.74","falls to 3.74","becomes 7.00"]', 'stays at 4.74', 'hard', 6, 'jee', 'Dilution changes acid and salt equally, leaving their ratio (and pH = 4.74) unchanged.', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_057', 'A buffer has 0.1 M acid and 1.0 M salt with pKa = 4.74. Its pH is:', 'mcq', '["3.74","4.74","5.74","6.74"]', '5.74', 'hard', 7, 'jee', 'pH = pKa + log([salt]/[acid]) = 4.74 + log(10) = 4.74 + 1 = 5.74.', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_058', 'The solubility of AgCl in water decreases when NaCl is added mainly due to the:', 'mcq', '["common-ion effect","rise in temperature","complex formation","hydrolysis of Ag⁺"]', 'common-ion effect', 'hard', 6, 'jee', 'Added Cl⁻ (common ion) shifts the dissolution equilibrium back, lowering AgCl solubility.', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_059', 'A buffer of NH₄OH and NH₄Cl has pKb = 4.74 and [salt]/[base] = 10. Its pH is:', 'mcq', '["5.74","8.26","9.26","4.74"]', '8.26', 'hard', 8, 'jee', 'pOH = pKb + log(10) = 5.74, so pH = 14 − 5.74 = 8.26.', 'chem', 'ch06', 'ch06t2', 'ch06t2s2'),
('axai_ch06_060', 'The major buffer system that maintains the pH of human blood near 7.4 is the:', 'mcq', '["acetate buffer","carbonic acid–bicarbonate buffer","ammonia buffer","sodium chloride buffer"]', 'carbonic acid–bicarbonate buffer', 'hard', 6, 'neet', 'Blood pH is largely controlled by the H₂CO₃/HCO₃⁻ (carbonic acid–bicarbonate) buffer system.', 'chem', 'ch06', 'ch06t2', 'ch06t2s2')
on conflict (id) do nothing;
