-- ch03t1 "Ionic & Covalent Bonding" — two subtopics + 60 questions.
--   ch03t1s1 Ionic Bonding & Lattice Energy        (axai_ch03_001..030)
--   ch03t1s2 Covalent Bonding & Lewis Structures   (axai_ch03_031..060)
-- Topic ch03t1 already exists. Additive / idempotent. status defaults to active.

insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch03t1s1', 'Ionic Bonding & Lattice Energy', 'ch03t1', 'ch03', 'chem', 1),
  ('ch03t1s2', 'Covalent Bonding & Lewis Structures', 'ch03t1', 'ch03', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch03t1s1 Ionic Bonding & Lattice Energy =====
('axai_ch03_001', 'The chemical bond formed by the complete transfer of one or more electrons from one atom to another is called a(n):', 'mcq', '["covalent bond","ionic bond","metallic bond","hydrogen bond"]', 'ionic bond', 'easy', 1, 'both', 'Complete transfer of electrons gives oppositely charged ions held together by electrostatic attraction — an ionic (electrovalent) bond.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_002', 'Which of the following is the most typical ionic compound?', 'mcq', '["CCl₄","NaCl","CH₄","I₂"]', 'NaCl', 'easy', 1, 'both', 'NaCl forms by transfer of an electron from Na to Cl; the others are covalent.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_003', 'An ionic bond is most likely to form between two elements with:', 'mcq', '["similar electronegativities","a large electronegativity difference","identical atoms","no valence electrons"]', 'a large electronegativity difference', 'easy', 2, 'both', 'A large electronegativity difference (roughly > 1.7) favours electron transfer and ionic bonding.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_004', 'Lattice enthalpy of an ionic solid is the energy:', 'mcq', '["released when gaseous ions form one mole of the solid","absorbed when a solid melts","released when a covalent bond breaks","needed to ionise a gaseous atom"]', 'released when gaseous ions form one mole of the solid', 'easy', 2, 'both', 'Lattice enthalpy (formation convention) is the energy released when gaseous ions combine to give one mole of the crystalline solid.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_005', 'The coordination number of Na⁺ in the rock-salt (NaCl) structure is:', 'mcq', '["4","6","8","12"]', '6', 'easy', 2, 'both', 'In the NaCl lattice each Na⁺ is octahedrally surrounded by 6 Cl⁻ ions.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_006', 'In the solid state, ionic compounds are:', 'mcq', '["good conductors of electricity","poor conductors of electricity","liquids at room temperature","gases at room temperature"]', 'poor conductors of electricity', 'easy', 2, 'both', 'In the solid the ions are locked in the lattice; ionic compounds conduct only when molten or dissolved.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_007', 'Which property is characteristic of most ionic compounds?', 'mcq', '["low melting point","high melting point","insolubility in all solvents","softness and volatility"]', 'high melting point', 'easy', 1, 'both', 'Strong electrostatic forces in the lattice give ionic compounds high melting and boiling points.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_008', 'Formation of an ionic bond is favoured by:', 'mcq', '["low ionisation energy of the metal and high electron affinity of the non-metal","high ionisation energy of both atoms","equal sharing of electron pairs","absence of valence electrons"]', 'low ionisation energy of the metal and high electron affinity of the non-metal', 'easy', 3, 'both', 'Easy electron loss (low ionisation energy) and easy electron gain (high electron affinity) favour ion formation.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_009', 'In the formation of CaCl₂, the calcium atom:', 'mcq', '["gains 2 electrons","loses 2 electrons","shares 2 electrons","loses 1 electron"]', 'loses 2 electrons', 'easy', 2, 'both', 'Ca → Ca²⁺ + 2e⁻; each Cl gains one electron, giving CaCl₂.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_010', 'Which of the following ions has a noble-gas electron configuration?', 'mcq', '["Na⁺","Fe²⁺","Cu²⁺","Cr³⁺"]', 'Na⁺', 'easy', 3, 'both', 'Na⁺ (2,8) is isoelectronic with neon; the transition-metal ions do not have a noble-gas configuration.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_011', 'Using U ∝ (Z₊Z₋)/(r₊+r₋), the sodium halide with the highest lattice enthalpy is:', 'mcq', '["NaF","NaCl","NaBr","NaI"]', 'NaF', 'medium', 4, 'both', 'F⁻ is the smallest anion, giving the smallest interionic distance and the largest lattice enthalpy among the sodium halides.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_012', 'Which compound has the highest lattice enthalpy?', 'mcq', '["NaCl","KCl","MgO","CaO"]', 'MgO', 'medium', 5, 'both', 'In MgO both ions are doubly charged and small (Mg²⁺, O²⁻), giving the greatest lattice enthalpy of the set.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_013', 'According to Fajans'' rules, covalent character in an ionic bond increases when the cation is:', 'mcq', '["large and singly charged","small and highly charged","large and uncharged","absent"]', 'small and highly charged', 'medium', 4, 'both', 'A small, highly charged cation has high polarising power, distorting the anion and increasing covalent character.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_014', 'Which of the following has the greatest covalent character?', 'mcq', '["NaCl","MgCl₂","AlCl₃","CsCl"]', 'AlCl₃', 'medium', 5, 'both', 'Al³⁺ is small and highly charged (high polarising power), so AlCl₃ is the most covalent by Fajans'' rules.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_015', 'The correct order of lattice enthalpy among the lithium halides is:', 'mcq', '["LiF > LiCl > LiBr > LiI","LiI > LiBr > LiCl > LiF","LiCl > LiF > LiBr > LiI","LiBr > LiF > LiCl > LiI"]', 'LiF > LiCl > LiBr > LiI', 'medium', 5, 'both', 'As the anion grows (F⁻ → I⁻) the interionic distance increases and lattice enthalpy falls.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_016', 'The Born–Haber cycle determines lattice enthalpy indirectly by applying:', 'mcq', '["Hess''s law","Raoult''s law","Hund''s rule","Le Chatelier''s principle"]', 'Hess''s law', 'medium', 4, 'both', 'Because enthalpy is a state function, the Born–Haber cycle uses Hess''s law to obtain lattice enthalpy from other measurable enthalpies.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_017', 'For the alkali-metal chlorides, the lattice enthalpy order is:', 'mcq', '["LiCl > NaCl > KCl > RbCl","RbCl > KCl > NaCl > LiCl","NaCl > LiCl > KCl > RbCl","KCl > NaCl > LiCl > RbCl"]', 'LiCl > NaCl > KCl > RbCl', 'medium', 5, 'both', 'A smaller cation (Li⁺) gives a smaller interionic distance and a larger lattice enthalpy.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_018', 'Which cation has the greatest polarising power?', 'mcq', '["K⁺","Na⁺","Mg²⁺","Al³⁺"]', 'Al³⁺', 'medium', 5, 'both', 'Polarising power rises with charge and falls with size; Al³⁺ is small and triply charged.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_019', 'Anion polarisability (and hence covalent character) is greatest for:', 'mcq', '["F⁻","Cl⁻","Br⁻","I⁻"]', 'I⁻', 'medium', 4, 'both', 'The large, diffuse I⁻ ion is the most polarisable, giving the most covalent character.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_020', 'CuCl is more covalent than NaCl, although Cu⁺ and Na⁺ carry the same charge, because Cu⁺ has:', 'mcq', '["a smaller nuclear charge","an 18-electron (pseudo-noble-gas) outer shell","a much larger ionic radius","a complete noble-gas configuration"]', 'an 18-electron (pseudo-noble-gas) outer shell', 'medium', 6, 'jee', 'The 18-electron outer shell of Cu⁺ shields the nucleus poorly, giving it greater polarising power than Na⁺.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_021', 'Arrange the sodium halides in increasing order of lattice enthalpy:', 'mcq', '["NaI < NaBr < NaCl < NaF","NaF < NaCl < NaBr < NaI","NaCl < NaF < NaBr < NaI","NaBr < NaI < NaCl < NaF"]', 'NaI < NaBr < NaCl < NaF', 'hard', 6, 'jee', 'Lattice enthalpy increases as anion size decreases, so NaF is highest and NaI lowest.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_022', 'The lattice enthalpy of MgO is several times that of NaF chiefly because MgO:', 'mcq', '["has doubly charged ions that are also smaller","is purely covalent","contains a larger cation","has a much lower melting point"]', 'has doubly charged ions that are also smaller', 'hard', 6, 'jee', 'U ∝ Z₊Z₋; the (2)(2) charge product plus the small ionic radii make MgO''s lattice enthalpy far larger than NaF''s.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_023', 'Among BeCl₂, MgCl₂, CaCl₂ and BaCl₂, the most covalent is:', 'mcq', '["BeCl₂","MgCl₂","CaCl₂","BaCl₂"]', 'BeCl₂', 'hard', 6, 'jee', 'Be²⁺ is the smallest, most polarising cation in the group, so BeCl₂ is the most covalent.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_024', 'A white solid melts at 801 °C, gives a conducting solution in water, but does not conduct as a solid. Its bonding is:', 'mcq', '["covalent","ionic","metallic","hydrogen bonding"]', 'ionic', 'hard', 6, 'both', 'A high melting point together with conductivity only when molten or dissolved are hallmarks of an ionic solid.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_025', 'For an isoelectronic series of ions, the ionic radius:', 'mcq', '["increases with increasing nuclear charge","decreases with increasing nuclear charge","is independent of nuclear charge","is largest for the most positive ion"]', 'decreases with increasing nuclear charge', 'hard', 7, 'jee', 'With the same number of electrons, a higher nuclear charge pulls them in more tightly, so the radius shrinks (N³⁻ > O²⁻ > F⁻ > Na⁺ > Mg²⁺).', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_026', 'Among the isoelectronic ions N³⁻, O²⁻, F⁻ and Na⁺, the smallest is:', 'mcq', '["N³⁻","O²⁻","F⁻","Na⁺"]', 'Na⁺', 'hard', 7, 'jee', 'All have 10 electrons; Na⁺ has the highest nuclear charge (Z = 11), so it is the smallest.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_027', 'LiF is much less soluble in water than LiCl mainly because LiF has a:', 'mcq', '["very high lattice enthalpy","very low lattice enthalpy","covalent network structure","very large anion"]', 'very high lattice enthalpy', 'hard', 7, 'jee', 'The very high lattice enthalpy of LiF (two small ions) outweighs its hydration enthalpy, lowering solubility relative to LiCl.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_028', 'In expressions for lattice enthalpy, the quantity that most strongly raises its magnitude is:', 'mcq', '["the product of the ionic charges","the colour of the ions","the molar mass of the salt","the boiling point of the metal"]', 'the product of the ionic charges', 'hard', 7, 'jee', 'U ∝ Z₊Z₋/(r₊+r₋); doubling the charges multiplies the charge product and dominates the lattice enthalpy.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_029', 'Which oxide has the highest lattice enthalpy?', 'mcq', '["Na₂O","MgO","K₂O","Rb₂O"]', 'MgO', 'hard', 7, 'jee', 'MgO has small, doubly charged ions, giving the greatest charge density and lattice enthalpy of the set.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
('axai_ch03_030', 'The melting points of NaF, NaCl, NaBr and NaI decrease in that order. This trend is explained by:', 'mcq', '["increasing anion size lowering lattice enthalpy","increasing covalent character only","decreasing molar mass","increasing cation charge"]', 'increasing anion size lowering lattice enthalpy', 'hard', 8, 'jee', 'Larger anions increase the interionic distance, lowering lattice enthalpy and hence the melting point from NaF to NaI.', 'chem', 'ch03', 'ch03t1', 'ch03t1s1'),
-- ===== ch03t1s2 Covalent Bonding & Lewis Structures =====
('axai_ch03_031', 'A covalent bond is formed by:', 'mcq', '["transfer of electrons","sharing of electron pairs","loss of electrons only","gain of electrons only"]', 'sharing of electron pairs', 'easy', 1, 'both', 'A covalent bond results from the mutual sharing of one or more electron pairs between atoms.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_032', 'The number of shared electron pairs in a nitrogen molecule (N₂) is:', 'mcq', '["1","2","3","4"]', '3', 'easy', 2, 'both', 'N≡N contains a triple bond, i.e. three shared electron pairs.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_033', 'A double bond consists of how many shared electrons?', 'mcq', '["two","four","six","one"]', 'four', 'easy', 2, 'both', 'A double bond is two shared pairs, i.e. four electrons.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_034', 'In a coordinate (dative) bond, the shared electron pair is provided by:', 'mcq', '["both atoms equally","only one of the two atoms","the nucleus","a free electron in space"]', 'only one of the two atoms', 'easy', 2, 'both', 'In a coordinate bond both shared electrons come from a single atom (the donor).', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_035', 'Which species contains a coordinate (dative) bond?', 'mcq', '["CH₄","NH₄⁺","H₂","Cl₂"]', 'NH₄⁺', 'easy', 3, 'both', 'In NH₄⁺ the lone pair on nitrogen forms a dative bond to H⁺.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_036', 'The total number of valence electrons used in the Lewis structure of CO₂ is:', 'mcq', '["12","14","16","18"]', '16', 'easy', 2, 'both', 'C contributes 4 and each O contributes 6: 4 + 2×6 = 16.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_037', 'How many lone pairs are present on the central oxygen atom of a water (H₂O) molecule?', 'mcq', '["0","1","2","3"]', '2', 'easy', 2, 'both', 'Oxygen in H₂O forms two bond pairs and retains two lone pairs.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_038', 'The octet rule is fully obeyed by the central atom in:', 'mcq', '["BF₃","PCl₅","CH₄","SF₆"]', 'CH₄', 'easy', 3, 'both', 'Carbon in CH₄ has exactly 8 electrons; BF₃ is electron-deficient while PCl₅ and SF₆ are hypervalent.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_039', 'Which molecule is an example of an incomplete octet on the central atom?', 'mcq', '["CH₄","BF₃","CO₂","NH₃"]', 'BF₃', 'easy', 3, 'both', 'Boron in BF₃ is surrounded by only 6 electrons — an incomplete octet.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_040', 'The number of bonding electron pairs in a methane (CH₄) molecule is:', 'mcq', '["2","3","4","5"]', '4', 'easy', 1, 'both', 'Methane has four C–H single bonds, i.e. four bonding pairs.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_041', 'The number of σ and π bonds in a carbon dioxide molecule (O=C=O) is:', 'mcq', '["2 σ and 2 π","4 σ and 0 π","2 σ and 1 π","1 σ and 3 π"]', '2 σ and 2 π', 'medium', 4, 'both', 'Each C=O bond is one σ + one π; two double bonds give 2 σ and 2 π.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_042', 'The number of σ and π bonds in ethyne (C₂H₂, H–C≡C–H) is:', 'mcq', '["3 σ and 2 π","2 σ and 3 π","5 σ and 0 π","3 σ and 1 π"]', '3 σ and 2 π', 'medium', 5, 'both', 'Two C–H σ bonds plus one C–C σ bond give 3 σ; the triple bond contributes 2 π bonds.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_043', 'Which species does NOT obey the octet rule?', 'mcq', '["NH₃","H₂O","NO","CO₂"]', 'NO', 'medium', 5, 'both', 'NO has 11 valence electrons — an odd-electron molecule that cannot satisfy the octet.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_044', 'The formal charge on nitrogen in the ammonium ion (NH₄⁺) is:', 'mcq', '["0","+1","−1","+2"]', '+1', 'medium', 5, 'both', 'FC = 5 − 0 − ½(8) = 5 − 4 = +1.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_045', 'In SF₆ the sulfur atom is surrounded by an expanded octet of:', 'mcq', '["8 electrons","10 electrons","12 electrons","14 electrons"]', '12 electrons', 'medium', 4, 'both', 'Six S–F bonds place 12 electrons around sulfur (expanded octet using d orbitals).', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_046', 'Which of the following has the maximum number of lone pairs on its central atom?', 'mcq', '["CH₄","NH₃","H₂O","CO₂"]', 'H₂O', 'medium', 4, 'both', 'Oxygen in H₂O has 2 lone pairs; N in NH₃ has 1; C in CH₄ and CO₂ has none.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_047', 'In the ozone molecule (O₃), the formal charge on the central oxygen atom is:', 'mcq', '["0","+1","−1","+2"]', '+1', 'medium', 6, 'jee', 'The central O has one lone pair, one single and one double bond: FC = 6 − 2 − ½(6) = +1.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_048', 'The total number of valence electrons used in the Lewis structure of the carbonate ion (CO₃²⁻) is:', 'mcq', '["20","22","24","26"]', '24', 'medium', 5, 'both', 'C (4) + 3 × O (18) + 2 (for the 2− charge) = 24.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_049', 'Which of the following is an odd-electron (free-radical) molecule?', 'mcq', '["CO₂","NO₂","SO₂","N₂O"]', 'NO₂', 'medium', 5, 'both', 'NO₂ has 17 valence electrons, an odd number, making it a free radical.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_050', 'The number of σ bonds in a benzene (C₆H₆) molecule is:', 'mcq', '["6","9","12","15"]', '12', 'medium', 5, 'both', '6 C–C σ bonds + 6 C–H σ bonds = 12 σ bonds; the remaining 3 π bonds are delocalised.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_051', 'The total number of σ and π bonds in benzene (C₆H₆) is:', 'mcq', '["12 σ and 3 π","6 σ and 6 π","12 σ and 6 π","9 σ and 3 π"]', '12 σ and 3 π', 'hard', 6, 'jee', '6 C–C + 6 C–H = 12 σ bonds; three π bonds delocalise over the ring.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_052', 'The formal charge on the carbon atom in carbon monoxide ( :C≡O: ) is:', 'mcq', '["0","−1","+1","−2"]', '−1', 'hard', 7, 'jee', 'For carbon: FC = 4 − 2 − ½(6) = 4 − 2 − 3 = −1 (oxygen carries +1).', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_053', 'Which molecule has an electron-deficient central atom and therefore acts as a Lewis acid?', 'mcq', '["NH₃","BF₃","H₂O","CH₄"]', 'BF₃', 'hard', 6, 'jee', 'Boron in BF₃ has only 6 electrons and readily accepts a lone pair, behaving as a Lewis acid.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_054', 'The number of σ and π bonds in hydrogen cyanide (H–C≡N) is:', 'mcq', '["2 σ and 2 π","2 σ and 1 π","3 σ and 2 π","1 σ and 2 π"]', '2 σ and 2 π', 'hard', 6, 'jee', 'One H–C σ and one C–N σ give 2 σ; the C≡N triple bond adds 2 π.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_055', 'The total number of lone pairs of electrons present in the XeF₂ molecule is:', 'mcq', '["6","7","8","9"]', '9', 'hard', 8, 'jee', 'Xe keeps 3 lone pairs and each F has 3 lone pairs (6 in total): 3 + 6 = 9.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_056', 'Which molecule has, on its central atom, a σ bond, a π bond, AND a lone pair?', 'mcq', '["SO₂","CH₄","BF₃","CO₂"]', 'SO₂', 'hard', 7, 'jee', 'In bent SO₂ the sulfur forms σ and π bonds to oxygen and still retains one lone pair; CO₂''s carbon has no lone pair.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_057', 'The number of electrons involved in bonding in a nitrogen molecule (N₂) is:', 'mcq', '["2","4","6","8"]', '6', 'hard', 6, 'both', 'The N≡N triple bond shares three pairs, i.e. 6 electrons.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_058', 'In the cyanide ion (CN⁻, :C≡N:⁻), the formal charge on carbon is:', 'mcq', '["0","−1","+1","−2"]', '−1', 'hard', 7, 'jee', 'For carbon: FC = 4 − 2 − ½(6) = −1, carrying the ion''s negative charge.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_059', 'PCl₅ exists but NCl₅ does not, mainly because nitrogen:', 'mcq', '["is less electronegative than phosphorus","has no available d-orbitals to expand its octet","is larger than phosphorus","forms only ionic chlorides"]', 'has no available d-orbitals to expand its octet', 'hard', 7, 'jee', 'Phosphorus can use 3d orbitals to expand its octet to 10 electrons; nitrogen (period 2) has no d orbitals and is limited to an octet.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2'),
('axai_ch03_060', 'How many of the following are hypervalent (expanded-octet) species: PCl₅, SF₆, XeF₄, BF₃?', 'mcq', '["1","2","3","4"]', '3', 'hard', 8, 'jee', 'PCl₅ (10 e), SF₆ (12 e) and XeF₄ (12 e) are hypervalent; BF₃ is electron-deficient, not hypervalent.', 'chem', 'ch03', 'ch03t1', 'ch03t1s2')
on conflict (id) do nothing;
