-- ch08t2 "Arrhenius Equation & Activation Energy" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch08t2s1 Arrhenius Equation & Temperature        (axai_ch08_031..045)
--   ch08t2s2 Activation Energy & Collision Theory     (axai_ch08_046..060)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch08t2s1', 'Arrhenius Equation & Temperature', 'ch08t2', 'ch08', 'chem', 1),
  ('ch08t2s2', 'Activation Energy & Collision Theory', 'ch08t2', 'ch08', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch08t2s1 Arrhenius Equation & Temperature =====
('axai_ch08_031', 'The Arrhenius equation is:', 'mcq', '["k = A e^(−Ea/RT)","k = A e^(Ea/RT)","k = A/Ea","k = Ea/RT"]', 'k = A e^(−Ea/RT)', 'easy', 2, 'both', 'The Arrhenius equation is k = A e^(−Ea/RT), relating rate constant to temperature.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_032', 'In the Arrhenius equation, the symbol A is called the:', 'mcq', '["activation energy","frequency (pre-exponential) factor","rate of reaction","temperature"]', 'frequency (pre-exponential) factor', 'easy', 3, 'both', 'A is the frequency or pre-exponential factor, related to collision frequency and orientation.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_033', 'For most reactions, increasing the temperature ____ the rate constant:', 'mcq', '["decreases","increases","does not change","makes it zero"]', 'increases', 'easy', 2, 'both', 'Higher temperature increases the rate constant (and hence the rate) for most reactions.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_034', 'In the Arrhenius equation, Ea represents the:', 'mcq', '["enthalpy of reaction","activation energy","equilibrium constant","entropy"]', 'activation energy', 'easy', 2, 'both', 'Ea is the activation energy, the minimum energy needed for a reaction to occur.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_035', 'A common rule of thumb is that reaction rate roughly doubles for every ____ rise in temperature:', 'mcq', '["1 °C","10 °C","100 °C","50 °C"]', '10 °C', 'easy', 3, 'both', 'For many reactions the rate approximately doubles for each 10 °C rise in temperature.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_036', 'Taking logarithms gives ln k = ln A − Ea/RT. A plot of ln k versus 1/T has a slope of:', 'mcq', '["−Ea/R","Ea/R","−R/Ea","ln A"]', '−Ea/R', 'medium', 5, 'both', 'The Arrhenius plot of ln k vs 1/T is linear with slope −Ea/R.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_037', 'A catalyst increases the rate of a reaction by:', 'mcq', '["increasing Ea","lowering the activation energy","raising the temperature","increasing ΔH"]', 'lowering the activation energy', 'medium', 4, 'both', 'A catalyst provides an alternative path with lower activation energy.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_038', 'In the Arrhenius plot of ln k versus 1/T, the intercept equals:', 'mcq', '["ln A","Ea/R","−Ea/R","A"]', 'ln A', 'medium', 5, 'both', 'The intercept of ln k vs 1/T is ln A.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_039', 'If Ea = 0, the Arrhenius equation predicts that the rate constant k equals:', 'mcq', '["zero","A","infinity","RT"]', 'A', 'medium', 6, 'both', 'With Ea = 0, e^(−Ea/RT) = 1, so k = A.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_040', 'A reaction with a large activation energy is ____ sensitive to temperature changes than one with a small Ea:', 'mcq', '["less","more","equally","not"]', 'more', 'medium', 6, 'both', 'The larger the Ea, the more strongly the rate constant rises with temperature.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_041', 'The two-temperature Arrhenius form is log(k₂/k₁) = (Ea/2.303R) × X. The factor X is:', 'mcq', '["(1/T₁ − 1/T₂)","(1/T₂ − 1/T₁)","(T₂ − T₁)","(T₁ − T₂)"]', '(1/T₁ − 1/T₂)', 'hard', 7, 'jee', 'log(k₂/k₁) = (Ea/2.303R)(1/T₁ − 1/T₂).', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_042', 'If the rate constant exactly doubles when temperature rises from T₁ to T₂, then log(k₂/k₁) equals:', 'mcq', '["0.301","0.693","1.0","2.0"]', '0.301', 'hard', 7, 'jee', 'log(k₂/k₁) = log 2 = 0.301.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_043', 'A catalyst speeds up a reaction by providing an alternative pathway with a:', 'mcq', '["higher activation energy","lower activation energy","larger ΔH","negative temperature"]', 'lower activation energy', 'hard', 6, 'both', 'The catalysed path has a lower activation energy, so more molecules can react.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_044', 'At the same temperature, the reaction with the smaller activation energy has the:', 'mcq', '["smaller rate constant","larger rate constant","same rate constant","zero rate"]', 'larger rate constant', 'hard', 7, 'jee', 'A smaller Ea gives a larger e^(−Ea/RT) term and hence a larger rate constant.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
('axai_ch08_045', 'As temperature approaches infinity, the factor e^(−Ea/RT) approaches:', 'mcq', '["0","1","Ea","infinity"]', '1', 'hard', 7, 'jee', 'As T → ∞, Ea/RT → 0, so e^(−Ea/RT) → 1 and k → A.', 'chem', 'ch08', 'ch08t2', 'ch08t2s1'),
-- ===== ch08t2s2 Activation Energy & Collision Theory =====
('axai_ch08_046', 'According to collision theory, a reaction occurs when molecules collide with sufficient energy and:', 'mcq', '["the right colour","proper orientation","high pressure only","a catalyst present"]', 'proper orientation', 'easy', 3, 'both', 'Effective collisions require both adequate energy and correct orientation.', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_047', 'The minimum energy that colliding molecules must possess to react is the:', 'mcq', '["kinetic energy","activation energy","potential energy","bond energy"]', 'activation energy', 'easy', 2, 'both', 'Activation energy is the threshold energy required for an effective collision.', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_048', 'On an energy profile, the activated complex (transition state) corresponds to the:', 'mcq', '["lowest point","highest point (energy maximum)","starting point","end point"]', 'highest point (energy maximum)', 'easy', 3, 'both', 'The activated complex sits at the energy maximum of the reaction coordinate.', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_049', 'A catalyst changes which of the following?', 'mcq', '["the activation energy","the enthalpy change ΔH","the equilibrium constant","the products formed"]', 'the activation energy', 'easy', 3, 'both', 'A catalyst lowers the activation energy but does not change ΔH or the products.', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_050', 'The collision frequency of gas molecules generally increases with:', 'mcq', '["lower temperature","higher temperature","lower concentration","added catalyst only"]', 'higher temperature', 'easy', 3, 'both', 'Higher temperature increases molecular speeds and hence the collision frequency.', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_051', 'For an exothermic reaction, the activation energy of the forward reaction is ____ that of the reverse reaction:', 'mcq', '["greater than","less than","equal to","double"]', 'less than', 'medium', 6, 'both', 'In an exothermic reaction, products lie lower in energy, so Ea(forward) < Ea(reverse).', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_052', 'The energy difference between the reactants and the activated complex is the:', 'mcq', '["enthalpy of reaction","activation energy","bond energy of products","entropy"]', 'activation energy', 'medium', 4, 'both', 'Activation energy is the energy gap between the reactants and the transition state.', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_053', 'In collision theory, the steric (probability) factor P accounts for the:', 'mcq', '["energy of collision","orientation of colliding molecules","temperature","catalyst"]', 'orientation of colliding molecules', 'medium', 5, 'both', 'The steric factor corrects for the fraction of collisions with the proper orientation.', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_054', 'For an endothermic reaction, the activation energy of the forward reaction is ____ that of the reverse reaction:', 'mcq', '["less than","greater than","equal to","zero"]', 'greater than', 'medium', 6, 'both', 'For an endothermic reaction the products are higher in energy, so Ea(forward) > Ea(reverse).', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_055', 'A catalyst does not change the ____ of a reaction:', 'mcq', '["rate","activation energy","enthalpy change (ΔH)","reaction pathway"]', 'enthalpy change (ΔH)', 'medium', 5, 'both', 'A catalyst alters the path and rate but leaves ΔH (a state function) unchanged.', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_056', 'For a reaction, Ea(forward) = 50 kJ and Ea(reverse) = 80 kJ. The enthalpy change ΔH is:', 'mcq', '["+30 kJ","−30 kJ","+130 kJ","−130 kJ"]', '−30 kJ', 'hard', 7, 'jee', 'ΔH = Ea(forward) − Ea(reverse) = 50 − 80 = −30 kJ.', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_057', 'A reaction with ΔH = −30 kJ is:', 'mcq', '["endothermic","exothermic","at equilibrium","zero-order"]', 'exothermic', 'hard', 6, 'jee', 'A negative ΔH means heat is released, so the reaction is exothermic.', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_058', 'Only a small fraction of molecular collisions lead to reaction mainly because most collisions:', 'mcq', '["have energy below Ea or wrong orientation","are too slow","occur at low pressure","involve a catalyst"]', 'have energy below Ea or wrong orientation', 'hard', 7, 'jee', 'Most colliding molecules lack the threshold energy or proper orientation, so they do not react.', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_059', 'For a reaction with Ea(forward) = 60 kJ and ΔH = +20 kJ, the activation energy of the reverse reaction is:', 'mcq', '["40 kJ","80 kJ","20 kJ","100 kJ"]', '40 kJ', 'hard', 8, 'jee', 'Ea(reverse) = Ea(forward) − ΔH = 60 − 20 = 40 kJ.', 'chem', 'ch08', 'ch08t2', 'ch08t2s2'),
('axai_ch08_060', 'According to collision theory, the rate constant is proportional to the fraction of molecules with energy ≥ Ea, given by:', 'mcq', '["e^(−Ea/RT)","e^(+Ea/RT)","Ea/RT","ln(Ea/RT)"]', 'e^(−Ea/RT)', 'hard', 7, 'jee', 'The Boltzmann fraction of molecules with energy ≥ Ea is e^(−Ea/RT).', 'chem', 'ch08', 'ch08t2', 'ch08t2s2')
on conflict (id) do nothing;
