-- ch07t1 "Oxidation States & Redox Balancing" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch07t1s1 Oxidation Number Rules         (axai_ch07_001..015)
--   ch07t1s2 Balancing Redox Reactions      (axai_ch07_016..030)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch07t1s1', 'Oxidation Number Rules', 'ch07t1', 'ch07', 'chem', 1),
  ('ch07t1s2', 'Balancing Redox Reactions', 'ch07t1', 'ch07', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch07t1s1 Oxidation Number Rules =====
('axai_ch07_001', 'The oxidation number of an element in its free (uncombined) state is:', 'mcq', '["+1","−1","0","+2"]', '0', 'easy', 1, 'both', 'A free element (e.g. O₂, Na, Fe) is assigned an oxidation number of zero.', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_002', 'The oxidation number of hydrogen in most of its compounds is:', 'mcq', '["−1","0","+1","+2"]', '+1', 'easy', 2, 'both', 'Hydrogen is usually +1 (except in metal hydrides, where it is −1).', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_003', 'The oxidation number of oxygen in most compounds is:', 'mcq', '["+2","−2","−1","0"]', '−2', 'easy', 2, 'both', 'Oxygen is normally −2 (exceptions include peroxides and OF₂).', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_004', 'Oxidation is best defined as the:', 'mcq', '["gain of electrons","loss of electrons","gain of protons","loss of neutrons"]', 'loss of electrons', 'easy', 1, 'both', 'Oxidation is the loss of electrons (and an increase in oxidation number).', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_005', 'The oxidation number of a monatomic ion equals:', 'mcq', '["zero","its charge","always +1","its mass number"]', 'its charge', 'easy', 2, 'both', 'For a monatomic ion, the oxidation number equals the ionic charge (e.g. Na⁺ is +1).', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_006', 'The oxidation number of sulphur in H₂SO₄ is:', 'mcq', '["+2","+4","+6","−2"]', '+6', 'medium', 4, 'both', '2(+1) + S + 4(−2) = 0 gives S = +6.', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_007', 'The oxidation number of manganese in KMnO₄ is:', 'mcq', '["+2","+4","+6","+7"]', '+7', 'medium', 5, 'both', '(+1) + Mn + 4(−2) = 0 gives Mn = +7.', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_008', 'The oxidation number of chromium in K₂Cr₂O₇ is:', 'mcq', '["+3","+6","+7","+2"]', '+6', 'medium', 5, 'both', '2(+1) + 2Cr + 7(−2) = 0 gives 2Cr = +12, so Cr = +6.', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_009', 'The oxidation number of hydrogen in a metal hydride such as NaH is:', 'mcq', '["+1","−1","0","+2"]', '−1', 'medium', 4, 'both', 'In ionic hydrides hydrogen is more electronegative than the metal, so it is −1.', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_010', 'The oxidation number of oxygen in hydrogen peroxide (H₂O₂) is:', 'mcq', '["−2","−1","0","+1"]', '−1', 'medium', 5, 'both', 'In peroxides the O–O bond gives each oxygen an oxidation number of −1.', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_011', 'The average oxidation number of sulphur in the thiosulphate ion S₂O₃²⁻ is:', 'mcq', '["+2","+4","+6","−2"]', '+2', 'hard', 7, 'jee', '2S + 3(−2) = −2 gives 2S = +4, so the average oxidation number of S is +2.', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_012', 'The oxidation number of carbon in glucose (C₆H₁₂O₆) is:', 'mcq', '["0","+4","−4","+2"]', '0', 'hard', 7, 'jee', '6C + 12(+1) + 6(−2) = 0 gives 6C = 0, so the average oxidation number of carbon is 0.', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_013', 'The oxidation number of chlorine in perchloric acid (HClO₄) is:', 'mcq', '["+1","+3","+5","+7"]', '+7', 'hard', 6, 'jee', '(+1) + Cl + 4(−2) = 0 gives Cl = +7.', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_014', 'The average oxidation number of iron in Fe₃O₄ is:', 'mcq', '["+2","+3","+8/3","+4"]', '+8/3', 'hard', 8, 'jee', '3Fe + 4(−2) = 0 gives 3Fe = +8, so the average oxidation number is +8/3.', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
('axai_ch07_015', 'In which species does nitrogen have an oxidation number of +5?', 'mcq', '["NH₃","NO","HNO₃","N₂"]', 'HNO₃', 'hard', 6, 'jee', 'In HNO₃: (+1) + N + 3(−2) = 0 gives N = +5.', 'chem', 'ch07', 'ch07t1', 'ch07t1s1'),
-- ===== ch07t1s2 Balancing Redox Reactions =====
('axai_ch07_016', 'In a redox reaction, the species that loses electrons is:', 'mcq', '["reduced","oxidised","the oxidising agent","unchanged"]', 'oxidised', 'easy', 2, 'both', 'Loss of electrons is oxidation, so the species losing electrons is oxidised.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_017', 'The oxidising agent in a redox reaction is the species that:', 'mcq', '["loses electrons","gains electrons","is itself oxidised","donates protons"]', 'gains electrons', 'easy', 3, 'both', 'An oxidising agent accepts (gains) electrons and is itself reduced.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_018', 'A reducing agent is a substance that:', 'mcq', '["gains electrons","loses electrons","gains protons","is itself reduced"]', 'loses electrons', 'easy', 2, 'both', 'A reducing agent donates (loses) electrons and is itself oxidised.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_019', 'In the ion-electron method, charge in acidic medium is balanced by adding:', 'mcq', '["OH⁻ ions","H⁺ ions and electrons","O₂","Na⁺ ions"]', 'H⁺ ions and electrons', 'easy', 3, 'both', 'In acidic medium, H⁺ balances hydrogen/charge and electrons balance the net charge.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_020', 'A disproportionation reaction is one in which the same element is:', 'mcq', '["only oxidised","only reduced","both oxidised and reduced","unchanged"]', 'both oxidised and reduced', 'easy', 3, 'both', 'In disproportionation a single element is simultaneously oxidised and reduced.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_021', 'In Zn + Cu²⁺ → Zn²⁺ + Cu, the reducing agent is:', 'mcq', '["Cu²⁺","Zn","Zn²⁺","Cu"]', 'Zn', 'medium', 4, 'both', 'Zn loses electrons (is oxidised), so it acts as the reducing agent.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_022', 'In 2Na + Cl₂ → 2NaCl, chlorine acts as the:', 'mcq', '["reducing agent","oxidising agent","catalyst","base"]', 'oxidising agent', 'medium', 4, 'both', 'Cl₂ gains electrons (is reduced to Cl⁻), so it is the oxidising agent.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_023', 'When balancing in basic medium, oxygen and hydrogen are balanced using:', 'mcq', '["H⁺ only","H₂O and OH⁻","Cl₂","Na⁺"]', 'H₂O and OH⁻', 'medium', 5, 'both', 'In basic medium, H₂O and OH⁻ are used to balance oxygen and hydrogen atoms.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_024', 'In MnO₄⁻ → Mn²⁺ (acidic medium), the number of electrons gained per Mn is:', 'mcq', '["2","3","5","7"]', '5', 'medium', 6, 'both', 'Manganese goes from +7 to +2, a gain of 5 electrons.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_025', 'In Cr₂O₇²⁻ → 2Cr³⁺ (acidic medium), the total number of electrons gained is:', 'mcq', '["3","6","2","7"]', '6', 'medium', 6, 'both', 'Each Cr changes +6 → +3 (3 e⁻); two Cr atoms gain a total of 6 electrons.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_026', 'When MnO₄⁻ is reduced to Mn²⁺ in acidic solution, the number of H⁺ ions required per MnO₄⁻ is:', 'mcq', '["4","5","8","2"]', '8', 'hard', 7, 'jee', 'MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O requires 8 H⁺ ions.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_027', 'The reaction 3Cl₂ + 6NaOH → 5NaCl + NaClO₃ + 3H₂O is an example of:', 'mcq', '["combination","disproportionation","neutralisation","double displacement"]', 'disproportionation', 'hard', 7, 'jee', 'Chlorine (0) is both reduced to −1 (NaCl) and oxidised to +5 (NaClO₃), a disproportionation.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_028', 'In the balanced reaction of MnO₄⁻ with Fe²⁺ in acid, the mole ratio MnO₄⁻ : Fe²⁺ is:', 'mcq', '["1 : 1","1 : 5","5 : 1","1 : 2"]', '1 : 5', 'hard', 8, 'jee', 'MnO₄⁻ gains 5 e⁻ while each Fe²⁺ loses 1 e⁻, so one MnO₄⁻ oxidises five Fe²⁺.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_029', 'One mole of Cr₂O₇²⁻ oxidises how many moles of Fe²⁺ in acidic solution?', 'mcq', '["2","3","6","1"]', '6', 'hard', 8, 'jee', 'Cr₂O₇²⁻ gains 6 electrons, so it oxidises 6 moles of Fe²⁺ (each losing 1 e⁻).', 'chem', 'ch07', 'ch07t1', 'ch07t1s2'),
('axai_ch07_030', 'When O₂ is converted to H₂O, the change in oxidation number of oxygen is:', 'mcq', '["0 to −2","−2 to 0","0 to +2","−1 to −2"]', '0 to −2', 'hard', 6, 'jee', 'Oxygen in O₂ is 0 and in H₂O is −2, so it is reduced from 0 to −2.', 'chem', 'ch07', 'ch07t1', 'ch07t1s2')
on conflict (id) do nothing;
