-- ch03t2 "VSEPR, Hybridisation & Geometry" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch03t2s1 VSEPR & Molecular Geometry        (axai_ch03_061..075)
--   ch03t2s2 Hybridisation & Bond Parameters   (axai_ch03_076..090)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch03t2s1', 'VSEPR & Molecular Geometry', 'ch03t2', 'ch03', 'chem', 1),
  ('ch03t2s2', 'Hybridisation & Bond Parameters', 'ch03t2', 'ch03', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch03t2s1 VSEPR & Molecular Geometry =====
('axai_ch03_061', 'According to VSEPR theory, the shape of a molecule is determined by:', 'mcq', '["the number of neutrons in the nucleus","the repulsion between electron pairs around the central atom","the atomic mass of the central atom","the colour of the molecule"]', 'the repulsion between electron pairs around the central atom', 'easy', 1, 'both', 'VSEPR theory states that electron pairs around the central atom arrange themselves to minimise mutual repulsion, fixing the shape.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_062', 'The shape of a methane (CH₄) molecule is:', 'mcq', '["square planar","tetrahedral","trigonal planar","linear"]', 'tetrahedral', 'easy', 1, 'both', 'Four bond pairs around carbon with no lone pairs give a regular tetrahedral shape.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_063', 'The H–C–H bond angle in methane is approximately:', 'mcq', '["90°","104.5°","109.5°","120°"]', '109.5°', 'easy', 2, 'both', 'A regular tetrahedral arrangement of four bond pairs gives bond angles of 109.5°.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_064', 'The shape of a carbon dioxide (CO₂) molecule is:', 'mcq', '["bent","linear","trigonal planar","tetrahedral"]', 'linear', 'easy', 2, 'both', 'Carbon has two bond pairs and no lone pairs, giving a linear O=C=O arrangement at 180°.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_065', 'The shape of a boron trifluoride (BF₃) molecule is:', 'mcq', '["pyramidal","trigonal planar","tetrahedral","bent"]', 'trigonal planar', 'easy', 2, 'both', 'Three bond pairs and no lone pairs on boron give a trigonal planar shape with 120° angles.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_066', 'The shape of an ammonia (NH₃) molecule is:', 'mcq', '["trigonal planar","trigonal pyramidal","tetrahedral","linear"]', 'trigonal pyramidal', 'medium', 4, 'both', 'Three bond pairs and one lone pair give a trigonal pyramidal shape (tetrahedral electron geometry).', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_067', 'The H–O–H bond angle in water (104.5°) is less than the tetrahedral angle because:', 'mcq', '["oxygen is highly electronegative","the two lone pairs on oxygen repel the bond pairs more strongly","water is a liquid","hydrogen has no lone pairs"]', 'the two lone pairs on oxygen repel the bond pairs more strongly', 'medium', 5, 'both', 'Lone pair–lone pair and lone pair–bond pair repulsions compress the H–O–H angle below 109.5°.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_068', 'The shape of a phosphorus pentachloride (PCl₅) molecule is:', 'mcq', '["octahedral","trigonal bipyramidal","square planar","tetrahedral"]', 'trigonal bipyramidal', 'medium', 5, 'both', 'Five bond pairs and no lone pairs on phosphorus give a trigonal bipyramidal shape.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_069', 'The shape of a sulfur hexafluoride (SF₆) molecule is:', 'mcq', '["trigonal bipyramidal","octahedral","tetrahedral","pentagonal"]', 'octahedral', 'medium', 4, 'both', 'Six bond pairs and no lone pairs on sulfur give a regular octahedral shape.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_070', 'The correct decreasing order of repulsion between electron pairs is:', 'mcq', '["bp–bp > lp–bp > lp–lp","lp–lp > lp–bp > bp–bp","lp–bp > lp–lp > bp–bp","bp–bp > lp–lp > lp–bp"]', 'lp–lp > lp–bp > bp–bp', 'medium', 5, 'both', 'Lone pairs occupy more space, so lone pair–lone pair repulsion is strongest and bond pair–bond pair is weakest.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_071', 'The shape of a sulfur tetrafluoride (SF₄) molecule is:', 'mcq', '["tetrahedral","see-saw","square planar","trigonal pyramidal"]', 'see-saw', 'hard', 6, 'jee', 'SF₄ has four bond pairs and one lone pair (trigonal bipyramidal geometry), giving a see-saw shape.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_072', 'The shape of a chlorine trifluoride (ClF₃) molecule is:', 'mcq', '["trigonal planar","T-shaped","trigonal pyramidal","bent"]', 'T-shaped', 'hard', 7, 'jee', 'ClF₃ has three bond pairs and two lone pairs (trigonal bipyramidal geometry), giving a T-shaped molecule.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_073', 'The shape of a xenon tetrafluoride (XeF₄) molecule is:', 'mcq', '["tetrahedral","square planar","see-saw","octahedral"]', 'square planar', 'hard', 7, 'jee', 'XeF₄ has four bond pairs and two lone pairs (octahedral geometry); the lone pairs occupy axial positions, giving a square planar shape.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_074', 'The shape of a bromine pentafluoride (BrF₅) molecule is:', 'mcq', '["trigonal bipyramidal","square pyramidal","octahedral","pentagonal planar"]', 'square pyramidal', 'hard', 7, 'jee', 'BrF₅ has five bond pairs and one lone pair (octahedral geometry), giving a square pyramidal shape.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
('axai_ch03_075', 'The correct order of bond angles is:', 'mcq', '["H₂O > NH₃ > CH₄","CH₄ > NH₃ > H₂O","NH₃ > CH₄ > H₂O","CH₄ > H₂O > NH₃"]', 'CH₄ > NH₃ > H₂O', 'hard', 6, 'jee', 'As the number of lone pairs increases (0, 1, 2), bond pair repulsion is reduced and the angle shrinks: 109.5° > 107° > 104.5°.', 'chem', 'ch03', 'ch03t2', 'ch03t2s1'),
-- ===== ch03t2s2 Hybridisation & Bond Parameters =====
('axai_ch03_076', 'The hybridisation of the carbon atom in methane (CH₄) is:', 'mcq', '["sp","sp²","sp³","sp³d"]', 'sp³', 'easy', 1, 'both', 'Carbon forms four equivalent σ bonds using four sp³ hybrid orbitals.', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_077', 'The hybridisation of boron in boron trifluoride (BF₃) is:', 'mcq', '["sp","sp²","sp³","sp³d"]', 'sp²', 'easy', 2, 'both', 'Three σ bonds and no lone pair require three sp² hybrid orbitals (trigonal planar).', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_078', 'The hybridisation of beryllium in beryllium chloride (BeCl₂) is:', 'mcq', '["sp","sp²","sp³","sp³d²"]', 'sp', 'easy', 2, 'both', 'Two σ bonds and no lone pair require two sp hybrid orbitals, giving a linear molecule.', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_079', 'Which of the following carbon–carbon bonds is the shortest?', 'mcq', '["C–C single bond","C=C double bond","C≡C triple bond","all are equal"]', 'C≡C triple bond', 'easy', 3, 'both', 'Increasing bond order pulls the atoms closer, so the triple bond is the shortest.', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_080', 'The percentage of s-character in an sp hybrid orbital is:', 'mcq', '["25%","33%","50%","75%"]', '50%', 'easy', 3, 'both', 'An sp orbital is formed from one s and one p orbital, so it has 50% s-character.', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_081', 'The hybridisation of phosphorus in phosphorus pentachloride (PCl₅) is:', 'mcq', '["sp³","sp³d","sp³d²","sp²"]', 'sp³d', 'medium', 4, 'both', 'Five σ bonds require five hybrid orbitals (sp³d), giving a trigonal bipyramidal shape.', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_082', 'The hybridisation of sulfur in sulfur hexafluoride (SF₆) is:', 'mcq', '["sp³d","sp³d²","sp³","sp³d³"]', 'sp³d²', 'medium', 5, 'both', 'Six σ bonds require six hybrid orbitals (sp³d²), giving an octahedral shape.', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_083', 'The hybridisation of nitrogen in an ammonia (NH₃) molecule is:', 'mcq', '["sp","sp²","sp³","sp³d"]', 'sp³', 'medium', 4, 'both', 'Three bond pairs plus one lone pair occupy four sp³ hybrid orbitals.', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_084', 'As the s-character of a hybrid orbital increases, the bond angle:', 'mcq', '["decreases","increases","stays at 90°","becomes zero"]', 'increases', 'medium', 5, 'both', 'Higher s-character (sp³ 109.5° → sp² 120° → sp 180°) increases the bond angle.', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_085', 'Which of the following has the highest carbon–carbon bond enthalpy?', 'mcq', '["ethane (C–C)","ethene (C=C)","ethyne (C≡C)","all are equal"]', 'ethyne (C≡C)', 'medium', 5, 'both', 'Bond enthalpy increases with bond order, so the C≡C triple bond in ethyne is the strongest.', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_086', 'The hybridisation of xenon in xenon tetrafluoride (XeF₄) is:', 'mcq', '["sp³","sp³d","sp³d²","sp³d³"]', 'sp³d²', 'hard', 6, 'jee', 'Four bond pairs and two lone pairs occupy six sp³d² hybrid orbitals (octahedral electron geometry).', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_087', 'The hybridisation of the central iodine atom in the triiodide ion (I₃⁻) is:', 'mcq', '["sp","sp³","sp³d","sp³d²"]', 'sp³d', 'hard', 7, 'jee', 'The central iodine has two bond pairs and three lone pairs, requiring five sp³d hybrid orbitals (linear ion).', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_088', 'The hybridisation of chlorine in chlorine trifluoride (ClF₃) is:', 'mcq', '["sp³","sp³d","sp³d²","sp²"]', 'sp³d', 'hard', 6, 'jee', 'Three bond pairs and two lone pairs occupy five sp³d hybrid orbitals (trigonal bipyramidal electron geometry).', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_089', 'The carbon–hydrogen bond is shortest in:', 'mcq', '["ethane (sp³ C)","ethene (sp² C)","ethyne (sp C)","methane (sp³ C)"]', 'ethyne (sp C)', 'hard', 7, 'jee', 'The sp-hybridised carbon in ethyne has the highest s-character, pulling the bonding electrons closer and giving the shortest C–H bond.', 'chem', 'ch03', 'ch03t2', 'ch03t2s2'),
('axai_ch03_090', 'The correct decreasing order of bond angle in NH₃, PH₃ and AsH₃ is:', 'mcq', '["AsH₃ > PH₃ > NH₃","NH₃ > PH₃ > AsH₃","PH₃ > NH₃ > AsH₃","NH₃ > AsH₃ > PH₃"]', 'NH₃ > PH₃ > AsH₃', 'hard', 8, 'jee', 'Down the group the central atom''s electronegativity falls, the bond pairs move further from it, and the bond angle decreases.', 'chem', 'ch03', 'ch03t2', 'ch03t2s2')
on conflict (id) do nothing;
