-- ch11t1 "Transition Elements: Properties & Trends" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch11t1s1 d-Block Properties & Trends            (axai_ch11_001..015)
--   ch11t1s2 Lanthanoids & Actinoids (f-Block)      (axai_ch11_016..030)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch11t1s1', 'd-Block Properties & Trends', 'ch11t1', 'ch11', 'chem', 1),
  ('ch11t1s2', 'Lanthanoids & Actinoids (f-Block)', 'ch11t1', 'ch11', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch11t1s1 d-Block Properties & Trends =====
('axai_ch11_001', 'Transition elements are also known as the:', 'mcq', '["s-block elements","p-block elements","d-block elements","f-block elements"]', 'd-block elements', 'easy', 1, 'both', 'Transition elements have their last electron entering the (n-1)d orbital, so they form the d-block of the periodic table.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_002', 'The general outer electronic configuration of transition elements is:', 'mcq', '["(n-1)d¹⁻¹⁰ ns⁰⁻²","ns²np⁶","ns¹","(n-2)f¹⁻¹⁴"]', '(n-1)d¹⁻¹⁰ ns⁰⁻²', 'easy', 2, 'both', 'Transition metals have the general configuration (n-1)d¹⁻¹⁰ ns⁰⁻², with electrons filling the inner d-subshell.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_003', 'Transition metals commonly form coloured compounds because of:', 'mcq', '["fully filled d-orbitals","d-d electronic transitions","s-s transitions","ionic bonding"]', 'd-d electronic transitions', 'easy', 2, 'both', 'Partially filled d-orbitals allow d-d electronic transitions that absorb visible light, giving coloured compounds.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_004', 'A characteristic feature of transition elements is that they show:', 'mcq', '["only one oxidation state","variable oxidation states","no oxidation state","only negative oxidation states"]', 'variable oxidation states', 'easy', 1, 'both', 'Because (n-1)d and ns electrons have similar energies, transition metals lose different numbers of electrons, giving variable oxidation states.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_005', 'Transition metals and their compounds often act as good catalysts because of their:', 'mcq', '["fixed oxidation state","variable oxidation states and ability to form complexes","low melting points","non-metallic character"]', 'variable oxidation states and ability to form complexes', 'easy', 3, 'both', 'Variable oxidation states and the ability to form intermediate complexes let transition metals provide alternative low-energy reaction paths.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_006', 'Which transition metal ion is colourless in aqueous solution?', 'mcq', '["Cu²⁺","Fe³⁺","Zn²⁺","Ni²⁺"]', 'Zn²⁺', 'medium', 4, 'both', 'Zn²⁺ has a completely filled d¹⁰ configuration, so no d-d transition is possible and it is colourless.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_007', 'The highest oxidation state of manganese, seen in KMnO₄, is:', 'mcq', '["+4","+6","+7","+2"]', '+7', 'medium', 5, 'both', 'In KMnO₄ manganese uses all its 3d⁵4s² electrons, giving the maximum oxidation state of +7.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_008', 'Transition metals have high melting and boiling points mainly because of:', 'mcq', '["weak van der Waals forces","strong metallic bonding involving d-electrons","ionic bonding","hydrogen bonding"]', 'strong metallic bonding involving d-electrons', 'medium', 5, 'both', 'The participation of unpaired d-electrons in metallic bonding gives strong interatomic forces and high melting points.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_009', 'Which property is generally exhibited by transition metal ions with unpaired d-electrons?', 'mcq', '["diamagnetism","paramagnetism","ferroelectricity","superconductivity"]', 'paramagnetism', 'medium', 4, 'both', 'Unpaired d-electrons give a net magnetic moment, so such ions are paramagnetic.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_010', 'The element with the electronic configuration showing an anomaly, [Ar]3d⁵4s¹, is:', 'mcq', '["chromium","manganese","iron","vanadium"]', 'chromium', 'medium', 5, 'jee', 'Chromium adopts [Ar]3d⁵4s¹ because the half-filled d⁵ and s¹ arrangement gives extra stability.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_011', 'The "spin-only" magnetic moment of an ion with three unpaired electrons is approximately:', 'mcq', '["1.73 BM","2.83 BM","3.87 BM","5.92 BM"]', '3.87 BM', 'hard', 6, 'jee', 'Using μ = √(n(n+2)) with n = 3 gives √15 ≈ 3.87 Bohr magnetons.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_012', 'Mn²⁺ (3d⁵) compounds are more stable than Mn³⁺ compounds because Mn²⁺ has a:', 'mcq', '["fully filled d-subshell","half-filled (d⁵) stable configuration","empty d-subshell","large size"]', 'half-filled (d⁵) stable configuration', 'hard', 7, 'jee', 'The half-filled 3d⁵ configuration of Mn²⁺ gives extra exchange-energy stability, so it resists further oxidation.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_013', 'Across the first transition series, the atomic radii first decrease and then stay nearly constant because of the balance between:', 'mcq', '["increasing nuclear charge and increasing d-electron screening","decreasing nuclear charge and ionic bonding","hydrogen bonding and metallic bonding","lanthanoid contraction and ionisation"]', 'increasing nuclear charge and increasing d-electron screening', 'hard', 7, 'jee', 'As nuclear charge rises across the series, the added d-electrons screen it, so the contracting and screening effects nearly cancel and radii level off.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_014', 'Zinc, cadmium and mercury are generally not regarded as typical transition elements because they have:', 'mcq', '["partially filled d-orbitals in all states","completely filled d-orbitals (d¹⁰) in their common states","no d-electrons","variable oxidation states"]', 'completely filled d-orbitals (d¹⁰) in their common states', 'hard', 6, 'jee', 'Zn, Cd and Hg have full d¹⁰ subshells in the atom and common +2 ion, so they lack the typical transition-metal properties.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
('axai_ch11_015', 'The strong oxidising nature of the dichromate ion (Cr₂O₇²⁻) in acidic medium is shown by the reduction of chromium to:', 'mcq', '["Cr (metal)","Cr³⁺","Cr⁶⁺","CrO₄²⁻"]', 'Cr³⁺', 'hard', 8, 'jee', 'In acidic medium dichromate is reduced from Cr(VI) to the stable Cr³⁺ (green), acting as a strong oxidising agent.', 'chem', 'ch11', 'ch11t1', 'ch11t1s1'),
-- ===== ch11t1s2 Lanthanoids & Actinoids (f-Block) =====
('axai_ch11_016', 'The lanthanoids and actinoids together make up the:', 'mcq', '["s-block","p-block","d-block","f-block"]', 'f-block', 'easy', 1, 'both', 'In the lanthanoids and actinoids the last electron enters the (n-2)f orbital, so they form the f-block (inner transition elements).', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_017', 'The most common and stable oxidation state of the lanthanoids is:', 'mcq', '["+1","+2","+3","+4"]', '+3', 'easy', 1, 'both', 'Lanthanoids predominantly show the +3 oxidation state, which is the most stable across the series.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_018', 'The steady decrease in atomic and ionic radii of lanthanoids with increasing atomic number is called:', 'mcq', '["actinoid contraction","lanthanoid contraction","inert pair effect","diagonal relationship"]', 'lanthanoid contraction', 'easy', 2, 'both', 'The poor shielding by 4f electrons causes a gradual decrease in size across the series, known as the lanthanoid contraction.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_019', 'Which series of inner transition elements is radioactive throughout?', 'mcq', '["lanthanoids","actinoids","d-block","s-block"]', 'actinoids', 'easy', 2, 'both', 'All actinoid elements are radioactive, with the heavier members being synthetic and unstable.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_020', 'The 4f electrons are progressively filled in which series?', 'mcq', '["lanthanoids","actinoids","first transition series","alkali metals"]', 'lanthanoids', 'easy', 3, 'both', 'In lanthanoids (Ce to Lu) the 4f subshell is progressively filled.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_021', 'The poor shielding effect responsible for the lanthanoid contraction is caused by which electrons?', 'mcq', '["s-electrons","p-electrons","4f-electrons","d-electrons"]', '4f-electrons', 'medium', 4, 'jee', 'The diffuse 4f electrons shield the nuclear charge poorly, so the effective nuclear charge increases and size contracts across the series.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_022', 'A major consequence of the lanthanoid contraction is the nearly identical radii of:', 'mcq', '["Na and K","Zr and Hf","Li and Mg","B and Al"]', 'Zr and Hf', 'medium', 5, 'jee', 'The lanthanoid contraction makes the second- and third-row transition pair Zr and Hf almost the same size, so they behave very similarly.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_023', 'Actinoids show a greater variety of oxidation states than lanthanoids because in actinoids the:', 'mcq', '["5f, 6d and 7s orbitals have comparable energies","4f orbitals are deeply buried","they are all diamagnetic","they have no f-electrons"]', '5f, 6d and 7s orbitals have comparable energies', 'medium', 5, 'jee', 'The comparable energies of the 5f, 6d and 7s orbitals in actinoids allow many electrons to participate in bonding, giving variable oxidation states.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_024', 'Which lanthanoid ion shows a stable +4 oxidation state because of an empty 4f⁰ configuration?', 'mcq', '["La³⁺","Ce⁴⁺","Eu²⁺","Gd³⁺"]', 'Ce⁴⁺', 'medium', 5, 'jee', 'Ce⁴⁺ attains the stable 4f⁰ configuration, so cerium can show a +4 state in addition to +3.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_025', 'A mixture of lanthanoid metals (mainly Ce) used to make alloys for lighter flints is called:', 'mcq', '["amalgam","misch metal","brass","bronze"]', 'misch metal', 'medium', 4, 'both', 'Misch metal is an alloy of lanthanoids (mostly cerium) used in lighter flints and as a deoxidiser in steel.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_026', 'Which lanthanoid ion shows a stable +2 oxidation state due to a half-filled 4f⁷ configuration?', 'mcq', '["Ce²⁺","Eu²⁺","Lu²⁺","Pr²⁺"]', 'Eu²⁺', 'hard', 7, 'jee', 'Eu²⁺ attains the extra-stable half-filled 4f⁷ configuration, so europium can show the +2 state.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_027', 'The actinoid contraction is greater than the lanthanoid contraction across the series because:', 'mcq', '["5f electrons shield even more poorly than 4f electrons","actinoids are diamagnetic","actinoids have no nuclear charge","5f orbitals are fully filled"]', '5f electrons shield even more poorly than 4f electrons', 'hard', 7, 'jee', 'The 5f electrons shield the nuclear charge even less effectively than 4f electrons, so the actinoid contraction is more pronounced.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_028', 'The general electronic configuration of lanthanoids is best represented as:', 'mcq', '["[Xe]4f¹⁻¹⁴5d⁰⁻¹6s²","[Rn]5f¹⁻¹⁴6d⁰⁻¹7s²","[Ar]3d¹⁻¹⁰4s²","[Kr]4d¹⁻¹⁰5s²"]', '[Xe]4f¹⁻¹⁴5d⁰⁻¹6s²', 'hard', 6, 'jee', 'Lanthanoids have the general configuration [Xe]4f¹⁻¹⁴5d⁰⁻¹6s², with the 4f subshell being progressively filled.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_029', 'Compared with 4f orbitals in lanthanoids, the 5f orbitals of actinoids are:', 'mcq', '["more buried and less available for bonding","less buried and more available for bonding","completely filled","non-existent"]', 'less buried and more available for bonding', 'hard', 7, 'jee', 'The 5f orbitals extend further from the nucleus than 4f orbitals, so they take part in bonding more readily, explaining the variable oxidation states of actinoids.', 'chem', 'ch11', 'ch11t1', 'ch11t1s2'),
('axai_ch11_030', 'The highest oxidation state reached by uranium among the actinoids is:', 'mcq', '["+3","+4","+6","+7"]', '+6', 'hard', 8, 'jee', 'Uranium can use its 5f, 6d and 7s electrons to reach a maximum oxidation state of +6 (as in UO₂²⁺ and UF₆).', 'chem', 'ch11', 'ch11t1', 'ch11t1s2')
on conflict (id) do nothing;
