-- ch05t2 "Entropy, Gibbs Energy & Spontaneity" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch05t2s1 Entropy & the Second Law       (axai_ch05_031..045)
--   ch05t2s2 Gibbs Energy & Spontaneity      (axai_ch05_046..060)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch05t2s1', 'Entropy & the Second Law', 'ch05t2', 'ch05', 'chem', 1),
  ('ch05t2s2', 'Gibbs Energy & Spontaneity', 'ch05t2', 'ch05', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch05t2s1 Entropy & the Second Law =====
('axai_ch05_031', 'Entropy is a measure of the:', 'mcq', '["disorder or randomness of a system","total energy of a system","pressure of a system","mass of a system"]', 'disorder or randomness of a system', 'easy', 1, 'both', 'Entropy (S) measures the degree of disorder or randomness in a system.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_032', 'When ice melts to water, the entropy of the substance:', 'mcq', '["increases","decreases","stays the same","becomes zero"]', 'increases', 'easy', 2, 'both', 'A liquid is more disordered than a solid, so melting increases entropy.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_033', 'The correct order of molar entropy for a given substance is:', 'mcq', '["solid > liquid > gas","gas > liquid > solid","liquid > gas > solid","gas > solid > liquid"]', 'gas > liquid > solid', 'easy', 2, 'both', 'Disorder increases from solid to liquid to gas, so entropy follows gas > liquid > solid.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_034', 'According to the second law of thermodynamics, in any spontaneous process the entropy of the universe:', 'mcq', '["decreases","increases","stays constant","becomes zero"]', 'increases', 'easy', 2, 'both', 'The second law states that the total entropy of the universe increases in a spontaneous process.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_035', 'The SI units of entropy are:', 'mcq', '["J K⁻¹ mol⁻¹","kJ mol⁻¹","J mol⁻¹","K mol⁻¹"]', 'J K⁻¹ mol⁻¹', 'easy', 3, 'both', 'Entropy has units of J K⁻¹ mol⁻¹ (energy per unit temperature per mole).', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_036', 'For a reversible phase change at temperature T, the entropy change is given by:', 'mcq', '["ΔS = ΔH × T","ΔS = ΔH / T","ΔS = T / ΔH","ΔS = ΔH + T"]', 'ΔS = ΔH / T', 'medium', 4, 'both', 'At a reversible phase transition ΔS = ΔH(transition)/T.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_037', 'When a gas expands into a vacuum, its entropy:', 'mcq', '["decreases","increases","stays the same","becomes negative"]', 'increases', 'medium', 4, 'both', 'Expansion increases the volume available to the molecules, raising the disorder and the entropy.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_038', 'For a reaction in which the number of moles of gas increases, the entropy change ΔS is generally:', 'mcq', '["positive","negative","zero","undefined"]', 'positive', 'medium', 5, 'both', 'More gaseous moles means greater disorder, so ΔS is positive.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_039', 'The total entropy change of the universe is given by:', 'mcq', '["ΔS(system) − ΔS(surroundings)","ΔS(system) + ΔS(surroundings)","ΔS(system) × ΔS(surroundings)","ΔS(surroundings) − ΔS(system)"]', 'ΔS(system) + ΔS(surroundings)', 'medium', 5, 'both', 'ΔS(universe) = ΔS(system) + ΔS(surroundings).', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_040', 'According to the third law of thermodynamics, the entropy of a perfectly crystalline substance at absolute zero is:', 'mcq', '["zero","infinite","positive","negative"]', 'zero', 'medium', 5, 'both', 'The third law states that the entropy of a perfect crystal at 0 K is exactly zero.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_041', 'The entropy change when 1 mol of ice melts at 273 K (ΔH(fusion) = 6.0 kJ mol⁻¹) is approximately:', 'mcq', '["22 J K⁻¹ mol⁻¹","6.0 J K⁻¹ mol⁻¹","273 J K⁻¹ mol⁻¹","16 J K⁻¹ mol⁻¹"]', '22 J K⁻¹ mol⁻¹', 'hard', 7, 'jee', 'ΔS = ΔH/T = 6000/273 ≈ 22 J K⁻¹ mol⁻¹.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_042', 'For the reaction N₂(g) + 3H₂(g) → 2NH₃(g), the entropy change ΔS is:', 'mcq', '["positive","negative","zero","equal to ΔH"]', 'negative', 'hard', 6, 'jee', 'Gaseous moles fall from 4 to 2, so disorder decreases and ΔS is negative.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_043', 'The entropy change of the surroundings for a process at constant temperature T is:', 'mcq', '["−ΔH(system)/T","ΔH(system)/T","−T/ΔH(system)","ΔH(system) × T"]', '−ΔH(system)/T', 'hard', 7, 'jee', 'Heat released by the system (−ΔH) flows to the surroundings, so ΔS(surroundings) = −ΔH(system)/T.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_044', 'A process is spontaneous when the total entropy change of the universe is:', 'mcq', '["negative","positive","zero","equal to ΔH"]', 'positive', 'hard', 6, 'jee', 'A spontaneous process increases the total entropy of the universe, so ΔS(universe) > 0.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
('axai_ch05_045', 'Which of the following has the highest molar entropy?', 'mcq', '["H₂O(s)","H₂O(l)","H₂O(g)","they are equal"]', 'H₂O(g)', 'hard', 6, 'jee', 'Water vapour is the most disordered state, so it has the highest molar entropy.', 'chem', 'ch05', 'ch05t2', 'ch05t2s1'),
-- ===== ch05t2s2 Gibbs Energy & Spontaneity =====
('axai_ch05_046', 'The Gibbs energy (G) is defined as:', 'mcq', '["G = H − TS","G = H + TS","G = U − TS","G = H − S"]', 'G = H − TS', 'easy', 2, 'both', 'Gibbs free energy is defined as G = H − TS.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_047', 'At constant temperature, the change in Gibbs energy is given by:', 'mcq', '["ΔG = ΔH − TΔS","ΔG = ΔH + TΔS","ΔG = TΔS − ΔH","ΔG = ΔH × TΔS"]', 'ΔG = ΔH − TΔS', 'easy', 2, 'both', 'At constant T, ΔG = ΔH − TΔS.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_048', 'A reaction at constant temperature and pressure is spontaneous when ΔG is:', 'mcq', '["positive","negative","zero","equal to ΔH"]', 'negative', 'easy', 2, 'both', 'A negative Gibbs energy change indicates a spontaneous (feasible) process.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_049', 'At equilibrium, the value of ΔG is:', 'mcq', '["positive","negative","zero","infinite"]', 'zero', 'easy', 3, 'both', 'At equilibrium there is no net driving force, so ΔG = 0.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_050', 'A reaction is non-spontaneous when ΔG is:', 'mcq', '["negative","positive","zero","equal to TΔS"]', 'positive', 'easy', 2, 'both', 'A positive Gibbs energy change means the process is non-spontaneous in the forward direction.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_051', 'A reaction with ΔH < 0 and ΔS > 0 is:', 'mcq', '["spontaneous at all temperatures","non-spontaneous at all temperatures","spontaneous only at high temperature","spontaneous only at low temperature"]', 'spontaneous at all temperatures', 'medium', 5, 'both', 'With ΔH negative and ΔS positive, ΔG = ΔH − TΔS is negative at every temperature.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_052', 'A reaction with ΔH > 0 and ΔS < 0 is:', 'mcq', '["spontaneous at all temperatures","non-spontaneous at all temperatures","spontaneous only at high temperature","spontaneous only at low temperature"]', 'non-spontaneous at all temperatures', 'medium', 5, 'both', 'With ΔH positive and ΔS negative, ΔG = ΔH − TΔS is positive at every temperature.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_053', 'At the temperature at which a phase change is at equilibrium, the temperature equals:', 'mcq', '["ΔH × ΔS","ΔH / ΔS","ΔS / ΔH","ΔH − ΔS"]', 'ΔH / ΔS', 'medium', 6, 'jee', 'At equilibrium ΔG = 0, so ΔH = TΔS and T = ΔH/ΔS.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_054', 'The standard Gibbs energy change is related to the equilibrium constant K by:', 'mcq', '["ΔG° = −RT ln K","ΔG° = RT ln K","ΔG° = −RT/K","ΔG° = RT K"]', 'ΔG° = −RT ln K', 'medium', 6, 'jee', 'The standard Gibbs energy change relates to K by ΔG° = −RT ln K.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_055', 'A reaction with ΔH < 0 and ΔS < 0 is spontaneous:', 'mcq', '["only at low temperature","only at high temperature","at all temperatures","at no temperature"]', 'only at low temperature', 'medium', 5, 'both', 'With both terms negative, −TΔS is positive; ΔG is negative only when T is low enough.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_056', 'A reaction with ΔH > 0 and ΔS > 0 is spontaneous:', 'mcq', '["only at low temperature","only at high temperature","at all temperatures","at no temperature"]', 'only at high temperature', 'hard', 6, 'jee', 'The −TΔS term becomes more negative as T rises, so ΔG turns negative only at high temperature.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_057', 'For a reaction with ΔH = +40 kJ and ΔS = +100 J K⁻¹ at 300 K, ΔG is:', 'mcq', '["+10 kJ","−10 kJ","+70 kJ","0 kJ"]', '+10 kJ', 'hard', 7, 'jee', 'ΔG = ΔH − TΔS = 40 − (300 × 0.100) = 40 − 30 = +10 kJ.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_058', 'For a reaction with ΔH = +30 kJ and ΔS = +100 J K⁻¹, the temperature above which it becomes spontaneous is:', 'mcq', '["300 K","30 K","3000 K","0.3 K"]', '300 K', 'hard', 7, 'jee', 'Spontaneity begins when ΔG = 0, i.e. T = ΔH/ΔS = 30000/100 = 300 K.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_059', 'For a reaction whose equilibrium constant K is greater than 1, the sign of ΔG° is:', 'mcq', '["negative","positive","zero","always undefined"]', 'negative', 'hard', 6, 'jee', 'Since ΔG° = −RT ln K, when K > 1 the ln K term is positive and ΔG° is negative.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2'),
('axai_ch05_060', 'At the normal boiling point of a liquid, the Gibbs energy change for vaporisation is:', 'mcq', '["zero","positive","negative","equal to ΔH"]', 'zero', 'hard', 7, 'jee', 'At the boiling point liquid and vapour are in equilibrium, so ΔG of vaporisation is zero.', 'chem', 'ch05', 'ch05t2', 'ch05t2s2')
on conflict (id) do nothing;
