-- ch11t3 "VBT, CFT & Isomerism in Complexes" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch11t3s1 VBT & Crystal Field Theory                 (axai_ch11_061..075)
--   ch11t3s2 Isomerism in Coordination Compounds        (axai_ch11_076..090)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch11t3s1', 'VBT & Crystal Field Theory', 'ch11t3', 'ch11', 'chem', 1),
  ('ch11t3s2', 'Isomerism in Coordination Compounds', 'ch11t3', 'ch11', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch11t3s1 VBT & Crystal Field Theory =====
('axai_ch11_061', 'Valence bond theory (VBT) explains bonding in complexes in terms of:', 'mcq', '["overlap of hybridised metal orbitals with ligand orbitals","ionic attraction only","delocalised electrons","hydrogen bonding"]', 'overlap of hybridised metal orbitals with ligand orbitals', 'easy', 1, 'both', 'In VBT the metal provides empty hybrid orbitals that overlap with filled ligand orbitals to form coordinate bonds.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_062', 'According to crystal field theory, the bonding between metal and ligand is treated as:', 'mcq', '["purely covalent","purely electrostatic (ionic)","metallic","hydrogen bonding"]', 'purely electrostatic (ionic)', 'easy', 2, 'both', 'Crystal field theory regards the metal-ligand interaction as a purely electrostatic attraction between the metal ion and the ligands.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_063', 'In an octahedral field, the five d-orbitals split into two sets labelled:', 'mcq', '["t2g and eg","s and p","a1 and b1","sigma and pi"]', 't2g and eg', 'easy', 2, 'both', 'An octahedral crystal field splits the d-orbitals into the lower t2g set and the higher eg set.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_064', 'The hybridisation associated with a tetrahedral complex is:', 'mcq', '["sp³","dsp²","d²sp³","sp"]', 'sp³', 'easy', 2, 'both', 'A tetrahedral complex uses sp³ hybrid orbitals of the central metal.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_065', 'A complex with no unpaired electrons is described as:', 'mcq', '["paramagnetic","diamagnetic","ferromagnetic","antiferromagnetic"]', 'diamagnetic', 'easy', 3, 'both', 'When all electrons are paired the complex has no net magnetic moment, so it is diamagnetic.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_066', 'The hybridisation of the central metal in an inner-orbital octahedral complex such as [Co(NH₃)₆]³⁺ is:', 'mcq', '["sp³d²","d²sp³","sp³","dsp²"]', 'd²sp³', 'medium', 5, 'jee', 'Strong-field NH₃ causes inner (n-1)d orbitals to be used, giving d²sp³ hybridisation in [Co(NH₃)₆]³⁺.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_067', 'A ligand that causes a large crystal field splitting and favours low-spin complexes is called a:', 'mcq', '["weak-field ligand","strong-field ligand","ambidentate ligand","bridging ligand"]', 'strong-field ligand', 'medium', 4, 'both', 'Strong-field ligands (e.g. CN⁻, CO) produce a large splitting (Δ), forcing electrons to pair and giving low-spin complexes.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_068', 'According to the spectrochemical series, which ligand produces the largest crystal field splitting?', 'mcq', '["I⁻","Cl⁻","H₂O","CO"]', 'CO', 'medium', 5, 'jee', 'In the spectrochemical series CO is a very strong-field ligand and causes the largest splitting of the d-orbitals.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_069', 'The hybridisation of nickel in the square planar complex [Ni(CN)₄]²⁻ is:', 'mcq', '["sp³","dsp²","d²sp³","sp³d²"]', 'dsp²', 'medium', 5, 'jee', 'Strong-field CN⁻ gives a square planar diamagnetic complex with dsp² hybridisation of Ni²⁺.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_070', 'The colour of a transition metal complex arises mainly from:', 'mcq', '["ligand-ligand bonds","d-d electronic transitions across the crystal field gap","nuclear transitions","s-p transitions"]', 'd-d electronic transitions across the crystal field gap', 'medium', 4, 'both', 'Absorption of visible light promotes a d-electron across the crystal field splitting (Δ), and the complementary colour is observed.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_071', 'For a tetrahedral complex, the crystal field splitting energy (Δt) is related to the octahedral splitting (Δo) by approximately:', 'mcq', '["Δt = Δo","Δt = 2Δo","Δt = (4/9)Δo","Δt = 9Δo"]', 'Δt = (4/9)Δo', 'hard', 7, 'jee', 'For the same metal and ligands, Δt is about four-ninths of Δo, so tetrahedral complexes are almost always high-spin.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_072', 'The complex [Fe(CN)₆]³⁻ is low-spin with one unpaired electron, so its spin-only magnetic moment is about:', 'mcq', '["1.73 BM","2.83 BM","3.87 BM","5.92 BM"]', '1.73 BM', 'hard', 7, 'jee', 'Strong-field CN⁻ pairs the d-electrons of Fe³⁺ (d⁵) leaving one unpaired, giving μ = √(1·3) ≈ 1.73 BM.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_073', '[CoF₆]³⁻ is a high-spin (outer-orbital) complex, so its hybridisation is:', 'mcq', '["d²sp³","sp³d²","dsp²","sp³"]', 'sp³d²', 'hard', 6, 'jee', 'Weak-field F⁻ cannot pair the electrons of Co³⁺, so outer 4d orbitals are used, giving sp³d² hybridisation (high-spin).', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_074', 'A major limitation of valence bond theory is that it does not satisfactorily explain the:', 'mcq', '["geometry of complexes","colour and detailed magnetic properties of complexes","oxidation state","coordination number"]', 'colour and detailed magnetic properties of complexes', 'hard', 7, 'jee', 'VBT cannot quantitatively account for the colour and the precise magnetic behaviour of complexes, which crystal field theory addresses.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
('axai_ch11_075', 'Electrons pair up in the lower d-orbitals (low-spin) when the crystal field splitting energy is:', 'mcq', '["smaller than the pairing energy","greater than the pairing energy","equal to zero","negative"]', 'greater than the pairing energy', 'hard', 8, 'jee', 'When Δ exceeds the electron pairing energy, it is energetically favourable for electrons to pair in the lower set, giving a low-spin complex.', 'chem', 'ch11', 'ch11t3', 'ch11t3s1'),
-- ===== ch11t3s2 Isomerism in Coordination Compounds =====
('axai_ch11_076', 'Compounds with the same molecular formula but different arrangements of atoms are called:', 'mcq', '["isotopes","isomers","allotropes","isobars"]', 'isomers', 'easy', 1, 'both', 'Isomers have identical molecular formulae but differ in the arrangement of their atoms.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_077', 'Geometrical and optical isomerism are types of:', 'mcq', '["structural isomerism","stereoisomerism","ionisation isomerism","linkage isomerism"]', 'stereoisomerism', 'easy', 2, 'both', 'Geometrical (cis-trans) and optical isomerism arise from different spatial arrangements, so they are forms of stereoisomerism.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_078', 'Cis and trans isomers are examples of:', 'mcq', '["optical isomerism","geometrical isomerism","linkage isomerism","coordination isomerism"]', 'geometrical isomerism', 'easy', 2, 'both', 'Cis-trans (geometrical) isomerism arises from the different relative positions of ligands around the central metal.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_079', 'Isomers that are non-superimposable mirror images of each other are called:', 'mcq', '["geometrical isomers","optical isomers (enantiomers)","linkage isomers","ionisation isomers"]', 'optical isomers (enantiomers)', 'easy', 2, 'both', 'Optical isomers (enantiomers) are non-superimposable mirror images that rotate plane-polarised light in opposite directions.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_080', 'Isomerism arising because an ambidentate ligand can bind through different donor atoms (e.g. –NO₂ vs –ONO) is called:', 'mcq', '["linkage isomerism","ionisation isomerism","hydrate isomerism","coordination isomerism"]', 'linkage isomerism', 'easy', 3, 'jee', 'Linkage isomerism occurs when an ambidentate ligand such as NO₂⁻ coordinates through nitrogen or through oxygen.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_081', 'The pair [Co(NH₃)₅Br]SO₄ and [Co(NH₃)₅SO₄]Br are examples of:', 'mcq', '["linkage isomerism","ionisation isomerism","optical isomerism","geometrical isomerism"]', 'ionisation isomerism', 'medium', 5, 'jee', 'They give different ions in solution because the sulphate and bromide swap between the coordination sphere and the counter-ion position (ionisation isomerism).', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_082', 'The isomerism shown by [Cr(H₂O)₆]Cl₃ and [Cr(H₂O)₅Cl]Cl₂·H₂O is called:', 'mcq', '["hydrate (solvate) isomerism","linkage isomerism","coordination isomerism","optical isomerism"]', 'hydrate (solvate) isomerism', 'medium', 5, 'jee', 'These isomers differ in the number of water molecules inside the coordination sphere versus outside it (hydrate isomerism).', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_083', 'A square planar complex of the type [MA₂B₂] (e.g. [Pt(NH₃)₂Cl₂]) shows which isomerism?', 'mcq', '["only optical","geometrical (cis-trans)","only linkage","no isomerism"]', 'geometrical (cis-trans)', 'medium', 4, 'jee', 'In a square planar MA₂B₂ complex the two B ligands can be adjacent (cis) or opposite (trans), giving geometrical isomers.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_084', 'The interchange of ligands between cationic and anionic complexes, as in [Co(NH₃)₆][Cr(CN)₆] and [Cr(NH₃)₆][Co(CN)₆], is called:', 'mcq', '["ionisation isomerism","coordination isomerism","linkage isomerism","hydrate isomerism"]', 'coordination isomerism', 'medium', 5, 'jee', 'Coordination isomerism arises when ligands are distributed differently between the cationic and anionic complex parts.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_085', 'Geometrical isomerism is generally not shown by tetrahedral complexes because:', 'mcq', '["all four positions are spatially equivalent (adjacent)","they are always ionic","they have no ligands","tetrahedral metals are too small"]', 'all four positions are spatially equivalent (adjacent)', 'medium', 5, 'jee', 'In a regular tetrahedron all four ligand positions are adjacent and equivalent, so cis-trans isomers cannot arise.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_086', 'Which complex can exist as a pair of optical isomers?', 'mcq', '["trans-[Co(en)₂Cl₂]⁺","cis-[Co(en)₂Cl₂]⁺","[Co(NH₃)₆]³⁺","[PtCl₄]²⁻"]', 'cis-[Co(en)₂Cl₂]⁺', 'hard', 7, 'jee', 'The cis isomer of [Co(en)₂Cl₂]⁺ lacks a plane of symmetry, so it is chiral and exists as non-superimposable mirror images.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_087', 'The complex [Co(NH₃)₆]³⁺ does not show geometrical isomerism because:', 'mcq', '["all six ligands are identical","it is tetrahedral","it has ambidentate ligands","cobalt is in a low oxidation state"]', 'all six ligands are identical', 'hard', 6, 'jee', 'With six identical ammine ligands there is only one way to arrange them, so no cis-trans isomers are possible.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_088', 'An octahedral complex of the type [MA₃B₃] can exist as which two geometrical isomers?', 'mcq', '["cis and trans","facial (fac) and meridional (mer)","d and l","ortho and para"]', 'facial (fac) and meridional (mer)', 'hard', 7, 'jee', 'In [MA₃B₃] the three identical ligands can occupy one triangular face (fac) or a meridian (mer), giving facial and meridional isomers.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_089', 'Which isomer of [Pt(NH₃)₂Cl₂] is the anticancer drug cisplatin?', 'mcq', '["the trans isomer","the cis isomer","an optical isomer","a linkage isomer"]', 'the cis isomer', 'hard', 6, 'jee', 'Cisplatin is the cis isomer of [Pt(NH₃)₂Cl₂], in which the two chloride ligands are adjacent to each other.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2'),
('axai_ch11_090', 'The trans isomer of an [M(AA)₂B₂] complex (AA = symmetric bidentate) is usually optically inactive because it:', 'mcq', '["has no ligands","possesses a plane of symmetry","is tetrahedral","contains ambidentate ligands"]', 'possesses a plane of symmetry', 'hard', 8, 'jee', 'The trans isomer has a plane of symmetry, making it superimposable on its mirror image and therefore optically inactive.', 'chem', 'ch11', 'ch11t3', 'ch11t3s2')
on conflict (id) do nothing;
