-- ch04t1 "Ideal Gas Laws & Real Gases" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch04t1s1 Gas Laws (Boyle, Charles, Avogadro)   (axai_ch04_001..015)
--   ch04t1s2 Ideal Gas Equation & Dalton's Law       (axai_ch04_016..030)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch04t1s1', 'Gas Laws (Boyle, Charles, Avogadro)', 'ch04t1', 'ch04', 'chem', 1),
  ('ch04t1s2', 'Ideal Gas Equation & Dalton''s Law', 'ch04t1', 'ch04', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch04t1s1 Gas Laws (Boyle, Charles, Avogadro) =====
('axai_ch04_001', 'At constant temperature, the volume of a fixed mass of gas is:', 'mcq', '["directly proportional to pressure","inversely proportional to pressure","independent of pressure","proportional to the square of pressure"]', 'inversely proportional to pressure', 'easy', 1, 'both', 'Boyle''s law: at constant T, V ∝ 1/P for a fixed mass of gas.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_002', 'According to Charles''s law, at constant pressure the volume of a fixed mass of gas is:', 'mcq', '["inversely proportional to its absolute temperature","directly proportional to its absolute temperature","independent of temperature","proportional to the square of temperature"]', 'directly proportional to its absolute temperature', 'easy', 2, 'both', 'Charles''s law: at constant P, V ∝ T (in kelvin) for a fixed mass of gas.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_003', 'Avogadro''s law states that equal volumes of all gases at the same temperature and pressure contain an equal number of:', 'mcq', '["atoms","molecules","protons","electrons"]', 'molecules', 'easy', 2, 'both', 'Avogadro''s law: equal volumes of gases at the same T and P contain the same number of molecules.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_004', 'For a fixed mass of gas at constant temperature, the product PV is:', 'mcq', '["constant","zero","equal to T","equal to nR"]', 'constant', 'easy', 1, 'both', 'Boyle''s law can be written PV = constant at constant temperature for a fixed mass of gas.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_005', 'According to Charles''s law, at constant pressure the ratio V/T for a fixed mass of gas is:', 'mcq', '["constant","zero","equal to P","equal to R"]', 'constant', 'easy', 2, 'both', 'Charles''s law gives V/T = constant at constant pressure for a fixed mass of gas.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_006', 'A gas occupies 1 L at 2 atm. At constant temperature, its volume when the pressure is reduced to 1 atm is:', 'mcq', '["0.5 L","1 L","2 L","4 L"]', '2 L', 'medium', 4, 'both', 'By Boyle''s law P₁V₁ = P₂V₂: V₂ = (2 × 1)/1 = 2 L.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_007', 'A gas at 300 K is heated to 600 K at constant pressure. Its volume becomes:', 'mcq', '["half the original","unchanged","double the original","four times the original"]', 'double the original', 'medium', 4, 'both', 'By Charles''s law V ∝ T: doubling the absolute temperature doubles the volume.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_008', 'Extrapolating the volume–temperature graph of an ideal gas to zero volume gives a temperature of about:', 'mcq', '["0 °C","−100 °C","−273.15 °C","100 °C"]', '−273.15 °C', 'medium', 5, 'both', 'The V–T plots of all gases extrapolate to zero volume at −273.15 °C, which is absolute zero.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_009', 'The molar volume of an ideal gas at 273 K and 1 atm is approximately:', 'mcq', '["11.2 L","22.4 L","24.0 L","44.8 L"]', '22.4 L', 'medium', 4, 'both', 'One mole of an ideal gas occupies about 22.4 L at 273 K and 1 atm.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_010', 'Gay-Lussac''s law states that at constant volume the pressure of a fixed mass of gas is:', 'mcq', '["inversely proportional to absolute temperature","directly proportional to absolute temperature","independent of temperature","proportional to volume"]', 'directly proportional to absolute temperature', 'medium', 5, 'both', 'Gay-Lussac''s (pressure–temperature) law: at constant V, P ∝ T (in kelvin).', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_011', 'A gas occupies 500 mL at 27 °C. At constant pressure, its volume at 127 °C is:', 'mcq', '["375 mL","500 mL","667 mL","1000 mL"]', '667 mL', 'hard', 6, 'jee', 'By Charles''s law V₂ = V₁T₂/T₁ = 500 × 400/300 ≈ 667 mL (temperatures in kelvin).', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_012', 'A gas occupies 2 L at 1 atm. At constant temperature, the pressure required to compress it to 0.5 L is:', 'mcq', '["0.25 atm","2 atm","4 atm","8 atm"]', '4 atm', 'hard', 6, 'jee', 'By Boyle''s law P₂ = P₁V₁/V₂ = (1 × 2)/0.5 = 4 atm.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_013', 'A gas occupies 1 L at 1 atm and 300 K. Its volume at 2 atm and 600 K is:', 'mcq', '["0.5 L","1 L","2 L","4 L"]', '1 L', 'hard', 7, 'jee', 'Combined gas law: V₂ = P₁V₁T₂/(T₁P₂) = (1 × 1 × 600)/(300 × 2) = 1 L.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_014', 'At constant pressure, a gas initially at 27 °C must be heated to which temperature for its volume to double?', 'mcq', '["54 °C","327 °C","600 °C","54 K"]', '327 °C', 'hard', 7, 'jee', 'V ∝ T, so T₂ = 2 × 300 K = 600 K = 327 °C.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
('axai_ch04_015', 'For a fixed mass of gas at constant temperature, a plot of pressure (P) against 1/V is:', 'mcq', '["a curve through the origin","a straight line through the origin","a horizontal line","a parabola"]', 'a straight line through the origin', 'hard', 6, 'jee', 'Since P = constant × (1/V) by Boyle''s law, a P vs 1/V plot is a straight line passing through the origin.', 'chem', 'ch04', 'ch04t1', 'ch04t1s1'),
-- ===== ch04t1s2 Ideal Gas Equation & Dalton's Law =====
('axai_ch04_016', 'The ideal gas equation is written as:', 'mcq', '["PV = nRT","PV = nRT²","P/V = nRT","PVT = nR"]', 'PV = nRT', 'easy', 1, 'both', 'The ideal gas equation combines the gas laws as PV = nRT.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_017', 'The value of the universal gas constant R in SI units is approximately:', 'mcq', '["8.314 J K⁻¹ mol⁻¹","0.0821 J K⁻¹ mol⁻¹","1.987 J K⁻¹ mol⁻¹","22.4 J K⁻¹ mol⁻¹"]', '8.314 J K⁻¹ mol⁻¹', 'easy', 2, 'both', 'In SI units R = 8.314 J K⁻¹ mol⁻¹ (it equals 0.0821 L·atm K⁻¹ mol⁻¹).', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_018', 'Dalton''s law of partial pressures states that the total pressure of a mixture of non-reacting gases equals the:', 'mcq', '["product of the partial pressures","sum of the partial pressures","average of the partial pressures","difference of the partial pressures"]', 'sum of the partial pressures', 'easy', 2, 'both', 'Dalton''s law: P(total) = p₁ + p₂ + p₃ + … , the sum of the partial pressures.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_019', 'In the ideal gas equation PV = nRT, the symbol n represents the:', 'mcq', '["number of molecules","number of moles","number of atoms","mass of the gas"]', 'number of moles', 'easy', 2, 'both', 'n is the amount of gas in moles.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_020', 'The partial pressure of a gas in a mixture is equal to its mole fraction multiplied by the:', 'mcq', '["total pressure","total volume","absolute temperature","gas constant"]', 'total pressure', 'easy', 3, 'both', 'Partial pressure pᵢ = xᵢ × P(total), where xᵢ is the mole fraction.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_021', 'Using PV = nRT, the pressure of 1 mol of an ideal gas occupying 22.4 L at 273 K is about:', 'mcq', '["0.5 atm","1 atm","2 atm","22.4 atm"]', '1 atm', 'medium', 4, 'both', 'P = nRT/V = (1 × 0.0821 × 273)/22.4 ≈ 1 atm.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_022', 'A mixture contains 0.25 mol of gas A in a total of 1 mol of gas at a total pressure of 4 atm. The partial pressure of A is:', 'mcq', '["0.25 atm","1 atm","2 atm","4 atm"]', '1 atm', 'medium', 5, 'both', 'pₐ = xₐ × P = (0.25/1) × 4 = 1 atm.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_023', 'The density (d) of an ideal gas of molar mass M is given by:', 'mcq', '["d = PM/RT","d = RT/PM","d = PRT/M","d = M/PRT"]', 'd = PM/RT', 'medium', 5, 'both', 'From PV = (m/M)RT, density d = m/V = PM/RT.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_024', 'The volume occupied by 2 mol of an ideal gas at 273 K and 1 atm is:', 'mcq', '["11.2 L","22.4 L","44.8 L","89.6 L"]', '44.8 L', 'medium', 4, 'both', 'Molar volume is 22.4 L at these conditions, so 2 mol occupy 2 × 22.4 = 44.8 L.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_025', 'For a fixed amount of gas, the partial pressure of a component is directly proportional to its:', 'mcq', '["molar mass","mole fraction","density","viscosity"]', 'mole fraction', 'medium', 5, 'both', 'At fixed total pressure, pᵢ = xᵢ × P(total), so partial pressure is proportional to mole fraction.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_026', 'A gas has a density of 1.96 g L⁻¹ at 273 K and 1 atm. Its molar mass is approximately:', 'mcq', '["16 g mol⁻¹","28 g mol⁻¹","44 g mol⁻¹","64 g mol⁻¹"]', '44 g mol⁻¹', 'hard', 6, 'jee', 'M = d × molar volume = 1.96 × 22.4 ≈ 44 g mol⁻¹ (carbon dioxide).', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_027', 'A container holds equal moles of H₂ and O₂ at a total pressure of 1 atm. The partial pressure of H₂ is:', 'mcq', '["0.25 atm","0.5 atm","1 atm","2 atm"]', '0.5 atm', 'hard', 6, 'jee', 'Equal moles give each a mole fraction of 0.5, so p(H₂) = 0.5 × 1 = 0.5 atm.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_028', 'The pressure exerted by 0.5 mol of an ideal gas in a 22.4 L vessel at 273 K is about:', 'mcq', '["0.25 atm","0.5 atm","1 atm","2 atm"]', '0.5 atm', 'hard', 6, 'jee', 'P = nRT/V = (0.5 × 0.0821 × 273)/22.4 ≈ 0.5 atm.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_029', 'When a gas is collected over water, the pressure of the dry gas equals the total pressure minus the:', 'mcq', '["atmospheric pressure","aqueous tension (vapour pressure of water)","partial pressure of oxygen","lattice enthalpy"]', 'aqueous tension (vapour pressure of water)', 'hard', 7, 'jee', 'By Dalton''s law, p(dry gas) = P(total) − p(water vapour), where the latter is the aqueous tension.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2'),
('axai_ch04_030', 'The density of oxygen gas (O₂) at 273 K and 1 atm is approximately:', 'mcq', '["0.71 g L⁻¹","1.43 g L⁻¹","2.86 g L⁻¹","32 g L⁻¹"]', '1.43 g L⁻¹', 'hard', 7, 'jee', 'd = M/molar volume = 32/22.4 ≈ 1.43 g L⁻¹.', 'chem', 'ch04', 'ch04t1', 'ch04t1s2')
on conflict (id) do nothing;
