-- ch07t3 "Electrolysis & Faraday's Laws" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch07t3s1 Electrolysis & Products            (axai_ch07_061..075)
--   ch07t3s2 Faraday's Laws & Conductance       (axai_ch07_076..090)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch07t3s1', 'Electrolysis & Products', 'ch07t3', 'ch07', 'chem', 1),
  ('ch07t3s2', 'Faraday''s Laws & Conductance', 'ch07t3', 'ch07', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch07t3s1 Electrolysis & Products =====
('axai_ch07_061', 'In an electrolytic cell, electrical energy is used to drive a:', 'mcq', '["spontaneous reaction","non-spontaneous reaction","combustion reaction","neutralisation"]', 'non-spontaneous reaction', 'easy', 2, 'both', 'Electrolysis uses external electrical energy to force a non-spontaneous redox reaction.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_062', 'During electrolysis, reduction occurs at the:', 'mcq', '["anode","cathode","salt bridge","both electrodes"]', 'cathode', 'easy', 2, 'both', 'Cations are reduced at the cathode in any electrochemical cell.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_063', 'During electrolysis, oxidation occurs at the:', 'mcq', '["cathode","anode","salt bridge","neither electrode"]', 'anode', 'easy', 2, 'both', 'Anions are oxidised at the anode.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_064', 'In an electrolytic cell, the anode is connected to the:', 'mcq', '["negative terminal","positive terminal","salt bridge","voltmeter"]', 'positive terminal', 'easy', 3, 'both', 'In electrolysis the anode is the positive electrode (connected to the + terminal of the source).', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_065', 'Electrolysis of molten sodium chloride produces sodium metal at the:', 'mcq', '["anode","cathode","salt bridge","surface"]', 'cathode', 'easy', 3, 'both', 'Na⁺ ions are reduced to sodium metal at the cathode.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_066', 'During the electrolysis of molten NaCl, the product formed at the anode is:', 'mcq', '["Na","H₂","Cl₂","O₂"]', 'Cl₂', 'medium', 4, 'both', 'Chloride ions are oxidised at the anode to give chlorine gas.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_067', 'In the electrolysis of aqueous NaCl (brine), the gas liberated at the cathode is:', 'mcq', '["Cl₂","O₂","H₂","Na vapour"]', 'H₂', 'medium', 5, 'both', 'Water is reduced more easily than Na⁺, so hydrogen gas is evolved at the cathode.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_068', 'In the electrolysis of acidified water, the gas evolved at the anode is:', 'mcq', '["H₂","O₂","Cl₂","CO₂"]', 'O₂', 'medium', 5, 'both', 'Water is oxidised at the anode to liberate oxygen gas.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_069', 'During electrolysis of aqueous CuSO₄ using copper electrodes, the cathode:', 'mcq', '["loses mass","gains mass as Cu deposits","produces O₂","produces H₂"]', 'gains mass as Cu deposits', 'medium', 5, 'both', 'Cu²⁺ ions are reduced and deposited on the cathode, so it gains mass.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_070', 'In the electrolysis of dilute aqueous Na₂SO₄, the cathode and anode products respectively are:', 'mcq', '["Na and SO₂","H₂ and O₂","Cl₂ and H₂","O₂ and H₂"]', 'H₂ and O₂', 'medium', 6, 'both', 'Water is preferentially discharged: H₂ at the cathode and O₂ at the anode.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_071', 'In the electrolysis of concentrated brine, Cl₂ rather than O₂ is liberated at the anode mainly because of the:', 'mcq', '["low standard potential of chloride","overpotential of oxygen","high temperature","salt bridge"]', 'overpotential of oxygen', 'hard', 7, 'jee', 'The high overpotential for oxygen evolution makes chloride oxidation kinetically favoured.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_072', 'In the electrolysis of aqueous CuSO₄ with inert (Pt) electrodes, the anode product is:', 'mcq', '["Cu","H₂","O₂","SO₂"]', 'O₂', 'hard', 7, 'jee', 'With inert electrodes, water is oxidised at the anode to give O₂ (sulphate is not discharged).', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_073', 'The amount of substance deposited at an electrode during electrolysis depends on the:', 'mcq', '["voltage only","quantity of charge passed","colour of the solution","electrode size only"]', 'quantity of charge passed', 'hard', 6, 'jee', 'By Faraday''s first law, the mass deposited is proportional to the charge passed.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_074', 'In the electrolytic refining of copper, the impure copper is used as the:', 'mcq', '["cathode","anode","electrolyte","salt bridge"]', 'anode', 'hard', 7, 'jee', 'Impure copper is the anode; it dissolves and pure copper deposits on the cathode.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
('axai_ch07_075', 'In the electrolysis of water, the volume ratio of H₂ to O₂ collected is:', 'mcq', '["1 : 1","2 : 1","1 : 2","4 : 1"]', '2 : 1', 'hard', 6, 'jee', 'Water gives twice the volume of H₂ as O₂, a ratio of 2 : 1.', 'chem', 'ch07', 'ch07t3', 'ch07t3s1'),
-- ===== ch07t3s2 Faraday's Laws & Conductance =====
('axai_ch07_076', 'Faraday''s first law states that the mass deposited is proportional to the:', 'mcq', '["voltage","quantity of electricity passed","resistance","temperature"]', 'quantity of electricity passed', 'easy', 2, 'both', 'The mass liberated at an electrode is directly proportional to the charge (quantity of electricity) passed.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_077', 'One faraday of charge is approximately equal to:', 'mcq', '["9650 C","96500 C","965 C","6.02×10²³ C"]', '96500 C', 'easy', 2, 'both', 'One faraday ≈ 96500 coulombs, the charge of one mole of electrons.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_078', 'One faraday corresponds to the charge of one mole of:', 'mcq', '["protons","electrons","neutrons","atoms"]', 'electrons', 'easy', 2, 'both', 'A faraday is the magnitude of charge carried by one mole of electrons.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_079', 'The SI unit of electrical conductance is the:', 'mcq', '["ohm","siemens","volt","ampere"]', 'siemens', 'easy', 3, 'both', 'Conductance is the reciprocal of resistance and is measured in siemens (S).', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_080', 'The conductivity (κ) of an electrolyte solution generally ____ on dilution:', 'mcq', '["increases","decreases","stays constant","becomes negative"]', 'decreases', 'easy', 3, 'both', 'On dilution the number of ions per unit volume falls, so conductivity decreases.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_081', 'The charge required to deposit one mole of a metal from M⁺ ions (n = 1) is:', 'mcq', '["96500 C","193000 C","48250 C","9650 C"]', '96500 C', 'medium', 4, 'both', 'One mole of M⁺ needs one mole of electrons, i.e. 96500 C.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_082', 'To deposit one mole of aluminium (Al³⁺ + 3e⁻ → Al), the charge required is:', 'mcq', '["96500 C","193000 C","289500 C","32167 C"]', '289500 C', 'medium', 6, 'both', 'Three moles of electrons are needed: 3 × 96500 = 289500 C.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_083', 'Faraday''s second law states that for the same charge, the masses deposited are proportional to their:', 'mcq', '["atomic numbers","equivalent masses","densities","melting points"]', 'equivalent masses', 'medium', 5, 'both', 'For equal charge, masses liberated are in the ratio of their chemical equivalent masses.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_084', 'The molar conductivity (Λm) of an electrolyte ____ with increasing dilution:', 'mcq', '["decreases","increases","remains constant","becomes negative"]', 'increases', 'medium', 5, 'both', 'Molar conductivity increases on dilution as ions move more freely.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_085', 'The molar conductivity of a strong electrolyte at infinite dilution can be obtained using:', 'mcq', '["Faraday''s law","Kohlrausch''s law","the Nernst equation","Hess''s law"]', 'Kohlrausch''s law', 'medium', 5, 'both', 'Kohlrausch''s law of independent migration of ions gives Λm at infinite dilution.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_086', 'The mass of copper (atomic mass 63.5, n = 2) deposited by 96500 C of charge is:', 'mcq', '["63.5 g","31.75 g","127 g","15.9 g"]', '31.75 g', 'hard', 7, 'jee', 'm = (equivalent mass × Q)/F = (63.5/2 × 96500)/96500 = 31.75 g.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_087', 'The charge passed when a current of 2 A flows for 965 seconds is:', 'mcq', '["965 C","1930 C","96500 C","482.5 C"]', '1930 C', 'hard', 6, 'jee', 'Q = I × t = 2 × 965 = 1930 C.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_088', 'When the same charge is passed through AgNO₃ and CuSO₄ in series, the mole ratio of Ag to Cu deposited is:', 'mcq', '["1 : 1","1 : 2","2 : 1","3 : 1"]', '2 : 1', 'hard', 8, 'jee', 'Ag⁺ needs 1 e⁻ and Cu²⁺ needs 2 e⁻, so for equal charge moles are in the ratio 2 : 1.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_089', 'A current of 9.65 A is passed for 1000 s through molten NaCl. The moles of Na deposited are:', 'mcq', '["0.05 mol","0.1 mol","1 mol","0.2 mol"]', '0.1 mol', 'hard', 8, 'jee', 'Q = 9.65 × 1000 = 9650 C; moles of electrons = 9650/96500 = 0.1, so 0.1 mol Na is deposited.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2'),
('axai_ch07_090', 'Kohlrausch''s law is especially useful for finding the molar conductivity at infinite dilution of:', 'mcq', '["strong electrolytes only","weak electrolytes","metals","gases"]', 'weak electrolytes', 'hard', 7, 'jee', 'Weak electrolytes cannot be extrapolated directly, so Kohlrausch''s law is used to obtain their limiting molar conductivity.', 'chem', 'ch07', 'ch07t3', 'ch07t3s2')
on conflict (id) do nothing;
