-- ch08t1 "Rate Laws & Order of Reactions" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch08t1s1 Rate, Order & Molecularity              (axai_ch08_001..015)
--   ch08t1s2 Integrated Rate Equations & Half-Life   (axai_ch08_016..030)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch08t1s1', 'Rate, Order & Molecularity', 'ch08t1', 'ch08', 'chem', 1),
  ('ch08t1s2', 'Integrated Rate Equations & Half-Life', 'ch08t1', 'ch08', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch08t1s1 Rate, Order & Molecularity =====
('axai_ch08_001', 'The rate of a chemical reaction is the change in concentration of a reactant or product per unit:', 'mcq', '["volume","time","mass","temperature"]', 'time', 'easy', 1, 'both', 'Reaction rate is defined as the change in concentration per unit time.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_002', 'The order of a reaction is the sum of the powers of the concentration terms in the:', 'mcq', '["balanced equation","rate law","equilibrium expression","Nernst equation"]', 'rate law', 'easy', 2, 'both', 'Order is determined experimentally from the exponents in the rate law.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_003', 'The molecularity of an elementary reaction is the number of:', 'mcq', '["products formed","reacting species involved","steps in the mechanism","catalysts used"]', 'reacting species involved', 'easy', 3, 'both', 'Molecularity is the number of atoms, ions or molecules that collide in an elementary step.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_004', 'The SI-based unit of reaction rate is:', 'mcq', '["mol L⁻¹","mol L⁻¹ s⁻¹","s⁻¹","mol s"]', 'mol L⁻¹ s⁻¹', 'easy', 2, 'both', 'Rate is concentration change per time, so its unit is mol L⁻¹ s⁻¹.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_005', 'For a zero-order reaction, the rate is:', 'mcq', '["proportional to concentration","independent of concentration","proportional to time","always zero"]', 'independent of concentration', 'easy', 3, 'both', 'A zero-order rate equals the rate constant and does not depend on reactant concentration.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_006', 'For the rate law Rate = k[A][B]², the overall order is:', 'mcq', '["1","2","3","4"]', '3', 'medium', 4, 'both', 'Overall order = 1 + 2 = 3.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_007', 'The unit of the rate constant for a first-order reaction is:', 'mcq', '["mol L⁻¹ s⁻¹","s⁻¹","L mol⁻¹ s⁻¹","mol⁻² L² s⁻¹"]', 's⁻¹', 'medium', 5, 'both', 'For a first-order reaction the rate constant has units of s⁻¹.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_008', 'The unit of the rate constant for a zero-order reaction is:', 'mcq', '["s⁻¹","mol L⁻¹ s⁻¹","L mol⁻¹ s⁻¹","dimensionless"]', 'mol L⁻¹ s⁻¹', 'medium', 5, 'both', 'For zero order, rate = k, so k has the units of rate, mol L⁻¹ s⁻¹.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_009', 'The order of a reaction:', 'mcq', '["is always equal to molecularity","can be zero or fractional","is always a whole number","can never be zero"]', 'can be zero or fractional', 'medium', 5, 'both', 'Unlike molecularity, order is experimental and may be zero, fractional or negative.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_010', 'For Rate = k[A], doubling [A] changes the rate by a factor of:', 'mcq', '["1/2","2","4","no change"]', '2', 'medium', 4, 'both', 'Being first order in A, doubling [A] doubles the rate.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_011', 'For Rate = k[A]², doubling [A] changes the rate by a factor of:', 'mcq', '["2","4","8","1/2"]', '4', 'hard', 6, 'jee', 'Being second order, rate ∝ [A]², so doubling [A] multiplies the rate by 2² = 4.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_012', 'The unit of the rate constant for a second-order reaction is:', 'mcq', '["s⁻¹","mol L⁻¹ s⁻¹","L mol⁻¹ s⁻¹","mol² L⁻² s⁻¹"]', 'L mol⁻¹ s⁻¹', 'hard', 6, 'jee', 'For second order, k has units of L mol⁻¹ s⁻¹.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_013', 'For a reaction, doubling [A] increases the rate eight-fold. The order with respect to A is:', 'mcq', '["1","2","3","0"]', '3', 'hard', 7, 'jee', 'Since 2ⁿ = 8 gives n = 3, the reaction is third order in A.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_014', 'The molecularity of a reaction can never be:', 'mcq', '["one","two","zero","three"]', 'zero', 'hard', 6, 'jee', 'Molecularity counts colliding species in an elementary step, so it must be a whole number ≥ 1 (never zero).', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
('axai_ch08_015', 'For the rate law Rate = k[A]^½[B], the overall order is:', 'mcq', '["1","1.5","2","0.5"]', '1.5', 'hard', 7, 'jee', 'Overall order = ½ + 1 = 1.5.', 'chem', 'ch08', 'ch08t1', 'ch08t1s1'),
-- ===== ch08t1s2 Integrated Rate Equations & Half-Life =====
('axai_ch08_016', 'For a first-order reaction, the half-life is:', 'mcq', '["dependent on initial concentration","independent of initial concentration","always 1 s","equal to the rate constant"]', 'independent of initial concentration', 'easy', 3, 'both', 'The first-order half-life t₁/₂ = 0.693/k is independent of the starting concentration.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_017', 'The integrated rate law for a first-order reaction is:', 'mcq', '["k = (2.303/t) log([A]₀/[A])","k = [A]₀ − [A]","kt = 1/[A]","k = [A]₀/2"]', 'k = (2.303/t) log([A]₀/[A])', 'easy', 3, 'both', 'The first-order integrated form is k = (2.303/t) log([A]₀/[A]).', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_018', 'For a first-order reaction, a plot of log[A] versus time is:', 'mcq', '["a curve","a straight line","a parabola","a circle"]', 'a straight line', 'easy', 3, 'both', 'log[A] decreases linearly with time for a first-order reaction.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_019', 'The half-life of a reaction is the time taken for the reactant concentration to fall to:', 'mcq', '["zero","one-half of its initial value","one-quarter","double"]', 'one-half of its initial value', 'easy', 2, 'both', 'Half-life is the time required for half the reactant to be consumed.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_020', 'Radioactive decay typically follows ____ kinetics:', 'mcq', '["zero-order","first-order","second-order","third-order"]', 'first-order', 'easy', 3, 'both', 'Radioactive decay is a classic first-order process.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_021', 'For a first-order reaction, t₁/₂ is related to k by:', 'mcq', '["t₁/₂ = 0.693/k","t₁/₂ = k/0.693","t₁/₂ = 1/k","t₁/₂ = k²"]', 't₁/₂ = 0.693/k', 'medium', 4, 'both', 'For first order, t₁/₂ = 0.693/k.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_022', 'For a first-order reaction with k = 0.0693 s⁻¹, the half-life is:', 'mcq', '["1 s","10 s","100 s","0.693 s"]', '10 s', 'medium', 5, 'both', 't₁/₂ = 0.693/0.0693 = 10 s.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_023', 'For a zero-order reaction, the half-life is proportional to:', 'mcq', '["1/[A]₀","[A]₀","[A]₀²","ln[A]₀"]', '[A]₀', 'medium', 6, 'both', 'For zero order, t₁/₂ = [A]₀/2k, so it is proportional to the initial concentration.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_024', 'After 2 half-lives, the fraction of a first-order reactant remaining is:', 'mcq', '["1/2","1/4","1/8","0"]', '1/4', 'medium', 5, 'both', 'Each half-life halves the amount: after 2 half-lives, (1/2)² = 1/4 remains.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_025', 'For a first-order reaction, the plot that gives a straight line is:', 'mcq', '["[A] vs t","1/[A] vs t","ln[A] vs t","[A]² vs t"]', 'ln[A] vs t', 'medium', 5, 'both', 'A plot of ln[A] against time is linear for first-order kinetics.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_026', 'A first-order reaction is 50% complete in 30 min. The time for 75% completion is:', 'mcq', '["45 min","60 min","90 min","120 min"]', '60 min', 'hard', 7, 'jee', '75% completion corresponds to 2 half-lives, so 2 × 30 = 60 min.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_027', 'For a first-order reaction with k = 2.303×10⁻³ s⁻¹, the time for the concentration to fall to one-tenth of the initial value is:', 'mcq', '["100 s","1000 s","2303 s","10 s"]', '1000 s', 'hard', 8, 'jee', 't = (2.303/k) log(10) = 2.303/(2.303×10⁻³) = 1000 s.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_028', 'For a zero-order reaction, a plot of [A] versus time is:', 'mcq', '["a straight line with negative slope","an exponential curve","a horizontal line","a parabola"]', 'a straight line with negative slope', 'hard', 6, 'jee', '[A] decreases linearly with time (slope = −k) for a zero-order reaction.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_029', 'A first-order reaction reaches 99.9% completion in about how many half-lives?', 'mcq', '["3","5","10","100"]', '10', 'hard', 8, 'jee', '99.9% complete leaves 1/1000; since 2¹⁰ ≈ 1000, this is about 10 half-lives.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2'),
('axai_ch08_030', 'For a first-order reaction with k = 1.386×10⁻² min⁻¹, the half-life t₁/₂ is:', 'mcq', '["25 min","50 min","100 min","69.3 min"]', '50 min', 'hard', 7, 'jee', 't₁/₂ = 0.693/k = 0.693/0.01386 = 50 min.', 'chem', 'ch08', 'ch08t1', 'ch08t1s2')
on conflict (id) do nothing;
