-- ch09t1 "Alkali & Alkaline Earth Metals" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch09t1s1 Group 1: Alkali Metals            (axai_ch09_001..015)
--   ch09t1s2 Group 2: Alkaline Earth Metals    (axai_ch09_016..030)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch09t1s1', 'Group 1: Alkali Metals', 'ch09t1', 'ch09', 'chem', 1),
  ('ch09t1s2', 'Group 2: Alkaline Earth Metals', 'ch09t1', 'ch09', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch09t1s1 Group 1: Alkali Metals =====
('axai_ch09_001', 'The general valence-shell electronic configuration of alkali metals is:', 'mcq', '["ns¹","ns²","ns²np¹","ns²np⁵"]', 'ns¹', 'easy', 1, 'both', 'Group 1 alkali metals all have a single electron in their outermost s-orbital, giving the configuration ns¹.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_002', 'Which alkali metal imparts a crimson-red colour to a Bunsen flame?', 'mcq', '["sodium","potassium","lithium","caesium"]', 'lithium', 'easy', 2, 'both', 'Lithium gives a characteristic crimson-red flame, while sodium gives golden-yellow and potassium gives lilac.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_003', 'Alkali metals are stored under kerosene oil because they:', 'mcq', '["are radioactive","react vigorously with air and moisture","are very dense","sublime readily"]', 'react vigorously with air and moisture', 'easy', 1, 'both', 'Alkali metals are so reactive that they react with oxygen and water in air, so they are kept under kerosene to exclude air and moisture.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_004', 'On moving down Group 1, the atomic radius of alkali metals:', 'mcq', '["decreases","increases","remains constant","first increases then decreases"]', 'increases', 'easy', 2, 'both', 'Down the group a new shell is added at each step, so the atomic radius increases from Li to Cs.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_005', 'Alkali metals are the strongest reducing agents because they:', 'mcq', '["gain electrons easily","lose their single valence electron easily","have high ionisation enthalpy","have small atomic size"]', 'lose their single valence electron easily', 'easy', 3, 'both', 'Their low ionisation enthalpy lets them lose the ns¹ electron readily, making them powerful reducing agents.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_006', 'When sodium is burnt in excess of air, the main product formed is:', 'mcq', '["Na₂O (oxide)","Na₂O₂ (peroxide)","NaO₂ (superoxide)","NaOH"]', 'Na₂O₂ (peroxide)', 'medium', 4, 'both', 'Sodium burns in excess oxygen to give mainly sodium peroxide, Na₂O₂.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_007', 'Which alkali metal has the highest melting point?', 'mcq', '["lithium","sodium","potassium","caesium"]', 'lithium', 'medium', 5, 'both', 'Down the group metallic bonding weakens as size increases, so lithium (smallest) has the highest melting point.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_008', 'On dissolving in liquid ammonia, dilute solutions of alkali metals are blue because of:', 'mcq', '["ammoniated metal cations","ammoniated (solvated) electrons","colloidal metal particles","dissolved nitrogen"]', 'ammoniated (solvated) electrons', 'medium', 5, 'jee', 'The metal ionises in liquid ammonia releasing solvated electrons, which absorb light and give the characteristic blue colour.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_009', 'The correct order of increasing first ionisation enthalpy among alkali metals is:', 'mcq', '["Cs < K < Na < Li","Li < Na < K < Cs","Na < Li < K < Cs","K < Na < Li < Cs"]', 'Cs < K < Na < Li', 'medium', 5, 'both', 'Ionisation enthalpy decreases down the group as atomic size increases, so Cs has the lowest and Li the highest.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_010', 'Which compound is manufactured by the Solvay (ammonia-soda) process?', 'mcq', '["NaOH","Na₂CO₃","NaHSO₄","Na₂SO₄"]', 'Na₂CO₃', 'medium', 4, 'both', 'The Solvay process produces sodium carbonate (washing soda) from brine, ammonia and carbon dioxide.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_011', 'Lithium shows a diagonal relationship with which element?', 'mcq', '["beryllium","magnesium","aluminium","boron"]', 'magnesium', 'hard', 6, 'jee', 'Because of similar charge/size ratio, lithium resembles magnesium (the element diagonally placed in Group 2).', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_012', 'The abnormally high hydration enthalpy of the Li⁺ ion is due to its:', 'mcq', '["large size","small size and high charge density","low nuclear charge","high atomic mass"]', 'small size and high charge density', 'hard', 7, 'jee', 'Li⁺ is the smallest alkali metal ion, so its high charge density attracts water strongly, giving the largest hydration enthalpy.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_013', 'Among the alkali metals, the superoxide MO₂ is most stable for:', 'mcq', '["lithium","sodium","potassium","caesium"]', 'caesium', 'hard', 7, 'jee', 'Large cations stabilise the large superoxide ion through favourable lattice energy, so superoxides are most stable for the heaviest alkali metals like Cs.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_014', 'Lithium does not form a stable solid bicarbonate (LiHCO₃) because:', 'mcq', '["lithium is unreactive","the small Li⁺ ion cannot stabilise the large bicarbonate ion","it is highly soluble","it decomposes the carbonate"]', 'the small Li⁺ ion cannot stabilise the large bicarbonate ion', 'hard', 8, 'jee', 'A small cation cannot stabilise a large anion in the solid state, so LiHCO₃ exists only in solution.', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
('axai_ch09_015', 'The thermal stability of alkali metal carbonates M₂CO₃ down the group:', 'mcq', '["decreases","increases","remains unchanged","first decreases then increases"]', 'increases', 'hard', 6, 'jee', 'Larger cations down the group stabilise the carbonate ion better, so thermal stability of M₂CO₃ increases (Li₂CO₃ is least stable).', 'chem', 'ch09', 'ch09t1', 'ch09t1s1'),
-- ===== ch09t1s2 Group 2: Alkaline Earth Metals =====
('axai_ch09_016', 'The general valence-shell electronic configuration of alkaline earth metals is:', 'mcq', '["ns¹","ns²","ns²np¹","ns²np²"]', 'ns²', 'easy', 1, 'both', 'Group 2 alkaline earth metals have two electrons in the outermost s-orbital, giving the configuration ns².', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_017', 'Which alkaline earth metal imparts a brick-red colour to a flame?', 'mcq', '["magnesium","calcium","barium","beryllium"]', 'calcium', 'easy', 2, 'both', 'Calcium gives a characteristic brick-red flame; strontium gives crimson and barium gives apple-green.', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_018', 'The common oxidation state shown by alkaline earth metals in their compounds is:', 'mcq', '["+1","+2","+3","variable"]', '+2', 'easy', 1, 'both', 'By losing both ns² electrons, Group 2 metals attain a noble-gas configuration and show a fixed +2 oxidation state.', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_019', 'Which alkaline earth metal does NOT impart any characteristic colour to a flame?', 'mcq', '["calcium","strontium","barium","beryllium"]', 'beryllium', 'easy', 2, 'both', 'Beryllium (and magnesium) have high ionisation energies, so their electrons are not excited by the flame and give no colour.', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_020', 'The chief ore used in the manufacture of cement and quicklime is:', 'mcq', '["gypsum","limestone (CaCO₃)","dolomite","Epsom salt"]', 'limestone (CaCO₃)', 'easy', 3, 'both', 'Limestone (calcium carbonate) is heated to give quicklime (CaO) and is a key raw material for cement.', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_021', 'The solubility of alkaline earth metal sulphates (MSO₄) down the group:', 'mcq', '["increases","decreases","remains constant","first increases then decreases"]', 'decreases', 'medium', 5, 'jee', 'As cation size increases down the group, hydration enthalpy falls faster than lattice enthalpy, so sulphate solubility decreases (BaSO₄ is nearly insoluble).', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_022', 'Which hydroxide among the following is amphoteric?', 'mcq', '["Be(OH)₂","Mg(OH)₂","Ca(OH)₂","Ba(OH)₂"]', 'Be(OH)₂', 'medium', 5, 'jee', 'Be(OH)₂ dissolves in both acids and alkalis, so it is amphoteric, unlike the basic hydroxides of the other Group 2 metals.', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_023', 'The chemical formula of Epsom salt is:', 'mcq', '["CaSO₄·2H₂O","MgSO₄·7H₂O","CaSO₄·½H₂O","Na₂SO₄·10H₂O"]', 'MgSO₄·7H₂O', 'medium', 4, 'both', 'Epsom salt is magnesium sulphate heptahydrate, MgSO₄·7H₂O.', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_024', 'On heating gypsum (CaSO₄·2H₂O) to about 393 K, the product formed is:', 'mcq', '["anhydrous CaSO₄","plaster of Paris (CaSO₄·½H₂O)","CaO","Ca(OH)₂"]', 'plaster of Paris (CaSO₄·½H₂O)', 'medium', 5, 'both', 'Partial dehydration of gypsum at about 393 K gives plaster of Paris, calcium sulphate hemihydrate.', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_025', 'The solubility of alkaline earth metal hydroxides M(OH)₂ down the group:', 'mcq', '["decreases","increases","remains constant","is zero throughout"]', 'increases', 'medium', 5, 'jee', 'Lattice enthalpy decreases faster than hydration enthalpy down the group, so hydroxide solubility increases (Ba(OH)₂ is the most soluble).', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_026', 'Beryllium differs from the rest of its group and resembles aluminium because of a:', 'mcq', '["lanthanoid contraction","diagonal relationship","inert pair effect","screening effect"]', 'diagonal relationship', 'hard', 6, 'jee', 'Due to similar charge/size ratio, beryllium shows a diagonal relationship with aluminium, the element placed diagonally.', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_027', 'Beryllium chloride (BeCl₂) in the solid (polymeric) state has beryllium with hybridisation:', 'mcq', '["sp","sp²","sp³","sp³d"]', 'sp³', 'hard', 7, 'jee', 'In solid polymeric BeCl₂ each Be is bonded to four chlorines through bridging, giving sp³ hybridisation, while the vapour-phase monomer is sp linear.', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_028', 'The thermal stability of alkaline earth metal carbonates MCO₃ increases in the order:', 'mcq', '["BaCO₃ < CaCO₃ < MgCO₃ < BeCO₃","BeCO₃ < MgCO₃ < CaCO₃ < BaCO₃","CaCO₃ < BeCO₃ < BaCO₃ < MgCO₃","MgCO₃ < BeCO₃ < CaCO₃ < BaCO₃"]', 'BeCO₃ < MgCO₃ < CaCO₃ < BaCO₃', 'hard', 7, 'jee', 'Larger cations stabilise the carbonate ion more effectively, so thermal stability increases down the group from BeCO₃ to BaCO₃.', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_029', 'Which property generally decreases down Group 2 from Be to Ba?', 'mcq', '["atomic radius","ionic radius","ionisation enthalpy","density"]', 'ionisation enthalpy', 'hard', 6, 'jee', 'As atomic size increases down the group, the outer electrons are less tightly held, so ionisation enthalpy decreases.', 'chem', 'ch09', 'ch09t1', 'ch09t1s2'),
('axai_ch09_030', 'Both BeSO₄ and MgSO₄ are readily soluble in water, whereas CaSO₄, SrSO₄ and BaSO₄ are sparingly soluble, mainly because of the:', 'mcq', '["very low lattice enthalpy of Be and Mg sulphates","high hydration enthalpy of the small Be²⁺ and Mg²⁺ ions","covalent character of the heavier sulphates","high charge on the sulphate ion"]', 'high hydration enthalpy of the small Be²⁺ and Mg²⁺ ions', 'hard', 8, 'jee', 'The small Be²⁺ and Mg²⁺ ions have high hydration enthalpies that outweigh lattice enthalpy, making their sulphates very soluble.', 'chem', 'ch09', 'ch09t1', 'ch09t1s2')
on conflict (id) do nothing;
