-- ch04t2 "Kinetic Molecular Theory" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch04t2s1 Postulates & Molecular Speeds          (axai_ch04_031..045)
--   ch04t2s2 Kinetic Energy & Maxwell Distribution  (axai_ch04_046..060)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch04t2s1', 'Postulates & Molecular Speeds', 'ch04t2', 'ch04', 'chem', 1),
  ('ch04t2s2', 'Kinetic Energy & Maxwell Distribution', 'ch04t2', 'ch04', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch04t2s1 Postulates & Molecular Speeds =====
('axai_ch04_031', 'According to kinetic molecular theory, the molecules of a gas are in:', 'mcq', '["fixed positions","continuous random motion","slow ordered motion","no motion at all"]', 'continuous random motion', 'easy', 1, 'both', 'A core postulate is that gas molecules move continuously and randomly in straight lines.', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_032', 'In kinetic molecular theory, the actual volume of the gas molecules themselves is assumed to be:', 'mcq', '["equal to the container volume","negligible compared with the container volume","larger than the container volume","half the container volume"]', 'negligible compared with the container volume', 'easy', 2, 'both', 'The theory assumes the molecules are point masses whose own volume is negligible next to the container volume.', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_033', 'Collisions between the molecules of an ideal gas are assumed to be:', 'mcq', '["perfectly elastic","perfectly inelastic","partly inelastic","impossible"]', 'perfectly elastic', 'easy', 2, 'both', 'Molecular collisions are assumed perfectly elastic, so total kinetic energy is conserved.', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_034', 'In an ideal gas, the force of attraction or repulsion between the molecules is assumed to be:', 'mcq', '["very large","zero","attractive only","repulsive only"]', 'zero', 'easy', 2, 'both', 'The theory assumes there are no intermolecular forces in an ideal gas.', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_035', 'Which of the following is one of the three statistical molecular speeds?', 'mcq', '["root mean square speed","escape speed","speed of sound","terminal speed"]', 'root mean square speed', 'easy', 3, 'both', 'The three molecular speeds are the most probable, average and root mean square (rms) speeds.', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_036', 'The root mean square speed of gas molecules is given by:', 'mcq', '["√(3RT/M)","√(2RT/M)","√(8RT/πM)","3RT/M"]', '√(3RT/M)', 'medium', 4, 'both', 'The rms speed is u(rms) = √(3RT/M).', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_037', 'The root mean square speed of a gas is proportional to:', 'mcq', '["T","√T","1/T","T²"]', '√T', 'medium', 4, 'both', 'Since u(rms) = √(3RT/M), the speed is proportional to the square root of the absolute temperature.', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_038', 'At a given temperature, the root mean square speed of a gas is inversely proportional to:', 'mcq', '["the absolute temperature","the square root of its molar mass","its volume","its pressure"]', 'the square root of its molar mass', 'medium', 5, 'both', 'u(rms) = √(3RT/M), so at fixed T the speed varies as 1/√M.', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_039', 'At the same temperature, which of the following gases has the highest root mean square speed?', 'mcq', '["H₂","O₂","N₂","CO₂"]', 'H₂', 'medium', 5, 'both', 'Speed varies as 1/√M; hydrogen has the smallest molar mass, so it has the highest rms speed.', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_040', 'The correct increasing order of the three molecular speeds is:', 'mcq', '["u(rms) < u(avg) < u(mp)","u(mp) < u(avg) < u(rms)","u(avg) < u(mp) < u(rms)","all three are equal"]', 'u(mp) < u(avg) < u(rms)', 'medium', 5, 'both', 'For a Maxwell distribution the most probable speed is the smallest and the rms speed the largest.', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_041', 'At the same temperature, the root mean square speed of H₂ compared with O₂ is:', 'mcq', '["4 times greater","16 times greater","one-quarter as large","equal"]', '4 times greater', 'hard', 6, 'jee', 'u(H₂)/u(O₂) = √(M(O₂)/M(H₂)) = √(32/2) = 4, so H₂ is 4 times faster.', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_042', 'To double the root mean square speed of a gas, its absolute temperature must be:', 'mcq', '["doubled","halved","increased four-fold","increased eight-fold"]', 'increased four-fold', 'hard', 6, 'jee', 'Since u(rms) ∝ √T, doubling the speed requires quadrupling the absolute temperature.', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_043', 'The average (mean) speed of gas molecules is given by:', 'mcq', '["√(3RT/M)","√(2RT/M)","√(8RT/πM)","8RT/πM"]', '√(8RT/πM)', 'hard', 6, 'jee', 'The average speed is u(avg) = √(8RT/πM).', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_044', 'The most probable speed of gas molecules is given by:', 'mcq', '["√(3RT/M)","√(2RT/M)","√(8RT/πM)","2RT/M"]', '√(2RT/M)', 'hard', 7, 'jee', 'The most probable speed is u(mp) = √(2RT/M).', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
('axai_ch04_045', 'The ratio of the rms speed of a gas at 327 °C to that at 27 °C is:', 'mcq', '["√2","2","√3","4"]', '√2', 'hard', 7, 'jee', 'u ∝ √T; the ratio is √(600/300) = √2 (temperatures in kelvin).', 'chem', 'ch04', 'ch04t2', 'ch04t2s1'),
-- ===== ch04t2s2 Kinetic Energy & Maxwell Distribution =====
('axai_ch04_046', 'The average kinetic energy of the molecules of an ideal gas depends only on its:', 'mcq', '["pressure","volume","absolute temperature","molar mass"]', 'absolute temperature', 'easy', 2, 'both', 'Average translational kinetic energy depends only on the absolute temperature, not on the identity of the gas.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_047', 'The average kinetic energy of one mole of an ideal gas is:', 'mcq', '["(3/2)RT","(1/2)RT","(3/2)kT","RT"]', '(3/2)RT', 'easy', 3, 'both', 'The mean translational kinetic energy per mole is (3/2)RT.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_048', 'The average translational kinetic energy of a single gas molecule is:', 'mcq', '["(3/2)kT","(3/2)RT","kT","(1/2)kT"]', '(3/2)kT', 'easy', 3, 'both', 'Per molecule the mean translational kinetic energy is (3/2)kT, where k is the Boltzmann constant.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_049', 'As the absolute temperature of a gas approaches zero, the average kinetic energy of its molecules approaches:', 'mcq', '["infinity","zero","(3/2)R","a maximum"]', 'zero', 'easy', 2, 'both', 'Since KE ∝ T, the average kinetic energy approaches zero as the temperature approaches absolute zero.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_050', 'A Maxwell–Boltzmann distribution curve is a plot of the fraction of molecules against their:', 'mcq', '["speed","mass","volume","charge"]', 'speed', 'easy', 2, 'both', 'The Maxwell distribution shows the fraction of molecules possessing each molecular speed.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_051', 'As the temperature of a gas is increased, the peak of its Maxwell distribution curve:', 'mcq', '["shifts to a lower speed and rises","shifts to a higher speed and flattens","stays in the same place","disappears"]', 'shifts to a higher speed and flattens', 'medium', 5, 'both', 'Higher temperature broadens the distribution and shifts the peak to higher speed, lowering its height.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_052', 'In a Maxwell distribution, the speed corresponding to the peak of the curve is the:', 'mcq', '["root mean square speed","average speed","most probable speed","escape speed"]', 'most probable speed', 'medium', 5, 'both', 'The peak of the curve marks the most probable speed — the speed possessed by the largest fraction of molecules.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_053', 'If the absolute temperature of a gas is doubled, the average kinetic energy of its molecules:', 'mcq', '["is halved","is doubled","is quadrupled","stays the same"]', 'is doubled', 'medium', 4, 'both', 'Average kinetic energy ∝ T, so doubling the absolute temperature doubles the kinetic energy.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_054', 'The average kinetic energy of a gas is directly proportional to its temperature measured on the:', 'mcq', '["Celsius scale","Kelvin (absolute) scale","Fahrenheit scale","any scale"]', 'Kelvin (absolute) scale', 'medium', 4, 'both', 'KE = (3/2)RT requires the absolute (Kelvin) temperature.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_055', 'At the same temperature, samples of H₂ and O₂ have:', 'mcq', '["the same average kinetic energy","the same molecular speed","equal masses","equal volumes always"]', 'the same average kinetic energy', 'medium', 5, 'both', 'Average kinetic energy depends only on temperature, so both gases have the same average KE at the same T (though different speeds).', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_056', 'The Boltzmann constant (k) is equal to:', 'mcq', '["R × N_A","R / N_A","N_A / R","R + N_A"]', 'R / N_A', 'hard', 6, 'jee', 'The Boltzmann constant is the gas constant per molecule: k = R/N_A.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_057', 'The average translational kinetic energy of a gas molecule at 300 K is approximately (k = 1.38 × 10⁻²³ J K⁻¹):', 'mcq', '["6.2 × 10⁻²¹ J","6.2 × 10⁻²³ J","4.1 × 10⁻²¹ J","3.7 × 10⁻²⁰ J"]', '6.2 × 10⁻²¹ J', 'hard', 7, 'jee', 'KE = (3/2)kT = 1.5 × 1.38 × 10⁻²³ × 300 ≈ 6.2 × 10⁻²¹ J.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_058', 'The total area under a Maxwell–Boltzmann distribution curve represents the:', 'mcq', '["most probable speed","total number of molecules","average kinetic energy","pressure of the gas"]', 'total number of molecules', 'hard', 6, 'jee', 'The area under the curve equals the total number of molecules, which stays constant as temperature changes.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_059', 'On raising the temperature, the fraction of molecules possessing very high speeds:', 'mcq', '["decreases","increases","stays the same","becomes zero"]', 'increases', 'hard', 6, 'jee', 'Raising the temperature broadens the distribution toward higher speeds, increasing the fraction of fast molecules.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2'),
('axai_ch04_060', 'The average kinetic energy of one mole of an ideal gas at 273 K is approximately (R = 8.314 J K⁻¹ mol⁻¹):', 'mcq', '["3.4 kJ","2.3 kJ","1.7 kJ","6.8 kJ"]', '3.4 kJ', 'hard', 7, 'jee', 'KE = (3/2)RT = 1.5 × 8.314 × 273 ≈ 3404 J ≈ 3.4 kJ.', 'chem', 'ch04', 'ch04t2', 'ch04t2s2')
on conflict (id) do nothing;
