-- ch07t2 "Electrochemical Cells & EMF" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch07t2s1 Galvanic Cells & Electrode Potential   (axai_ch07_031..045)
--   ch07t2s2 Nernst Equation & EMF                  (axai_ch07_046..060)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch07t2s1', 'Galvanic Cells & Electrode Potential', 'ch07t2', 'ch07', 'chem', 1),
  ('ch07t2s2', 'Nernst Equation & EMF', 'ch07t2', 'ch07', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch07t2s1 Galvanic Cells & Electrode Potential =====
('axai_ch07_031', 'In a galvanic (voltaic) cell, chemical energy is converted into:', 'mcq', '["heat energy","electrical energy","light energy","nuclear energy"]', 'electrical energy', 'easy', 1, 'both', 'A galvanic cell converts the energy of a spontaneous redox reaction into electrical energy.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_032', 'In a galvanic cell, oxidation occurs at the:', 'mcq', '["cathode","anode","salt bridge","voltmeter"]', 'anode', 'easy', 2, 'both', 'Oxidation always takes place at the anode.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_033', 'In a galvanic cell, the cathode is the electrode where:', 'mcq', '["oxidation occurs","reduction occurs","electrons are lost","no reaction occurs"]', 'reduction occurs', 'easy', 2, 'both', 'Reduction always takes place at the cathode.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_034', 'The standard hydrogen electrode is assigned a standard potential of:', 'mcq', '["+1.00 V","0.00 V","−1.00 V","0.76 V"]', '0.00 V', 'easy', 2, 'both', 'The SHE is the reference electrode with an assigned potential of exactly 0.00 V.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_035', 'The function of a salt bridge in a galvanic cell is to:', 'mcq', '["supply electrons","maintain electrical neutrality","increase temperature","act as a catalyst"]', 'maintain electrical neutrality', 'easy', 3, 'both', 'The salt bridge completes the circuit and keeps the half-cells electrically neutral.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_036', 'In the cell Zn | Zn²⁺ || Cu²⁺ | Cu, the anode is:', 'mcq', '["Cu","Zn","Cu²⁺","the salt bridge"]', 'Zn', 'medium', 4, 'both', 'By convention the left-hand electrode is the anode; here Zn is oxidised.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_037', 'A more positive standard reduction potential means the species is a:', 'mcq', '["stronger reducing agent","stronger oxidising agent","weaker oxidiser","poor electrode"]', 'stronger oxidising agent', 'medium', 5, 'both', 'A high (positive) reduction potential indicates a strong tendency to be reduced, i.e. a strong oxidising agent.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_038', 'The standard cell potential is calculated as:', 'mcq', '["E°cathode + E°anode","E°cathode − E°anode","E°anode − E°cathode","E°cathode × E°anode"]', 'E°cathode − E°anode', 'medium', 5, 'both', 'E°cell = E°cathode − E°anode, using standard reduction potentials.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_039', 'For the Daniell cell (E°(Cu²⁺/Cu) = +0.34 V, E°(Zn²⁺/Zn) = −0.76 V), the standard EMF is:', 'mcq', '["+0.42 V","+1.10 V","−1.10 V","+0.34 V"]', '+1.10 V', 'medium', 5, 'both', 'E°cell = 0.34 − (−0.76) = +1.10 V.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_040', 'In a galvanic cell, electrons flow through the external circuit from the:', 'mcq', '["cathode to anode","anode to cathode","salt bridge to anode","cathode to salt bridge"]', 'anode to cathode', 'medium', 4, 'both', 'Electrons released by oxidation at the anode flow externally to the cathode.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_041', 'A positive standard cell potential (E°cell > 0) indicates the cell reaction is:', 'mcq', '["non-spontaneous","spontaneous","at equilibrium","endothermic"]', 'spontaneous', 'hard', 6, 'both', 'A positive E°cell corresponds to negative ΔG°, so the reaction is spontaneous.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_042', 'Given E°(Ag⁺/Ag) = +0.80 V and E°(Cu²⁺/Cu) = +0.34 V, the EMF of Cu | Cu²⁺ || Ag⁺ | Ag is:', 'mcq', '["+0.46 V","+1.14 V","−0.46 V","+0.34 V"]', '+0.46 V', 'hard', 7, 'jee', 'E°cell = E°cathode − E°anode = 0.80 − 0.34 = +0.46 V.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_043', 'The relationship between standard cell potential and standard Gibbs energy is:', 'mcq', '["ΔG° = nFE°cell","ΔG° = −nFE°cell","ΔG° = E°cell/nF","ΔG° = −nF/E°cell"]', 'ΔG° = −nFE°cell', 'hard', 7, 'jee', 'ΔG° = −nFE°cell links cell potential to the standard Gibbs energy change.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_044', 'For the Daniell cell (E°cell = 1.10 V, n = 2, F = 96500 C), ΔG° is approximately:', 'mcq', '["−212 kJ","+212 kJ","−106 kJ","−96.5 kJ"]', '−212 kJ', 'hard', 8, 'jee', 'ΔG° = −nFE° = −2 × 96500 × 1.10 ≈ −2.12×10⁵ J = −212 kJ.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
('axai_ch07_045', 'In the electrochemical series, a metal with a very negative standard reduction potential is a:', 'mcq', '["weak reducing agent","strong reducing agent","strong oxidising agent","noble metal"]', 'strong reducing agent', 'hard', 7, 'jee', 'A very negative reduction potential means a strong tendency to be oxidised, i.e. a strong reducing agent.', 'chem', 'ch07', 'ch07t2', 'ch07t2s1'),
-- ===== ch07t2s2 Nernst Equation & EMF =====
('axai_ch07_046', 'The Nernst equation relates electrode potential to the:', 'mcq', '["temperature only","ion concentration","colour","mass of electrode"]', 'ion concentration', 'easy', 2, 'both', 'The Nernst equation expresses how electrode potential varies with ion concentration (and temperature).', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_047', 'In the form E = E° − (0.0591/n) log Q at 298 K, the factor 0.0591 has units of:', 'mcq', '["volts","joules","coulombs","amperes"]', 'volts', 'easy', 3, 'both', 'The term (0.0591/n) log Q is a potential, so 0.0591 is expressed in volts.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_048', 'In the Nernst equation, the symbol Q represents the:', 'mcq', '["equilibrium constant","reaction quotient","cell constant","Faraday constant"]', 'reaction quotient', 'easy', 3, 'both', 'Q is the reaction quotient, the ratio of product to reactant activities at any instant.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_049', 'When all species are at standard (unit) concentration, the cell potential equals:', 'mcq', '["zero","E°cell","infinity","0.0591 V"]', 'E°cell', 'easy', 2, 'both', 'At unit activities Q = 1 and log Q = 0, so E = E°cell.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_050', 'As a galvanic cell discharges, its cell potential gradually:', 'mcq', '["increases","decreases","stays constant","becomes infinite"]', 'decreases', 'easy', 3, 'both', 'As reactants are consumed, Q rises and the cell potential falls toward zero.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_051', 'At equilibrium, the EMF of an electrochemical cell is:', 'mcq', '["maximum","zero","negative","equal to E°cell"]', 'zero', 'medium', 5, 'both', 'At equilibrium there is no net reaction, so the cell EMF is zero.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_052', 'At 298 K for n = 1, the relation between E°cell and the equilibrium constant K is E°cell =:', 'mcq', '["0.0591 log K","(0.0591/2) log K","0.0591/K","log K"]', '0.0591 log K', 'medium', 6, 'jee', 'For n = 1, E°cell = (0.0591/1) log K = 0.0591 log K.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_053', 'In E = E° − (0.0591/n) log Q, increasing the concentration of the product ions makes E:', 'mcq', '["increase","decrease","unchanged","infinite"]', 'decrease', 'medium', 6, 'jee', 'Raising product concentrations increases Q, so the subtracted term grows and E decreases.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_054', 'For a concentration cell, the standard cell potential E°cell is:', 'mcq', '["large positive","zero","large negative","1.10 V"]', 'zero', 'medium', 6, 'jee', 'Both electrodes are identical, so E°cell = 0 and the EMF arises only from the concentration difference.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_055', 'In a Daniell cell, increasing the concentration of the product ion Zn²⁺ will:', 'mcq', '["increase E","decrease E","not change E","reverse the cell"]', 'decrease E', 'medium', 6, 'jee', 'Higher [Zn²⁺] increases Q = [Zn²⁺]/[Cu²⁺], lowering the cell potential.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_056', 'For a cell with E°cell = 0.0591 V and n = 1 at 298 K, the equilibrium constant K is:', 'mcq', '["1","10","100","0.1"]', '10', 'hard', 7, 'jee', '0.0591 = 0.0591 log K gives log K = 1, so K = 10.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_057', 'In E = E° − (0.0591/n) log Q at 298 K with n = 2, the term (0.0591/n) equals:', 'mcq', '["0.0591","0.0296","0.118","0.020"]', '0.0296', 'hard', 6, 'jee', '0.0591/2 = 0.0296 V.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_058', 'For Zn | Zn²⁺(1 M) || Cu²⁺(1 M) | Cu (E° = 1.10 V), decreasing [Cu²⁺] causes the EMF to:', 'mcq', '["increase","decrease","stay at 1.10 V","become zero"]', 'decrease', 'hard', 7, 'jee', 'Lower [Cu²⁺] raises Q = [Zn²⁺]/[Cu²⁺], so the EMF decreases below 1.10 V.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_059', 'The relationship between standard Gibbs energy and the equilibrium constant K is:', 'mcq', '["ΔG° = RT ln K","ΔG° = −RT ln K","ΔG° = nF ln K","ΔG° = −RT/ln K"]', 'ΔG° = −RT ln K', 'hard', 7, 'jee', 'ΔG° = −RT ln K links the standard Gibbs energy change to the equilibrium constant.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2'),
('axai_ch07_060', 'For a cell with E°cell = 0.295 V and n = 2 at 298 K, log K is approximately:', 'mcq', '["5","10","20","2"]', '10', 'hard', 8, 'jee', 'E°cell = (0.0591/n) log K → 0.295 = 0.0296 log K → log K ≈ 10.', 'chem', 'ch07', 'ch07t2', 'ch07t2s2')
on conflict (id) do nothing;
