-- ch06t1 "Chemical Equilibrium & Le Chatelier" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch06t1s1 Equilibrium Constant (Kc, Kp)        (axai_ch06_001..015)
--   ch06t1s2 Le Chatelier's Principle & Shifts    (axai_ch06_016..030)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch06t1s1', 'Equilibrium Constant (Kc, Kp)', 'ch06t1', 'ch06', 'chem', 1),
  ('ch06t1s2', 'Le Chatelier''s Principle & Shifts', 'ch06t1', 'ch06', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch06t1s1 Equilibrium Constant (Kc, Kp) =====
('axai_ch06_001', 'At chemical equilibrium, the rates of the forward and reverse reactions are:', 'mcq', '["both zero","equal","forward faster","reverse faster"]', 'equal', 'easy', 1, 'both', 'Dynamic equilibrium is reached when the forward and reverse reaction rates become equal.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_002', 'For the reaction aA + bB ⇌ cC + dD, the equilibrium constant Kc equals:', 'mcq', '["[A]^a[B]^b / [C]^c[D]^d","[C]^c[D]^d / [A]^a[B]^b","[C][D] / [A][B]","([C]+[D]) / ([A]+[B])"]', '[C]^c[D]^d / [A]^a[B]^b', 'easy', 2, 'both', 'By the law of mass action, Kc is the product concentrations over reactant concentrations, each raised to its stoichiometric coefficient.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_003', 'The relationship between Kp and Kc for a gaseous equilibrium is:', 'mcq', '["Kp = Kc(RT)^Δn","Kp = Kc / (RT)^Δn","Kp = Kc + RTΔn","Kp = Kc·R·T·Δn"]', 'Kp = Kc(RT)^Δn', 'easy', 3, 'both', 'Kp = Kc(RT)^Δn, where Δn is the change in the number of moles of gas (products − reactants).', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_004', 'The numerical value of an equilibrium constant depends only on the:', 'mcq', '["pressure","temperature","catalyst used","initial concentrations"]', 'temperature', 'easy', 2, 'both', 'The equilibrium constant is a function of temperature alone for a given reaction.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_005', 'A very large equilibrium constant (Kc ≫ 1) means that at equilibrium:', 'mcq', '["reactants predominate","products predominate","no reaction has occurred","only the catalyst remains"]', 'products predominate', 'easy', 2, 'both', 'A large Kc indicates the equilibrium lies far to the right, so products predominate.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_006', 'For N₂(g) + 3H₂(g) ⇌ 2NH₃(g), the value of Δn(g) used in Kp = Kc(RT)^Δn is:', 'mcq', '["+2","−2","0","−1"]', '−2', 'medium', 4, 'both', 'Δn(g) = moles of gaseous products − reactants = 2 − (1 + 3) = −2.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_007', 'When the number of moles of gaseous products equals that of gaseous reactants, Kp is:', 'mcq', '["greater than Kc","less than Kc","equal to Kc","equal to zero"]', 'equal to Kc', 'medium', 4, 'both', 'If Δn(g) = 0 then (RT)^0 = 1, so Kp = Kc.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_008', 'When the reaction quotient Q is less than Kc, the reaction proceeds in the:', 'mcq', '["reverse direction","forward direction","no net direction","direction that lowers temperature"]', 'forward direction', 'medium', 5, 'both', 'If Q < Kc, more product must form, so the net reaction goes forward until Q = Kc.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_009', 'For H₂(g) + I₂(g) ⇌ 2HI(g), the relation between Kp and Kc is:', 'mcq', '["Kp = Kc(RT)","Kp = Kc / RT","Kp = Kc","Kp = Kc(RT)²"]', 'Kp = Kc', 'medium', 5, 'both', 'Here Δn(g) = 2 − 2 = 0, so Kp = Kc.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_010', 'If the equilibrium constant of a reaction is K, then for the reverse reaction it is:', 'mcq', '["K","−K","1/K","K²"]', '1/K', 'medium', 4, 'both', 'Reversing a reaction inverts its equilibrium constant, giving 1/K.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_011', 'If a balanced equation is multiplied throughout by 2, the new equilibrium constant becomes:', 'mcq', '["2K","K/2","K²","√K"]', 'K²', 'hard', 6, 'both', 'Multiplying a reaction by a factor n raises its equilibrium constant to the power n, so K becomes K².', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_012', 'For 2SO₂(g) + O₂(g) ⇌ 2SO₃(g), the value of Δn(g) is:', 'mcq', '["−1","+1","0","−2"]', '−1', 'hard', 6, 'both', 'Δn(g) = 2 − (2 + 1) = −1.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_013', 'When two reactions with constants K₁ and K₂ are added, the equilibrium constant of the overall reaction is:', 'mcq', '["K₁ + K₂","K₁ − K₂","K₁ × K₂","K₁ / K₂"]', 'K₁ × K₂', 'hard', 7, 'both', 'Adding reactions multiplies their equilibrium constants, so K(overall) = K₁ × K₂.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_014', 'For the equilibrium PCl₅(g) ⇌ PCl₃(g) + Cl₂(g), the units of Kc are:', 'mcq', '["mol L⁻¹","mol⁻¹ L","dimensionless","mol² L⁻²"]', 'mol L⁻¹', 'hard', 7, 'jee', 'Δn = +1, so Kc has units of concentration, i.e. mol L⁻¹.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
('axai_ch06_015', 'For 2HI ⇌ H₂ + I₂ at equilibrium [H₂] = [I₂] = 1 M and [HI] = 2 M. The value of Kc is:', 'mcq', '["0.25","0.5","2","4"]', '0.25', 'hard', 7, 'jee', 'Kc = [H₂][I₂] / [HI]² = (1 × 1) / 2² = 0.25.', 'chem', 'ch06', 'ch06t1', 'ch06t1s1'),
-- ===== ch06t1s2 Le Chatelier's Principle & Shifts =====
('axai_ch06_016', 'Le Chatelier''s principle states that a disturbed equilibrium shifts in the direction that:', 'mcq', '["increases the disturbance","partially counteracts the disturbance","stops the reaction","raises the temperature"]', 'partially counteracts the disturbance', 'easy', 2, 'both', 'A system at equilibrium responds to a change so as to partially offset (counteract) that change.', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_017', 'Adding a catalyst to a reaction at equilibrium:', 'mcq', '["shifts it forward","shifts it backward","does not shift the equilibrium position","increases Kc"]', 'does not shift the equilibrium position', 'easy', 2, 'both', 'A catalyst speeds up both directions equally, so it changes the rate of attaining equilibrium but not its position.', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_018', 'For an exothermic reaction at equilibrium, increasing the temperature shifts the equilibrium:', 'mcq', '["forward","backward","not at all","to completion"]', 'backward', 'easy', 3, 'both', 'Heat is a product in an exothermic reaction, so adding heat shifts the equilibrium toward the reactants (backward).', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_019', 'Increasing the concentration of a reactant shifts the equilibrium:', 'mcq', '["backward","forward","not at all","toward the catalyst"]', 'forward', 'easy', 1, 'both', 'Adding reactant drives the reaction forward to consume the excess.', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_020', 'For N₂(g) + 3H₂(g) ⇌ 2NH₃(g), increasing the pressure shifts the equilibrium toward the side with:', 'mcq', '["more moles of gas","fewer moles of gas","equal moles","no gas"]', 'fewer moles of gas', 'easy', 3, 'both', 'Higher pressure favours the side with fewer gas moles, here the products (2 mol NH₃ vs 4 mol reactants).', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_021', 'In the Haber process N₂ + 3H₂ ⇌ 2NH₃ (exothermic), the yield of NH₃ is favoured by:', 'mcq', '["high temperature and low pressure","low temperature and high pressure","high temperature and high pressure","low temperature and low pressure"]', 'low temperature and high pressure', 'medium', 5, 'both', 'Being exothermic and having fewer product moles, NH₃ formation is favoured by low temperature and high pressure.', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_022', 'For 2SO₂ + O₂ ⇌ 2SO₃, continuously removing SO₃ as it forms causes the equilibrium to shift:', 'mcq', '["backward","forward","not at all","toward O₂"]', 'forward', 'medium', 4, 'both', 'Removing a product drives the reaction forward to replace it.', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_023', 'Adding an inert gas at constant volume to a gaseous equilibrium:', 'mcq', '["shifts it forward","shifts it backward","does not shift it","doubles Kc"]', 'does not shift it', 'medium', 5, 'both', 'At constant volume the partial pressures and concentrations are unchanged, so there is no shift.', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_024', 'Pressure changes have no effect on the equilibrium H₂(g) + I₂(g) ⇌ 2HI(g) because:', 'mcq', '["it is exothermic","Δn(g) = 0","a catalyst is present","HI is a solid"]', 'Δn(g) = 0', 'medium', 5, 'both', 'With equal moles of gas on both sides (Δn = 0), changing pressure does not shift the equilibrium.', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_025', 'For an endothermic reaction, the equilibrium constant Kc:', 'mcq', '["decreases with rising temperature","increases with rising temperature","is independent of temperature","is always 1"]', 'increases with rising temperature', 'medium', 6, 'both', 'For an endothermic reaction, raising the temperature shifts equilibrium forward and increases Kc.', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_026', 'For CaCO₃(s) ⇌ CaO(s) + CO₂(g), the equilibrium shifts forward when:', 'mcq', '["CO₂ is added","pressure is increased","CO₂ is removed","temperature is lowered"]', 'CO₂ is removed', 'hard', 6, 'both', 'Removing the only gaseous product, CO₂, drives the decomposition forward.', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_027', 'For N₂(g) + O₂(g) ⇌ 2NO(g) (endothermic), the maximum yield of NO is obtained at:', 'mcq', '["low temperature","high temperature","high pressure","low temperature and high pressure"]', 'high temperature', 'hard', 6, 'both', 'Being endothermic with Δn = 0, NO formation is favoured by high temperature and is unaffected by pressure.', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_028', 'For 2NO₂(g) ⇌ N₂O₄(g) (exothermic; brown → colourless), cooling the mixture makes it:', 'mcq', '["darker brown","lighter (more colourless)","unchanged in colour","emit light"]', 'lighter (more colourless)', 'hard', 7, 'both', 'Cooling favours the exothermic forward reaction, forming more colourless N₂O₄, so the brown colour fades.', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_029', 'Adding an inert gas at constant pressure to N₂ + 3H₂ ⇌ 2NH₃ shifts the equilibrium toward:', 'mcq', '["the products (fewer moles)","the reactants (more moles)","no shift occurs","NH₃ only"]', 'the reactants (more moles)', 'hard', 8, 'jee', 'At constant pressure the inert gas increases volume, lowering partial pressures, so equilibrium shifts toward the side with more gas moles (reactants).', 'chem', 'ch06', 'ch06t1', 'ch06t1s2'),
('axai_ch06_030', 'Doubling the container volume for PCl₅(g) ⇌ PCl₃(g) + Cl₂(g) shifts the equilibrium:', 'mcq', '["toward PCl₅","toward more dissociation (products)","not at all","toward the catalyst"]', 'toward more dissociation (products)', 'hard', 7, 'jee', 'Increasing volume lowers pressure, favouring the side with more gas moles, i.e. greater dissociation of PCl₅.', 'chem', 'ch06', 'ch06t1', 'ch06t1s2')
on conflict (id) do nothing;
