-- ch10t1 "Nitrogen & Oxygen Family (Gr 15–16)" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch10t1s1 Group 15: Nitrogen Family   (axai_ch10_001..015)
--   ch10t1s2 Group 16: Oxygen Family     (axai_ch10_016..030)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch10t1s1', 'Group 15: Nitrogen Family', 'ch10t1', 'ch10', 'chem', 1),
  ('ch10t1s2', 'Group 16: Oxygen Family', 'ch10t1', 'ch10', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch10t1s1 Group 15: Nitrogen Family =====
('axai_ch10_001', 'The general valence-shell electronic configuration of Group 15 (nitrogen family) elements is:', 'mcq', '["ns²np²","ns²np³","ns²np⁴","ns²np⁵"]', 'ns²np³', 'easy', 1, 'both', 'Group 15 elements have five valence electrons with a stable half-filled configuration ns²np³.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_002', 'The industrial process used to manufacture ammonia is the:', 'mcq', '["Haber process","Contact process","Ostwald process","Solvay process"]', 'Haber process', 'easy', 1, 'both', 'Ammonia is manufactured by the Haber process, combining N₂ and H₂ over an iron catalyst.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_003', 'The shape of an ammonia (NH₃) molecule is:', 'mcq', '["trigonal planar","trigonal pyramidal","tetrahedral","linear"]', 'trigonal pyramidal', 'easy', 2, 'both', 'Nitrogen in NH₃ has three bond pairs and one lone pair, giving a trigonal pyramidal shape.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_004', 'Which element of the nitrogen family is a typical non-metal that exists as a diatomic gas?', 'mcq', '["nitrogen","phosphorus","arsenic","antimony"]', 'nitrogen', 'easy', 2, 'both', 'Nitrogen is a non-metal that occurs naturally as the diatomic gas N₂.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_005', 'The oxidation state of nitrogen in nitric acid (HNO₃) is:', 'mcq', '["+3","+4","+5","-3"]', '+5', 'easy', 3, 'both', 'In HNO₃ nitrogen is bonded to three oxygens and one OH, giving it the maximum +5 oxidation state.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_006', 'The very high stability and inertness of the nitrogen molecule (N₂) is due to its:', 'mcq', '["single bond","double bond","triple bond","ionic bonding"]', 'triple bond', 'medium', 4, 'both', 'N₂ has a strong N≡N triple bond with a high bond dissociation enthalpy, making it chemically inert at room temperature.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_007', 'Nitrogen does not form pentahalides (e.g. NCl₅) whereas phosphorus does, because nitrogen:', 'mcq', '["is too reactive","lacks d-orbitals in its valence shell","is a non-metal","has a small nuclear charge"]', 'lacks d-orbitals in its valence shell', 'medium', 5, 'jee', 'Nitrogen''s valence shell (n=2) has no d-orbitals, so it cannot expand its octet to form pentahalides.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_008', 'The basicity of the hydrides of Group 15 decreases in the order:', 'mcq', '["NH₃ > PH₃ > AsH₃ > SbH₃","SbH₃ > AsH₃ > PH₃ > NH₃","PH₃ > NH₃ > AsH₃ > SbH₃","NH₃ > AsH₃ > PH₃ > SbH₃"]', 'NH₃ > PH₃ > AsH₃ > SbH₃', 'medium', 5, 'jee', 'Basicity falls down the group as the lone pair becomes less available with increasing atom size, so NH₃ is the most basic.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_009', 'In the Ostwald process, ammonia is catalytically oxidised to manufacture:', 'mcq', '["nitric acid","sulphuric acid","ammonium chloride","urea"]', 'nitric acid', 'medium', 4, 'both', 'The Ostwald process oxidises ammonia over a platinum-rhodium catalyst, ultimately producing nitric acid.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_010', 'White phosphorus is more reactive than red phosphorus mainly because it has:', 'mcq', '["a layered structure","an angular strained P₄ tetrahedral structure","a linear chain","a metallic lattice"]', 'an angular strained P₄ tetrahedral structure', 'medium', 5, 'jee', 'White phosphorus consists of P₄ tetrahedra with strained 60° angles, making it far more reactive than the polymeric red form.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_011', 'The brown ring test for the nitrate ion gives a brown complex which is:', 'mcq', '["[Fe(H₂O)₆]²⁺","[Fe(H₂O)₅(NO)]²⁺","[Fe(CN)₆]³⁻","FeSO₄"]', '[Fe(H₂O)₅(NO)]²⁺', 'hard', 7, 'jee', 'The brown ring is the nitrosyl iron complex [Fe(H₂O)₅(NO)]²⁺, confirming the presence of nitrate ions.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_012', 'Among the trihydrides of Group 15, the highest boiling point of NH₃ (compared with PH₃) is due to:', 'mcq', '["greater molecular mass","hydrogen bonding in NH₃","metallic bonding","its larger size"]', 'hydrogen bonding in NH₃', 'hard', 6, 'jee', 'Strong N–H···N hydrogen bonding in ammonia raises its boiling point well above that of the heavier PH₃.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_013', 'The correct order of thermal stability of Group 15 hydrides is:', 'mcq', '["BiH₃ > SbH₃ > AsH₃ > PH₃ > NH₃","NH₃ > PH₃ > AsH₃ > SbH₃ > BiH₃","PH₃ > NH₃ > AsH₃ > SbH₃ > BiH₃","NH₃ > AsH₃ > PH₃ > SbH₃ > BiH₃"]', 'NH₃ > PH₃ > AsH₃ > SbH₃ > BiH₃', 'hard', 7, 'jee', 'As the central atom grows larger down the group, the E–H bond weakens, so thermal stability decreases from NH₃ to BiH₃.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_014', 'Concentrated nitric acid renders iron and aluminium passive because it:', 'mcq', '["dissolves them completely","forms a protective oxide layer on the surface","reduces them to hydrides","forms volatile chlorides"]', 'forms a protective oxide layer on the surface', 'hard', 6, 'jee', 'Concentrated HNO₃ oxidises the metal surface to a thin, adherent oxide film that prevents further reaction (passivation).', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
('axai_ch10_015', 'PCl₅ in the solid state exists as an ionic solid composed of:', 'mcq', '["PCl₄⁺ and PCl₆⁻ ions","PCl₃ and Cl₂","P⁵⁺ and Cl⁻ ions","PCl₅ neutral molecules only"]', 'PCl₄⁺ and PCl₆⁻ ions', 'hard', 8, 'jee', 'Solid PCl₅ is ionic, consisting of tetrahedral PCl₄⁺ cations and octahedral PCl₆⁻ anions.', 'chem', 'ch10', 'ch10t1', 'ch10t1s1'),
-- ===== ch10t1s2 Group 16: Oxygen Family =====
('axai_ch10_016', 'The general valence-shell electronic configuration of Group 16 (oxygen family / chalcogens) is:', 'mcq', '["ns²np³","ns²np⁴","ns²np⁵","ns²np²"]', 'ns²np⁴', 'easy', 1, 'both', 'Group 16 chalcogens have six valence electrons with the configuration ns²np⁴.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_017', 'The industrial process used to manufacture sulphuric acid is the:', 'mcq', '["Contact process","Haber process","Ostwald process","Solvay process"]', 'Contact process', 'easy', 1, 'both', 'Sulphuric acid is manufactured by the Contact process, in which SO₂ is oxidised to SO₃ over a V₂O₅ catalyst.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_018', 'The allotrope of oxygen that protects the Earth from harmful UV radiation is:', 'mcq', '["dioxygen (O₂)","ozone (O₃)","atomic oxygen","peroxide"]', 'ozone (O₃)', 'easy', 2, 'both', 'Ozone (O₃) in the stratosphere absorbs harmful ultraviolet radiation from the Sun.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_019', 'The most common oxidation state of oxygen in its compounds (e.g. water and oxides) is:', 'mcq', '["+2","-1","-2","+4"]', '-2', 'easy', 2, 'both', 'Being highly electronegative, oxygen usually shows the -2 oxidation state in its compounds.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_020', 'The catalyst used in the Contact process for oxidising SO₂ to SO₃ is:', 'mcq', '["iron","platinum","vanadium pentoxide (V₂O₅)","nickel"]', 'vanadium pentoxide (V₂O₅)', 'easy', 3, 'both', 'Vanadium(V) oxide (V₂O₅) is the catalyst that converts SO₂ to SO₃ in the Contact process.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_021', 'The shape of a sulphur dioxide (SO₂) molecule is:', 'mcq', '["linear","bent (angular)","trigonal planar","tetrahedral"]', 'bent (angular)', 'medium', 4, 'both', 'Sulphur in SO₂ has two bond pairs (to oxygen) and one lone pair, giving a bent (angular) shape.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_022', 'Oxygen shows a maximum covalency of two whereas sulphur can show up to six because:', 'mcq', '["sulphur is more electronegative","sulphur has vacant d-orbitals to expand its octet","oxygen is a gas","oxygen has more electrons"]', 'sulphur has vacant d-orbitals to expand its octet', 'medium', 5, 'jee', 'Sulphur''s valence shell (n=3) has accessible d-orbitals, letting it expand its octet, while oxygen (n=2) cannot.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_023', 'The acidic strength of the hydrides of Group 16 increases in the order:', 'mcq', '["H₂O < H₂S < H₂Se < H₂Te","H₂Te < H₂Se < H₂S < H₂O","H₂S < H₂O < H₂Se < H₂Te","H₂O < H₂Se < H₂S < H₂Te"]', 'H₂O < H₂S < H₂Se < H₂Te', 'medium', 5, 'jee', 'As the E–H bond weakens down the group, the hydride loses H⁺ more easily, so acidity increases from H₂O to H₂Te.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_024', 'Oleum is the name given to:', 'mcq', '["dilute sulphuric acid","fuming sulphuric acid (H₂S₂O₇)","sulphurous acid","liquid SO₂"]', 'fuming sulphuric acid (H₂S₂O₇)', 'medium', 4, 'both', 'Oleum (fuming sulphuric acid) is formed by dissolving SO₃ in concentrated H₂SO₄, giving pyrosulphuric acid H₂S₂O₇.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_025', 'The water molecule (H₂O) has a much higher boiling point than H₂S mainly because of:', 'mcq', '["greater molecular mass of water","hydrogen bonding in water","metallic bonding","covalent network in water"]', 'hydrogen bonding in water', 'medium', 5, 'both', 'Strong O–H···O hydrogen bonding in water raises its boiling point far above that of the heavier H₂S.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_026', 'In ozone (O₃), the central oxygen atom is hybridised as:', 'mcq', '["sp","sp²","sp³","sp³d"]', 'sp²', 'hard', 6, 'jee', 'The central oxygen in O₃ has two sigma bonds and one lone pair (plus a delocalised pi system), giving sp² hybridisation and a bent shape.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_027', 'Concentrated sulphuric acid acts as a powerful dehydrating agent; it chars sugar because it:', 'mcq', '["oxidises carbon to CO₂","removes the elements of water leaving carbon","reduces sugar to alcohol","forms a sulphonate"]', 'removes the elements of water leaving carbon', 'hard', 6, 'jee', 'Concentrated H₂SO₄ removes hydrogen and oxygen (as water) from sugar, leaving behind a black mass of carbon.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_028', 'The two S–O bonds in SO₂ are of equal length because of:', 'mcq', '["sp³ hybridisation","resonance (delocalisation of pi electrons)","hydrogen bonding","ionic character"]', 'resonance (delocalisation of pi electrons)', 'hard', 7, 'jee', 'Resonance delocalises the pi electrons over both S–O bonds, making them identical in length and order.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_029', 'The correct order of thermal stability of Group 16 hydrides is:', 'mcq', '["H₂Te > H₂Se > H₂S > H₂O","H₂O > H₂S > H₂Se > H₂Te","H₂S > H₂O > H₂Se > H₂Te","H₂O > H₂Se > H₂S > H₂Te"]', 'H₂O > H₂S > H₂Se > H₂Te', 'hard', 7, 'jee', 'The E–H bond strength decreases down the group, so thermal stability falls from H₂O to H₂Te.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2'),
('axai_ch10_030', 'Sulphur exhibits a greater tendency for catenation than oxygen because:', 'mcq', '["sulphur is more electronegative","the S–S bond is stronger than the O–O bond","oxygen has d-orbitals","sulphur is a gas"]', 'the S–S bond is stronger than the O–O bond', 'hard', 8, 'jee', 'Lone-pair repulsion weakens the small O–O bond, while the larger sulphur forms stronger S–S bonds, so sulphur catenates more readily.', 'chem', 'ch10', 'ch10t1', 'ch10t1s2')
on conflict (id) do nothing;
