-- ch11t2 "Coordination Compounds & IUPAC Naming" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch11t2s1 Werner's Theory & Ligands              (axai_ch11_031..045)
--   ch11t2s2 IUPAC Nomenclature of Complexes        (axai_ch11_046..060)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch11t2s1', 'Werner''s Theory & Ligands', 'ch11t2', 'ch11', 'chem', 1),
  ('ch11t2s2', 'IUPAC Nomenclature of Complexes', 'ch11t2', 'ch11', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch11t2s1 Werner's Theory & Ligands =====
('axai_ch11_031', 'The ions or molecules bound directly to the central metal atom in a coordination compound are called:', 'mcq', '["counter ions","ligands","cations","electrolytes"]', 'ligands', 'easy', 1, 'both', 'Ligands are the ions or neutral molecules that donate electron pairs and bond directly to the central metal atom.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_032', 'The total number of ligand donor atoms bonded to the central metal atom is called the:', 'mcq', '["oxidation number","coordination number","atomic number","valency"]', 'coordination number', 'easy', 1, 'both', 'The coordination number is the number of donor atoms directly bonded to the central metal ion.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_033', 'According to Werner''s theory, the secondary valency of a metal corresponds to its:', 'mcq', '["oxidation state","coordination number","atomic mass","ionisation energy"]', 'coordination number', 'easy', 2, 'both', 'Werner''s secondary (non-ionisable) valency is directed in space and equals the coordination number of the metal.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_034', 'A ligand that binds to the central metal through only one donor atom is called:', 'mcq', '["monodentate","bidentate","polydentate","ambidentate"]', 'monodentate', 'easy', 2, 'both', 'A monodentate ligand (e.g. NH₃, Cl⁻) donates a single electron pair through one donor atom.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_035', 'In the complex [Cu(NH₃)₄]SO₄, the species inside the square brackets is called the:', 'mcq', '["counter ion","coordination sphere","ligand only","central metal only"]', 'coordination sphere', 'easy', 3, 'both', 'The metal together with its ligands enclosed in square brackets forms the coordination sphere.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_036', 'Which of the following is a bidentate ligand?', 'mcq', '["ammonia (NH₃)","chloride (Cl⁻)","ethylenediamine (en)","water (H₂O)"]', 'ethylenediamine (en)', 'medium', 4, 'both', 'Ethylenediamine has two nitrogen donor atoms, so it binds the metal at two sites and is bidentate.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_037', 'The oxidation state of iron in the complex ion [Fe(CN)₆]³⁻ is:', 'mcq', '["+2","+3","+4","0"]', '+3', 'medium', 5, 'both', 'With six CN⁻ ligands (each -1) and an overall charge of -3, the iron must be +3.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_038', 'The coordination number of the central metal in [Co(en)₃]³⁺ is:', 'mcq', '["3","4","6","2"]', '6', 'medium', 5, 'jee', 'Each ethylenediamine (en) is bidentate, so three of them provide six donor atoms, giving a coordination number of 6.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_039', 'A ligand like EDTA⁴⁻ that can bind the central metal through six donor atoms is called:', 'mcq', '["monodentate","bidentate","hexadentate","ambidentate"]', 'hexadentate', 'medium', 4, 'jee', 'EDTA⁴⁻ has two nitrogen and four oxygen donor atoms, so it is a hexadentate chelating ligand.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_040', 'A ligand that can coordinate through either of two different donor atoms (e.g. NO₂⁻ via N or O) is called:', 'mcq', '["bidentate","ambidentate","chelating","polydentate"]', 'ambidentate', 'medium', 5, 'jee', 'An ambidentate ligand such as NO₂⁻ or SCN⁻ has two different donor atoms but uses only one at a time.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_041', 'The extra stability of complexes containing chelating (multidentate) ligands compared with similar monodentate complexes is called the:', 'mcq', '["trans effect","chelate effect","Jahn-Teller effect","inert pair effect"]', 'chelate effect', 'hard', 6, 'jee', 'The chelate effect is the enhanced stability (largely entropy-driven) of complexes formed by ring-forming multidentate ligands.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_042', 'The oxidation state of nickel in the neutral complex [Ni(CO)₄] is:', 'mcq', '["0","+2","+4","-2"]', '0', 'hard', 6, 'jee', 'Carbonyl (CO) is a neutral ligand and the complex is neutral, so nickel is in the zero oxidation state.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_043', 'In Werner''s theory, the primary valency of a metal is:', 'mcq', '["non-ionisable and directional","ionisable and satisfied by negative ions","equal to the coordination number","always zero"]', 'ionisable and satisfied by negative ions', 'hard', 7, 'jee', 'Werner''s primary valency corresponds to the oxidation state; it is ionisable and satisfied by negative ions outside the coordination sphere.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_044', 'For the complex K₄[Fe(CN)₆], the number of ions produced on complete dissociation in water is:', 'mcq', '["2","3","4","5"]', '5', 'hard', 7, 'jee', 'It dissociates into four K⁺ ions and one [Fe(CN)₆]⁴⁻ ion, giving five ions in total.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
('axai_ch11_045', 'The charge on the complex ion formed by Pt with two NH₃ and four Cl⁻ ligands, where platinum is +4, is:', 'mcq', '["+2","0","-2","-4"]', '0', 'hard', 8, 'jee', 'In [Pt(NH₃)₂Cl₄], +4 (Pt) + 0 (2 NH₃) + (-4) (4 Cl⁻) = 0, so the complex is neutral.', 'chem', 'ch11', 'ch11t2', 'ch11t2s1'),
-- ===== ch11t2s2 IUPAC Nomenclature of Complexes =====
('axai_ch11_046', 'In naming a coordination compound, which is named first?', 'mcq', '["the central metal","the ligands","the counter ion","the oxidation state"]', 'the ligands', 'easy', 1, 'both', 'In IUPAC nomenclature the ligands are named first (in alphabetical order), followed by the central metal.', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_047', 'The ligand NH₃ is named in a complex as:', 'mcq', '["ammine","ammonia","amido","azido"]', 'ammine', 'easy', 1, 'both', 'Coordinated ammonia is named "ammine" (with double m) in IUPAC nomenclature.', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_048', 'The ligand H₂O when coordinated is named as:', 'mcq', '["hydro","aqua","oxo","hydroxo"]', 'aqua', 'easy', 2, 'both', 'Coordinated water is named "aqua" in a complex.', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_049', 'When a complex ion carries an overall negative charge, the name of the central metal ends in:', 'mcq', '["-ous","-ic","-ate","-ide"]', '-ate', 'easy', 2, 'both', 'For anionic complexes the metal name takes the suffix "-ate" (e.g. ferrate, cuprate).', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_050', 'The oxidation state of the central metal in a complex is shown in the name by:', 'mcq', '["a subscript","a Roman numeral in parentheses","a prefix di-, tri-","a superscript"]', 'a Roman numeral in parentheses', 'easy', 3, 'both', 'The metal''s oxidation state is written as a Roman numeral in parentheses immediately after its name.', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_051', 'The IUPAC name of [Cu(NH₃)₄]SO₄ is:', 'mcq', '["tetraamminecopper(II) sulphate","copper tetraammine sulphate","tetraamminecopper(I) sulphate","sulphatotetraamminecopper(II)"]', 'tetraamminecopper(II) sulphate', 'medium', 4, 'both', 'Four ammine ligands on copper(II) inside a cationic sphere with sulphate counter ion give tetraamminecopper(II) sulphate.', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_052', 'The IUPAC name of K₄[Fe(CN)₆] is:', 'mcq', '["potassium hexacyanoferrate(II)","potassium hexacyanoferrate(III)","potassium ferrocyanide(II)","tetrapotassium ironcyanide"]', 'potassium hexacyanoferrate(II)', 'medium', 5, 'both', 'Six cyanido ligands and an anionic complex with Fe(II) give potassium hexacyanoferrate(II).', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_053', 'When multiplying prefixes such as di, tri would cause confusion (e.g. for ethylenediamine), the prefixes used are:', 'mcq', '["mono, di, tri","bis, tris, tetrakis","penta, hexa","hemi, sesqui"]', 'bis, tris, tetrakis', 'medium', 5, 'jee', 'For ligands whose names already contain di/tri, the enclosing prefixes bis, tris, tetrakis are used (e.g. tris(ethylenediamine)).', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_054', 'In the formula of a coordination compound, the order of writing inside the bracket is:', 'mcq', '["ligands first, then metal","metal first, then ligands","counter ion first","oxidation state first"]', 'metal first, then ligands', 'medium', 4, 'jee', 'In the formula the central metal symbol is written first, followed by the ligands; in the name the ligands come first.', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_055', 'The IUPAC name of [Co(NH₃)₆]Cl₃ is:', 'mcq', '["hexaamminecobalt(III) chloride","cobalt hexaammine trichloride","hexaamminecobalt(II) chloride","trichloridohexaamminecobalt"]', 'hexaamminecobalt(III) chloride', 'medium', 5, 'both', 'Six ammine ligands on cobalt(III) in a cationic sphere with three chloride counter ions give hexaamminecobalt(III) chloride.', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_056', 'The IUPAC name of [Ni(CO)₄] is:', 'mcq', '["tetracarbonylnickel(0)","nickel tetracarbonyl(II)","tetracarbonylnickelate(0)","nickel(IV) carbonyl"]', 'tetracarbonylnickel(0)', 'hard', 6, 'jee', 'Four carbonyl ligands on neutral nickel give tetracarbonylnickel(0), a neutral complex.', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_057', 'The IUPAC name of the anionic complex [Fe(CN)₆]³⁻ (as in its potassium salt) is:', 'mcq', '["hexacyanoferrate(II)","hexacyanoferrate(III)","hexacyanidoiron(III)","ferricyanide(III)"]', 'hexacyanoferrate(III)', 'hard', 7, 'jee', 'For the anionic complex with Fe(III) and six cyanido ligands, the metal takes the "-ate" suffix: hexacyanoferrate(III).', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_058', 'The IUPAC name of [Pt(NH₃)₂Cl₂] is:', 'mcq', '["diamminedichloridoplatinum(II)","dichloridodiammineplatinum(II)","platinum diamminedichloride","diamminedichloridoplatinum(IV)"]', 'diamminedichloridoplatinum(II)', 'hard', 7, 'jee', 'Ligands are listed alphabetically (ammine before chlorido) on platinum(II): diamminedichloridoplatinum(II).', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_059', 'In the complex [Co(en)₃]₂(SO₄)₃, the oxidation state of cobalt is:', 'mcq', '["+2","+3","+4","+1"]', '+3', 'hard', 6, 'jee', 'With three neutral en ligands and the sulphate balancing, each cobalt carries a +3 charge.', 'chem', 'ch11', 'ch11t2', 'ch11t2s2'),
('axai_ch11_060', 'The correct IUPAC name of K₃[Al(C₂O₄)₃] is:', 'mcq', '["potassium trioxalatoaluminate(III)","potassium trioxalatoaluminium(III)","aluminium tripotassium oxalate","potassium trioxalatoaluminate(II)"]', 'potassium trioxalatoaluminate(III)', 'hard', 8, 'jee', 'Three oxalato ligands on aluminium(III) in an anionic complex with potassium counter ions give potassium trioxalatoaluminate(III).', 'chem', 'ch11', 'ch11t2', 'ch11t2s2')
on conflict (id) do nothing;
