-- ch09t2 "Boron & Carbon Family (Gr 13–14)" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch09t2s1 Group 13: Boron Family    (axai_ch09_031..045)
--   ch09t2s2 Group 14: Carbon Family   (axai_ch09_046..060)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch09t2s1', 'Group 13: Boron Family', 'ch09t2', 'ch09', 'chem', 1),
  ('ch09t2s2', 'Group 14: Carbon Family', 'ch09t2', 'ch09', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch09t2s1 Group 13: Boron Family =====
('axai_ch09_031', 'The general valence-shell electronic configuration of Group 13 (boron family) elements is:', 'mcq', '["ns²np¹","ns²np²","ns¹","ns²np³"]', 'ns²np¹', 'easy', 1, 'both', 'Group 13 elements have three valence electrons, with the configuration ns²np¹.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_032', 'Which element of the boron family is a non-metal?', 'mcq', '["boron","aluminium","gallium","thallium"]', 'boron', 'easy', 1, 'both', 'Boron is the only non-metal (metalloid) in Group 13; the rest are metals.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_033', 'The most abundant metal in the Earth''s crust is:', 'mcq', '["iron","aluminium","calcium","sodium"]', 'aluminium', 'easy', 2, 'both', 'Aluminium is the most abundant metal in the Earth''s crust, found mainly as bauxite and aluminosilicates.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_034', 'The common oxidation state shown by boron and aluminium in their compounds is:', 'mcq', '["+1","+2","+3","+4"]', '+3', 'easy', 2, 'both', 'By using all three valence electrons (ns²np¹), boron and aluminium commonly show the +3 oxidation state.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_035', 'Which ore is the chief source of aluminium?', 'mcq', '["bauxite","cryolite","corundum","feldspar"]', 'bauxite', 'easy', 3, 'both', 'Bauxite (hydrated aluminium oxide) is the principal ore from which aluminium is extracted.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_036', 'Boron trifluoride (BF₃) behaves as a Lewis acid because boron:', 'mcq', '["has a lone pair to donate","has an incomplete octet (electron deficient)","is highly electronegative","carries a negative charge"]', 'has an incomplete octet (electron deficient)', 'medium', 4, 'both', 'With only six electrons around boron, BF₃ has an empty orbital and accepts an electron pair, acting as a Lewis acid.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_037', 'The tendency of the +1 oxidation state to become more stable than +3 down Group 13 is due to the:', 'mcq', '["diagonal relationship","inert pair effect","lanthanoid contraction","screening effect"]', 'inert pair effect', 'medium', 5, 'jee', 'The reluctance of the ns² electron pair to take part in bonding (inert pair effect) makes the +1 state more stable for heavier elements like Tl.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_038', 'In diborane (B₂H₆), the two bridging B–H–B bonds are:', 'mcq', '["normal 2-centre-2-electron bonds","3-centre-2-electron bonds","ionic bonds","hydrogen bonds"]', '3-centre-2-electron bonds', 'medium', 5, 'jee', 'The bridging hydrogens in diborane form banana-shaped 3-centre-2-electron bonds, accounting for its electron-deficient structure.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_039', 'Anhydrous aluminium chloride (AlCl₃) exists as a dimer Al₂Cl₆ in which aluminium attains an octet through:', 'mcq', '["a coordinate (dative) bond from chlorine","hydrogen bonding","metallic bonding","pi back-bonding from hydrogen"]', 'a coordinate (dative) bond from chlorine', 'medium', 5, 'jee', 'Each bridging chlorine donates a lone pair to the electron-deficient aluminium, completing its octet in the Al₂Cl₆ dimer.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_040', 'Aluminium does not react readily with air at room temperature because it:', 'mcq', '["is a noble metal","forms a thin protective oxide layer","is very dense","is highly volatile"]', 'forms a thin protective oxide layer', 'medium', 4, 'both', 'A thin, adherent oxide film of Al₂O₃ forms on the surface and protects the underlying metal from further oxidation.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_041', 'The correct order of acidic strength of the trihalides of boron is:', 'mcq', '["BF₃ > BCl₃ > BBr₃","BBr₃ > BCl₃ > BF₃","BCl₃ > BF₃ > BBr₃","all are equal"]', 'BBr₃ > BCl₃ > BF₃', 'hard', 7, 'jee', 'Back-bonding from halogen to boron is strongest with fluorine and weakest with bromine, so Lewis acidity increases BF₃ < BCl₃ < BBr₃.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_042', 'Aluminium oxide (Al₂O₃) is described as amphoteric because it reacts with:', 'mcq', '["only acids","only bases","both acids and bases","neither acids nor bases"]', 'both acids and bases', 'hard', 6, 'jee', 'Al₂O₃ dissolves in acids to form salts and in alkalis to form aluminates, so it is amphoteric.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_043', 'On hydrolysis, diborane (B₂H₆) gives:', 'mcq', '["boron and hydrogen","boric acid and hydrogen","boron trichloride and water","borax and oxygen"]', 'boric acid and hydrogen', 'hard', 7, 'jee', 'Diborane reacts with water to give orthoboric acid (H₃BO₃) and hydrogen gas.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_044', 'Orthoboric acid (H₃BO₃) acts as a weak monobasic acid because it:', 'mcq', '["donates one proton directly","accepts an OH⁻ ion from water releasing H⁺","donates three protons","is a strong Lewis base"]', 'accepts an OH⁻ ion from water releasing H⁺', 'hard', 8, 'jee', 'Boric acid is a Lewis acid that accepts OH⁻ from water, releasing one H⁺, so it behaves as a weak monobasic acid.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
('axai_ch09_045', 'Thallium most commonly exhibits the +1 oxidation state rather than +3 because of the:', 'mcq', '["large hydration enthalpy of Tl³⁺","inert pair effect","strong metallic bonding","diagonal relationship with carbon"]', 'inert pair effect', 'hard', 6, 'jee', 'In thallium the 6s² electrons resist participation in bonding (inert pair effect), making the +1 state more stable than +3.', 'chem', 'ch09', 'ch09t2', 'ch09t2s1'),
-- ===== ch09t2s2 Group 14: Carbon Family =====
('axai_ch09_046', 'The general valence-shell electronic configuration of Group 14 (carbon family) elements is:', 'mcq', '["ns²np¹","ns²np²","ns²np³","ns²np⁴"]', 'ns²np²', 'easy', 1, 'both', 'Group 14 elements have four valence electrons with the configuration ns²np².', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_047', 'Which element of the carbon family is a non-metal?', 'mcq', '["carbon","silicon","germanium","tin"]', 'carbon', 'easy', 1, 'both', 'Carbon is a non-metal; silicon and germanium are metalloids while tin and lead are metals.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_048', 'The maximum covalency commonly shown by carbon is:', 'mcq', '["2","3","4","6"]', '4', 'easy', 2, 'both', 'Carbon has four valence electrons and no d-orbitals in its valence shell, so its maximum covalency is 4.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_049', 'The property of carbon to form long chains by self-linking is called:', 'mcq', '["catenation","hybridisation","polymerisation","allotropy"]', 'catenation', 'easy', 2, 'both', 'Catenation is the self-linking of like atoms; carbon shows the strongest catenation due to strong C–C bonds.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_050', 'Which oxide of carbon is a poisonous gas that binds strongly to haemoglobin?', 'mcq', '["CO₂","CO","C₃O₂","CaO"]', 'CO', 'easy', 3, 'both', 'Carbon monoxide binds to haemoglobin far more strongly than oxygen, preventing oxygen transport and making it poisonous.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_051', 'In which allotrope of carbon is each carbon atom sp³ hybridised and bonded tetrahedrally?', 'mcq', '["graphite","diamond","fullerene","graphene"]', 'diamond', 'medium', 4, 'both', 'In diamond every carbon is sp³ hybridised and bonded to four others in a rigid 3-D tetrahedral network.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_052', 'Carbon dioxide (CO₂) is a gas while silicon dioxide (SiO₂) is a high-melting solid because:', 'mcq', '["CO₂ has discrete molecules whereas SiO₂ is a giant covalent network","CO₂ is ionic","SiO₂ is a simple molecule","silicon cannot form double bonds with oxygen only"]', 'CO₂ has discrete molecules whereas SiO₂ is a giant covalent network', 'medium', 5, 'jee', 'CO₂ exists as small discrete O=C=O molecules with weak intermolecular forces, while SiO₂ forms a giant three-dimensional Si–O network solid.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_053', 'The tendency for catenation in Group 14 decreases in the order:', 'mcq', '["Si > C > Ge > Sn","C > Si > Ge > Sn","Sn > Ge > Si > C","Ge > C > Si > Sn"]', 'C > Si > Ge > Sn', 'medium', 5, 'jee', 'Catenation depends on bond strength, which falls down the group as atomic size increases, so it is greatest for carbon.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_054', 'In Group 14, the stability of the +2 oxidation state relative to +4 increases down the group due to the:', 'mcq', '["inert pair effect","diagonal relationship","catenation","greater electronegativity"]', 'inert pair effect', 'medium', 5, 'jee', 'The inert pair effect makes the ns² electrons less available for bonding in heavier elements, stabilising the +2 state (e.g. Pb²⁺).', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_055', 'Producer gas is a fuel gas mixture consisting mainly of:', 'mcq', '["CO and N₂","CO₂ and H₂","CH₄ and O₂","CO and H₂"]', 'CO and N₂', 'medium', 4, 'both', 'Producer gas is made by passing air over red-hot coke and consists chiefly of carbon monoxide and nitrogen.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_056', 'In graphite each carbon atom is sp² hybridised, and graphite conducts electricity because:', 'mcq', '["it has free ions","each carbon has one delocalised (free) electron in p-orbitals","of metallic bonding between layers","of hydrogen bonding"]', 'each carbon has one delocalised (free) electron in p-orbitals', 'hard', 6, 'jee', 'Three of carbon''s four electrons form sigma bonds; the fourth occupies a delocalised pi system that allows electrical conduction along the layers.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_057', 'Carbon does not form compounds such as SiF₆²⁻ (i.e. CF₆²⁻ does not exist) because carbon:', 'mcq', '["is too electronegative","lacks vacant d-orbitals in its valence shell","is a non-metal","has a small nuclear charge"]', 'lacks vacant d-orbitals in its valence shell', 'hard', 7, 'jee', 'Carbon''s valence shell (n=2) has no d-orbitals, so it cannot expand its octet, unlike silicon which forms SiF₆²⁻.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_058', 'Which fullerene is the most common and is made of 60 carbon atoms arranged like a football?', 'mcq', '["C₂₀","C₆₀","C₇₀","C₈₄"]', 'C₆₀', 'hard', 6, 'jee', 'Buckminsterfullerene C₆₀ has 60 carbon atoms forming 20 hexagons and 12 pentagons in a soccer-ball shape.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_059', 'Lead(IV) compounds such as PbO₂ are strong oxidising agents because:', 'mcq', '["Pb⁴⁺ readily loses electrons","Pb⁴⁺ is readily reduced to the more stable Pb²⁺ (inert pair effect)","lead is very electropositive","oxygen is in a low oxidation state"]', 'Pb⁴⁺ is readily reduced to the more stable Pb²⁺ (inert pair effect)', 'hard', 7, 'jee', 'Because the +2 state is more stable for lead, Pb⁴⁺ tends to be reduced to Pb²⁺, making PbO₂ a strong oxidising agent.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2'),
('axai_ch09_060', 'Tin shows both +2 and +4 oxidation states, but tin(II) compounds are reducing agents because:', 'mcq', '["Sn²⁺ is easily oxidised to the stable Sn⁴⁺","Sn⁴⁺ is unstable","tin is a noble metal","of strong catenation"]', 'Sn²⁺ is easily oxidised to the stable Sn⁴⁺', 'hard', 8, 'jee', 'For tin the +4 state is more stable than for lead, so Sn²⁺ readily loses electrons to form Sn⁴⁺, acting as a reducing agent.', 'chem', 'ch09', 'ch09t2', 'ch09t2s2')
on conflict (id) do nothing;
