-- ch08t3 "Adsorption, Colloids & Catalysis" — 2 subtopics + 30 questions (5E/5M/5H each).
--   ch08t3s1 Adsorption & Catalysis             (axai_ch08_061..075)
--   ch08t3s2 Colloids & Their Properties        (axai_ch08_076..090)
insert into public.subtopics (id, name, topic_id, chapter_id, subject_id, sort_order) values
  ('ch08t3s1', 'Adsorption & Catalysis', 'ch08t3', 'ch08', 'chem', 1),
  ('ch08t3s2', 'Colloids & Their Properties', 'ch08t3', 'ch08', 'chem', 2)
on conflict (id) do nothing;

insert into public.questions
  (id, text, type, options, correct_answer, difficulty, difficulty_level, exam_type, explanation, subject_id, chapter_id, topic_id, subtopic_id)
values
-- ===== ch08t3s1 Adsorption & Catalysis =====
('axai_ch08_061', 'Adsorption is the accumulation of a substance at the:', 'mcq', '["bulk of a solid","surface of a solid or liquid","centre of a gas","nucleus of an atom"]', 'surface of a solid or liquid', 'easy', 2, 'both', 'Adsorption is a surface phenomenon — molecules concentrate at the interface.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_062', 'The substance that gets adsorbed on a surface is called the:', 'mcq', '["adsorbent","adsorbate","catalyst","colloid"]', 'adsorbate', 'easy', 2, 'both', 'The adsorbate is the species that accumulates on the surface of the adsorbent.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_063', 'The solid surface on which adsorption occurs is called the:', 'mcq', '["adsorbate","adsorbent","solute","solvent"]', 'adsorbent', 'easy', 2, 'both', 'The adsorbent provides the surface on which the adsorbate is held.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_064', 'Physical adsorption (physisorption) involves weak ____ forces:', 'mcq', '["covalent","van der Waals","ionic","metallic"]', 'van der Waals', 'easy', 3, 'both', 'Physisorption is due to weak van der Waals attractions between adsorbate and adsorbent.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_065', 'A catalyst is a substance that alters a reaction rate while remaining ____ at the end:', 'mcq', '["consumed","chemically unchanged","oxidised","vaporised"]', 'chemically unchanged', 'easy', 2, 'both', 'A catalyst changes the rate but is regenerated chemically unchanged.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_066', 'Chemisorption involves the formation of ____ between adsorbate and adsorbent:', 'mcq', '["van der Waals forces","chemical bonds","ionic crystals","hydrogen gas"]', 'chemical bonds', 'medium', 5, 'both', 'Chemisorption involves strong chemical (covalent) bonding to the surface.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_067', 'Adsorption is generally an ____ process (ΔH negative):', 'mcq', '["endothermic","exothermic","athermal","explosive"]', 'exothermic', 'medium', 5, 'both', 'Adsorption releases energy as molecules bind to the surface, so it is exothermic.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_068', 'In the Freundlich adsorption isotherm, x/m varies with pressure p as:', 'mcq', '["p","p^(1/n)","p²","1/p"]', 'p^(1/n)', 'medium', 6, 'both', 'The Freundlich isotherm gives x/m = k·p^(1/n), where n > 1.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_069', 'In heterogeneous catalysis, the catalyst and reactants are in:', 'mcq', '["the same phase","different phases","the gas phase only","solution only"]', 'different phases', 'medium', 5, 'both', 'Heterogeneous catalysis occurs when catalyst and reactants are in different phases (e.g. solid catalyst, gaseous reactants).', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_070', 'The catalyst used in the Haber process for ammonia synthesis is:', 'mcq', '["platinum","finely divided iron","vanadium pentoxide","nickel"]', 'finely divided iron', 'medium', 5, 'both', 'The Haber process uses finely divided iron (with promoters) as the catalyst.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_071', 'Physisorption generally ____ with increasing temperature:', 'mcq', '["increases","decreases","stays constant","becomes chemisorption instantly"]', 'decreases', 'hard', 6, 'jee', 'Being exothermic, physical adsorption is favoured at low temperature and decreases as temperature rises.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_072', 'The catalyst used in the Contact process for the manufacture of H₂SO₄ is:', 'mcq', '["iron","V₂O₅","nickel","platinum only"]', 'V₂O₅', 'hard', 6, 'jee', 'Vanadium pentoxide (V₂O₅) catalyses the oxidation of SO₂ to SO₃ in the Contact process.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_073', 'The high specificity of enzyme catalysis is explained by the:', 'mcq', '["lock-and-key model","collision theory","Freundlich isotherm","common-ion effect"]', 'lock-and-key model', 'hard', 6, 'neet', 'The lock-and-key model accounts for the specific fit between an enzyme and its substrate.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_074', 'A catalyst increases the rate by lowering Ea but does not change the:', 'mcq', '["rate constant","equilibrium position / ΔG","temperature","collision frequency"]', 'equilibrium position / ΔG', 'hard', 7, 'jee', 'A catalyst speeds both directions equally, so it leaves the equilibrium position and ΔG unchanged.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
('axai_ch08_075', 'The hydrogenation of vegetable oils to vanaspati (ghee) uses ____ as the catalyst:', 'mcq', '["finely divided nickel","iron","V₂O₅","platinum black only"]', 'finely divided nickel', 'hard', 6, 'both', 'Finely divided nickel catalyses the hydrogenation of unsaturated oils to solid fats.', 'chem', 'ch08', 'ch08t3', 'ch08t3s1'),
-- ===== ch08t3s2 Colloids & Their Properties =====
('axai_ch08_076', 'In a colloid, the dispersed-phase particle size lies roughly between:', 'mcq', '["1 and 1000 nm","less than 0.1 nm","above 1 mm","exactly 1 m"]', '1 and 1000 nm', 'easy', 3, 'both', 'Colloidal particles are 1–1000 nm, intermediate between true solutions and suspensions.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_077', 'The scattering of a beam of light by colloidal particles is called the:', 'mcq', '["Brownian effect","Tyndall effect","Raman effect","Doppler effect"]', 'Tyndall effect', 'easy', 3, 'both', 'The Tyndall effect is the scattering of light by colloidal-sized particles.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_078', 'In a colloidal sol, the component present in larger amount is the:', 'mcq', '["dispersed phase","dispersion medium","adsorbate","precipitate"]', 'dispersion medium', 'easy', 3, 'both', 'The dispersion medium is the continuous phase present in larger amount.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_079', 'Milk is an example of a colloidal:', 'mcq', '["sol","emulsion","gel","foam"]', 'emulsion', 'easy', 3, 'both', 'Milk is an emulsion — liquid fat droplets dispersed in an aqueous medium.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_080', 'The continuous zig-zag motion of colloidal particles is called:', 'mcq', '["Tyndall motion","Brownian motion","coagulation","peptisation"]', 'Brownian motion', 'easy', 3, 'both', 'Brownian motion is the random zig-zag movement of colloidal particles due to molecular collisions.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_081', 'The process of converting a freshly prepared precipitate into a colloidal sol is called:', 'mcq', '["coagulation","peptisation","dialysis","emulsification"]', 'peptisation', 'medium', 6, 'both', 'Peptisation disperses a precipitate into a sol, usually by adding a suitable electrolyte.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_082', 'The coagulation of a colloid by an electrolyte is governed by the:', 'mcq', '["Henry''s law","Hardy–Schulze rule","Raoult''s law","Kohlrausch''s law"]', 'Hardy–Schulze rule', 'medium', 6, 'both', 'The Hardy–Schulze rule relates coagulating power to the charge of the oppositely charged ion.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_083', 'A lyophobic sol is ____ toward the dispersion medium:', 'mcq', '["solvent-loving","solvent-hating","neutral","gaseous"]', 'solvent-hating', 'medium', 5, 'both', 'Lyophobic (solvent-hating) sols have little affinity for the dispersion medium.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_084', 'The purification of a colloid by removing dissolved ions through a membrane is called:', 'mcq', '["dialysis","filtration","distillation","sublimation"]', 'dialysis', 'medium', 5, 'both', 'Dialysis removes small ions/molecules through a semipermeable membrane, purifying the sol.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_085', 'An example of a gel (liquid dispersed in a solid) is:', 'mcq', '["fog","milk","jelly or cheese","smoke"]', 'jelly or cheese', 'medium', 5, 'both', 'Gels such as jelly and cheese have a liquid dispersed within a solid network.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_086', 'According to the Hardy–Schulze rule, the coagulating power of an ion increases with its:', 'mcq', '["size","charge (valency)","mass","colour"]', 'charge (valency)', 'hard', 7, 'jee', 'The higher the charge of the coagulating ion, the greater its coagulating power.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_087', 'For coagulating a negatively charged As₂S₃ sol, the most effective ion is:', 'mcq', '["Na⁺","Ba²⁺","Al³⁺","Cl⁻"]', 'Al³⁺', 'hard', 7, 'jee', 'The negatively charged sol is best coagulated by the most highly charged cation, Al³⁺.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_088', 'An emulsion is a colloidal dispersion of one ____ in another:', 'mcq', '["solid in solid","liquid in liquid","gas in gas","solid in gas"]', 'liquid in liquid', 'hard', 6, 'both', 'An emulsion is a dispersion of one liquid as fine droplets in another immiscible liquid.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_089', 'Smoke (solid particles dispersed in a gas) is classified as an:', 'mcq', '["emulsion","aerosol","foam","gel"]', 'aerosol', 'hard', 6, 'both', 'Smoke is an aerosol — solid particles dispersed in a gaseous medium.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2'),
('axai_ch08_090', 'Soaps remove greasy dirt mainly by acting as an:', 'mcq', '["oxidising agent","emulsifying agent","adsorbent","electrolyte"]', 'emulsifying agent', 'hard', 7, 'both', 'Soap emulsifies oil/grease into the water as fine droplets, allowing it to be washed away.', 'chem', 'ch08', 'ch08t3', 'ch08t3s2')
on conflict (id) do nothing;
